SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[vwBDPINT_Localidade_Sel]

AS  

select 			
	B.UN_LOCTN_CHNG_CD,
	B.ISO_2_LTR_CNTRY_CD,
	B.ISO_2_LTR_CNTRY_CD	[Country Code],
	P.Nome_Pais				[Country Name],
	B.UN_LOCTN_CD,
	B.UN_LOCTN_NM,
	B.UN_LOCTN_WO_DIACRITICS_NM,
	B.UN_LOCTN_SUBDIV_CD,
	B.UN_LOCTN_STATUS_CD,
	B.UN_LOCTN_FNCTN_POS_1_CD,
	B.UN_LOCTN_FNCTN_POS_2_CD,
	B.UN_LOCTN_FNCTN_POS_3_CD,
	B.UN_LOCTN_FNCTN_POS_4_CD,
	B.UN_LOCTN_FNCTN_POS_5_CD,
	B.UN_LOCTN_FNCTN_POS_6_CD,
	B.UN_LOCTN_FNCTN_POS_7_CD,
	B.UN_LOCTN_FNCTN_POS_8_CD,
	B.UN_LOCTN_LAST_MODFD_DT,
	B.UN_LOCTN_IATA_CD,
	B.UN_LOCTN_LATITUDE_CD,
	B.UN_LOCTN_LONGITUDE_CD,
	B.IATA_3_LTR_CITY_CD,
	B.IATA_3_LTR_AIRPORT_CD,
	B.SCHED_D_K_CD,
	B.CREATED_BY,
	B.CREATED_ON,
	B.LAST_MODFD_BY,
	B.LAST_MODFD_DT,
	B.TEMP_CD_IND,
	B.LGCLLY_DELTD_IND,
	B.BDP_SMART_AIRPORT_NM,
	B.BDP_SMART_CITY_NM,
	B.CMNT_TXT
from BDPINT_Localidade B with(nolock)
	LEFT jOIN Pais P with(nolock) ON P.cd_pais = B. ISO_2_LTR_CNTRY_CD	
  
  
  

GO
