SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--select * from vwINFORMATION_SCHEMA_COLUMNS_Sel
CREATE VIEW [dbo].[vwINFORMATION_SCHEMA_COLUMNS_Sel]
AS

	SELECT COLUMN_NAME,TABLE_NAME FROM INFORMATION_SCHEMA.COLUMNS 
		--where TABLE_NAME = @Table_Name
		--order by table_name
           



GO
