SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[DW_INVC_LN]
AS

SELECT     
	ITEM.NUM_PROC																		[FRWDR_REF_NBR]
	,NULL																				[GROSS_MRGN_AMT]
	,NULL																				[GROSS_MRGN_AMT_CURR_CD]
	,ITEM.VLR_ORG																		[INVC_CHRG_AMT]
	,UPPER(TT.CD_TP_TX)																	[INVC_CHRG_CD]
	,(CASE WHEN ITEM.CD_TP_MOEDA = 'REL' THEN 'BRL' ELSE UPPER(ITEM.CD_TP_MOEDA) END)	[INVC_CHRG_CURR]
	,UPPER(ISNULL(TT.NOME_TP_TX_ING,NOME_TP_TX))										[INVC_CHRG_DESC]
	,ROW_NUMBER() OVER(PARTITION BY FAT.FATCOD  ORDER BY FAT.FATCOD  ASC)				[INVC_LN_SEQ_NBR]
	,ITEM.NUM_PROC																		[INVC_NBR]
	,UPPER(ISNULL(CTA.CD_CRED_DEV_HIA,'')) 												[INVC_VENDOR_NBR]
	,UPPER(ISNULL(PP.NOME_RAZ_SOC,''))													[INVC_VENDOR_NM]
FROM 
	FATURA FAT WITH(NOLOCK)
	JOIN ITEM_FAT ITEM WITH(NOLOCK) ON FAT.FATCOD=ITEM.FATCOD
	JOIN TIPO_TAXA TT WITH(NOLOCK) ON TT.CD_TP_TX=ITEM.CD_TP_TX
	LEFT JOIN VWCTA_CTE CTA WITH(NOLOCK) ON CTA.NUM_PROC_HIA=ITEM.NUM_PROC AND CTA.CD_TP_TX=ITEM.CD_TP_TX AND CTA.DC_HIA='D'
	LEFT JOIN PESSOA PP WITH(NOLOCK) ON PP.CD_PES=CTA.CD_CRED_DEV_HIA
WHERE 
    FAT.FATCOD IN (
        SELECT TOP 1 FATURA.FATCOD
        FROM FATURA FATURA
		JOIN ITEM_FAT ITEM_FAT WITH(NOLOCK) ON FATURA.FATCOD=ITEM_FAT.FATCOD
        WHERE ITEM_FAT.NUM_PROC = ITEM.NUM_PROC 
		AND FATURA.FATSTATUS = 1
        ORDER BY FATURA.FATCOD DESC
    )
	AND	CONVERT(DATETIME,FAT.FATDTEMISSAO,105) > GETDATE() -30
	--AND ITEM.NUM_PROC = 'IMSOL202407018BR'
	AND FATSTATUS = 1
GO
