SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vwOracle_Receivables]

AS
    SELECT 
        T.ID,
T.Category,
T.Ledger_Name,
T.Source,
T.Period,
T.Currency,
T.Batch,
T.Status,
T.Accounting_Flexfield,
T.Account_Description,
T.Company,
T.GL_Account,
T.Product,
T.Resp_Center,
T.Location,
T.Interco,
T.Customer,
T.Future1,
T.Future2,
T.Entered_DR,
T.Entered_CR,
T.Entered_Net,
T.Accounted_DR,
T.Accounted_CR,
T.Accounted_Net,
T.Header_Desc,
T.Line_Description,
T.Journal_Sequence,
T.Accounting_Date,
T.Invoice_Num,
T.Invoice_Date,
T.Trading_Partner_Name,
T.Trading_Partner_Number,
T.Trading_Partner_Site,
T.Account_type,
T.H_Job_No,
T.H_Master_BOL,
T.H_House_BOL,
T.H_Master_Booking_Number,
T.H_Global_Customer,
T.H_Customer_Ref,
T.H_CSR_Email,
T.H_Voucher_Reference_Num,
T.Job_No,
T.Master_BOL,
T.House_BOL,
T.Master_Booking_Number,
T.Global_Customer,
T.Customer_PO,
T.Customer_Ref,
T.CSR_Email,
T.Job_Customer_Account,
T.Customer_Vendor_Group,
T.Charge_Code,
T.Sales_Invoice_Number,
T.Voucher_Reference_Num,
T.Tax_Classification,
T.Actual_Date,
T.Created_by,
T.Original_Invoice_Amount_Entered,
T.Original_Invoice_Amount_Accounting,
T.Exchange_Rate,
T.Open_Amount_Entered,
T.Open_Amount_Local,
T.Oracle_UserID,
T.IsActive,
T.CreateadDate,
T.UpdatedDate
    FROM 
        Oracle_Receivables T WITH(NOLOCK);
 

GO
