SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW TMP_CTAS
AS
SELECT CD_CRED_DEV_HIA CD_PES FROM CTA_CTE_HOU_IMP_AER
UNION
SELECT CD_CRED_DEV_MIA FROM CTA_CTE_MAS_IMP_AER
UNION
SELECT CD_CRED_DEV_HEA FROM CTA_CTE_HOU_EXP_AER
UNION
SELECT CD_CRED_DEV_MEA FROM CTA_CTE_MAS_EXP_aER
UNION 
SELECT CD_CRED_DEV_HEM FROM CTA_CTE_HOU_EXP_MAR
UNION
SELECT CD_CRED_DEV_MEM FROM CTA_CTE_MAS_EXP_MAR
UNION
SELECT CD_CRED_DEV_HIM FROM CTA_CTE_HOU_IMP_MAR
UNION
SELECT CD_CRED_DEV_MIM FROM CTA_CTE_MAS_IMP_MAR


GO
