SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[DW_INVC]
AS

	SELECT     
		ITEM.NUM_PROC																		[FRWDR_REF_NBR]
		,ITEM.NUM_PROC																		[INVC_NBR]
		,FAT.FATDTEMISSAO																	[INVC_DT]
		,NULL																				[INVC_VOID_IND]
		,NULL																				[TOT_BDP_INVC_PAY_VENDOR_AMT]
		,NULL																				[TOT_BDP_INVC_PAY_VENDOR_CURR]
		,SUM(Vlr_RS)																		[INVC_PREPAID_AMT]
		,'BRL'																				[INVC_PREPAID_AMT_CURR]
		,NULL																				[GROSS_MRGN_AMT]
		,'BRL'																				[GROSS_MRGN_AMT_CURR_CD]
		,NULL																				[REV_INVC_PREPAID_AMT]
		,NULL																				[REV_INVC_COLLECT_AMT]
		,NULL																				[REV_INVC_MEMO_AMT]
	FROM 
		FATURA FAT WITH(NOLOCK)
		JOIN ITEM_FAT ITEM WITH(NOLOCK) ON FAT.FATCOD=ITEM.FATCOD
	WHERE 
		FAT.FATCOD IN (
			SELECT TOP 1 FATURA.FATCOD
			FROM FATURA FATURA
			JOIN ITEM_FAT ITEM_FAT WITH(NOLOCK) ON FATURA.FATCOD=ITEM_FAT.FATCOD
			WHERE ITEM_FAT.NUM_PROC = ITEM.NUM_PROC 
			AND FATURA.FATSTATUS = 1
			ORDER BY FATURA.FATCOD DESC
		)
		AND	CONVERT(DATETIME,FAT.FATDTEMISSAO,105) > GETDATE() -30
		--AND ITEM.NUM_PROC = 'IMSOL202407018BR'
		AND FATSTATUS = 1
	GROUP BY 
		ITEM.NUM_PROC,FAT.FATDTEMISSAO	




GO
