SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Saldo_Cta_Cte](
	[Cd_Banco] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Agencia] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[Num_Cta_Cte] [varchar](20) COLLATE Latin1_General_CI_AI NOT NULL,
	[Data_Ref] [varchar](7) COLLATE Latin1_General_CI_AI NOT NULL,
	[Vlr_Saldo] [decimal](12, 2) NOT NULL,
 CONSTRAINT [PK__Saldo_Cta_Cte__0D44F85C] PRIMARY KEY NONCLUSTERED 
(
	[Cd_Banco] ASC,
	[Cd_Agencia] ASC,
	[Num_Cta_Cte] ASC,
	[Data_Ref] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
