SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Adiantamento_POC](
	[POC] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[Data_Criacao] [datetime] NULL,
	[Usuario] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Data_Envio] [datetime] NULL,
 CONSTRAINT [PK_Adiantamento_POC] PRIMARY KEY CLUSTERED 
(
	[POC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
