SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATL_Consulta](
	[Tela] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Campo] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Tipo] [char](1) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_ATL_Consulta] PRIMARY KEY CLUSTERED 
(
	[Tela] ASC,
	[Campo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
