SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HEM_Transb](
	[Num_proc_HEM] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_Transb_HEM] [int] NOT NULL,
	[Navio_HEM] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Transb_HEM] [datetime] NULL,
 CONSTRAINT [PK_HEM_Transb] PRIMARY KEY CLUSTERED 
(
	[Num_proc_HEM] ASC,
	[Id_Transb_HEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[HEM_Transb]  WITH NOCHECK ADD  CONSTRAINT [FK_HEM_Transb_House_Exp_Mar] FOREIGN KEY([Num_proc_HEM])
REFERENCES [dbo].[House_Exp_Mar] ([Num_Proc_HEM])
GO
ALTER TABLE [dbo].[HEM_Transb] CHECK CONSTRAINT [FK_HEM_Transb_House_Exp_Mar]
GO
