SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[aux_ale_INCLUSAO_TASK_CAMILA](
	[num_proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[ETD] [datetime] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
