SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tela_Labels](
	[Cd_Tela] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[lblATL] [int] NOT NULL,
	[ID_ATL_Labels] [int] NOT NULL,
 CONSTRAINT [PK_Tela_Labels] PRIMARY KEY CLUSTERED 
(
	[Cd_Tela] ASC,
	[lblATL] ASC,
	[ID_ATL_Labels] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
