SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tmp_Err_Man](
	[Tmp_Processo] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Tmp_Erro] [varchar](200) COLLATE Latin1_General_CI_AI NOT NULL,
	[Tmp_ID_Machine] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
