SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Integracao](
	[ID_Tp_Int] [int] NOT NULL,
	[Nome_Tp_Int] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Grupo] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Tipo_Integracao] PRIMARY KEY CLUSTERED 
(
	[ID_Tp_Int] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
