SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Levis_DOC](
	[Num_proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[Dt_INS] [datetime] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
