SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[HIM_Transb](
	[Num_proc_HIM] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_Transb_HIM] [int] NOT NULL,
	[Navio_HIM] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Transb_HIM] [datetime] NULL,
 CONSTRAINT [PK_HIM_Transb] PRIMARY KEY CLUSTERED 
(
	[Num_proc_HIM] ASC,
	[Id_Transb_HIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[HIM_Transb]  WITH NOCHECK ADD  CONSTRAINT [FK_HIM_Transb_House_Imp_Mar] FOREIGN KEY([Num_proc_HIM])
REFERENCES [dbo].[House_Imp_Mar] ([Num_Proc_HIM])
GO
ALTER TABLE [dbo].[HIM_Transb] CHECK CONSTRAINT [FK_HIM_Transb_House_Imp_Mar]
GO
