SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Taxa_PC_CHB](
	[CD_Pes_Grupo] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Modal] [char](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Ordem] [int] NULL,
 CONSTRAINT [PK_Tipo_Taxa_PC_CHB] PRIMARY KEY CLUSTERED 
(
	[CD_Pes_Grupo] ASC,
	[Modal] ASC,
	[Cd_Tp_Tx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tipo_Taxa_PC_CHB]  WITH CHECK ADD  CONSTRAINT [FK_Tipo_Taxa_PC_CHB_Tipo_Taxa] FOREIGN KEY([Cd_Tp_Tx])
REFERENCES [dbo].[Tipo_Taxa] ([Cd_Tp_Tx])
GO
ALTER TABLE [dbo].[Tipo_Taxa_PC_CHB] CHECK CONSTRAINT [FK_Tipo_Taxa_PC_CHB_Tipo_Taxa]
GO
ALTER TABLE [dbo].[Tipo_Taxa_PC_CHB]  WITH CHECK ADD  CONSTRAINT [FK_Tipo_Taxa_PC_CHB_Tipo_Taxa_PC_CHB] FOREIGN KEY([CD_Pes_Grupo])
REFERENCES [dbo].[Grupo] ([Cd_Pes_Grupo])
GO
ALTER TABLE [dbo].[Tipo_Taxa_PC_CHB] CHECK CONSTRAINT [FK_Tipo_Taxa_PC_CHB_Tipo_Taxa_PC_CHB]
GO
