SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Aux_Armador](
	[Cd_Arm_Ofc] [varchar](4) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao_Armador] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Aux_Armador] PRIMARY KEY CLUSTERED 
(
	[Cd_Arm_Ofc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
