SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[E_Mix_Consulta_Tipo](
	[ID_consulta_tipo] [int] NOT NULL,
	[Nome_Consulta_Tipo] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY NONCLUSTERED 
(
	[ID_consulta_tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
