SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Campo_Impostos](
	[ID_Imposto] [int] NOT NULL,
	[Cd_Site] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Aliq] [decimal](18, 2) NULL,
	[Tab_Relacionada] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Campo_Retorno] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Descr_Imposto] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Tipo_Campo_Impostos] PRIMARY KEY CLUSTERED 
(
	[ID_Imposto] ASC,
	[Cd_Site] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
