SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATLImportDashBoard_Product_TABLE](
	[UniqueKey] [varchar](517) COLLATE Latin1_General_CI_AI NULL,
	[BDP Ref.] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Account Manager] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Advanced Request Date] [datetime] NULL,
	[Advancement Received Date] [datetime] NULL,
	[Cargo Manifest for Import Declaration - Date] [datetime] NULL,
	[Channel] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHB Collaborator] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHB Y/N] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[CNPJ] [varchar](18) COLLATE Latin1_General_CI_AI NULL,
	[Consignee] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
	[Container Type] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Customs Clearance Date] [datetime] NULL,
	[Customs Clearance Terminal] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Customs Transmission Date] [datetime] NULL,
	[Docs to BDP Billing Date] [datetime] NULL,
	[Entry Number] [varchar](80) COLLATE Latin1_General_CI_AI NULL,
	[Entry Terminal] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[ETA Date] [datetime] NULL,
	[Freight Payment and Fees - Date] [datetime] NULL,
	[Group Name] [varchar](20) COLLATE Latin1_General_CI_AI NOT NULL,
	[House] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[ICMS Exoneration Date] [datetime] NULL,
	[ICMS Payment Date] [datetime] NULL,
	[Import / Export] [varchar](6) COLLATE Latin1_General_CI_AI NOT NULL,
	[Inspection MAPA - Date] [datetime] NULL,
	[Modal] [varchar](12) COLLATE Latin1_General_CI_AI NOT NULL,
	[Original ETA - Date] [datetime] NULL,
	[Packing] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PO Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Register Date] [datetime] NULL,
	[Urgent Y/N] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Transport. Doc Delivery Date] [datetime] NULL,
	[Cargo Type] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Destination] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Last Historic] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Last Historic Client] [varchar](700) COLLATE Latin1_General_CI_AI NULL,
	[ATD Date] [datetime] NULL,
	[Carrier] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CE Mercante] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Government Agency] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Necessidade de LI?] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Notes] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[PDF - BL Original] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - Freight and Fees Receipt] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Vessel] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Cd_BDP Last Historic] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[BL Payment Date] [datetime] NULL,
	[Port of Entry Date] [datetime] NULL,
	[ATA Date] [datetime] NULL,
	[Container Yard Request Date] [datetime] NULL,
	[Original Docs Received - CHB - Date] [datetime] NULL,
	[Received MBL - Date] [datetime] NULL,
	[Process Status] [varchar](32) COLLATE Latin1_General_CI_AI NULL,
	[Final Destination] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[OrderType] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Inland Trucker] [varchar](60) COLLATE Latin1_General_CI_AI NULL,
	[Wood Inspection - Date] [datetime] NULL,
	[Wood Inspection Selected - Date] [datetime] NULL,
	[Wood Inspection Date] [datetime] NULL,
	[Booking Confirmation Date] [datetime] NULL,
	[Docs OK to register - Date] [datetime] NULL,
	[Docs Received Date] [datetime] NULL,
	[ETD Date] [datetime] NULL,
	[Copy of Docs Received - Date] [datetime] NULL,
	[Terminal] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Reason Code Events] [varchar](300) COLLATE Latin1_General_CI_AI NULL,
	[Shipper] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
	[Discharge Conclusion - Date] [datetime] NULL,
	[CSR Name] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Agricultural Batch] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Country of Origin] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Docs to Cambio - Date] [datetime] NULL,
	[BL Released - Date] [datetime] NULL,
	[Delivery Address] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Free Time] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Requerimento] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - COA] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - CE Mercante] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - AFRMM] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - BL] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - CI] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - DI] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - ICMS] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - Invoice] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[PDF - NF] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Good Receipt Date - Actual] [datetime] NULL,
	[Entrega na Planta - Date] [datetime] NULL,
	[PRE DI Date] [datetime] NULL,
	[DI Draft OK - Date - BR only] [datetime] NULL,
	[Draft Approval IMP - Date] [datetime] NULL,
	[Danfe Receipt - Date - BR only] [datetime] NULL,
	[NFE Draft - Date] [datetime] NULL,
	[AFRMM Payment Date] [datetime] NULL,
	[BL Fee Payment - Date] [datetime] NULL,
	[Loading at the Terminal - Date] [datetime] NULL,
	[Ops Comments] [varchar](700) COLLATE Latin1_General_CI_AI NULL,
	[GR Efetivo - Date] [datetime] NULL,
	[Wood Released - Date] [datetime] NULL,
	[Last Historic Client.2] [varchar](120) COLLATE Latin1_General_CI_AI NULL,
	[Product Description] [varchar](500) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
