SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NCM](
	[Id_NCM] [int] NOT NULL,
	[NCM] [char](8) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao_NCM] [varchar](400) COLLATE Latin1_General_CI_AI NOT NULL,
	[Alterado] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[Vencimento] [datetime] NULL,
	[cd_usuario] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[DT_INS] [datetime] NULL,
	[Excecao] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_NCM] PRIMARY KEY CLUSTERED 
(
	[Id_NCM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_NCM] ON [dbo].[NCM]
(
	[NCM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
