SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Servico](
	[Id_TP_Servico] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome_TP_Servico] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Servico] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[ativo] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Usuario] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[dt_ins] [datetime] NULL,
	[JOB] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_TP_Servico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
