SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Handling_MEA](
	[Num_Proc_MEA] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Hand_MEA_1] [varchar](300) COLLATE Latin1_General_CI_AI NULL,
	[Hand_MEA_2] [varchar](300) COLLATE Latin1_General_CI_AI NULL,
	[Hand_MEA_3] [varchar](300) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
