SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Banco](
	[id_tp_banco] [int] IDENTITY(1,1) NOT NULL,
	[nome_tp_banco] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_full_banco] [varchar](200) COLLATE Latin1_General_CI_AI NOT NULL,
	[Ativo] [bit] NOT NULL,
	[Cd_Usuario] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[dt_ins] [datetime] NULL,
 CONSTRAINT [PK_Tipo_Banco] PRIMARY KEY CLUSTERED 
(
	[id_tp_banco] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tipo_Banco] ADD  CONSTRAINT [DF_Tipo_Banco_Ativo]  DEFAULT ((1)) FOR [Ativo]
GO
