SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Config](
	[CfgVerMaj] [varchar](4) COLLATE Latin1_General_CI_AI NOT NULL,
	[CfgVerMin] [varchar](4) COLLATE Latin1_General_CI_AI NOT NULL,
	[CfgVerRev] [varchar](4) COLLATE Latin1_General_CI_AI NOT NULL,
	[CfgUltAtu] [datetime] NOT NULL,
	[CfgRPSFile] [int] NOT NULL,
	[CfgRPSRecFile] [int] NOT NULL,
 CONSTRAINT [PK_Config] PRIMARY KEY CLUSTERED 
(
	[CfgVerMaj] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Config] ADD  CONSTRAINT [DF_Config_CfgRPSFile]  DEFAULT (1) FOR [CfgRPSFile]
GO
ALTER TABLE [dbo].[Config] ADD  CONSTRAINT [DF_Config_CfgRPSRecFile]  DEFAULT ((0)) FOR [CfgRPSRecFile]
GO
