SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Compra_Venda_CP](
	[Cd_CV] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao_CV] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Compra_Venda_CP] PRIMARY KEY CLUSTERED 
(
	[Cd_CV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
