SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Pais_M49](
	[Cd_Pais] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[cd_m49] [varchar](5) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
