SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[log_integ_contab](
	[LicId] [int] IDENTITY(1,1) NOT NULL,
	[LicDescricao] [varchar](100) COLLATE Latin1_General_CI_AI NOT NULL,
	[LicDocto] [varchar](20) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_log_integ_contab] PRIMARY KEY CLUSTERED 
(
	[LicId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
