SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Container](
	[Cd_Tp_Cont] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Cont] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_CC_Ofc] [char](2) COLLATE Latin1_General_CI_AI NULL,
	[CD_Smart] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[Capacidade_M3] [float] NULL,
	[Carrier_Code] [varchar](5) COLLATE Latin1_General_CI_AI NULL,
	[Qtd_Teus] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[Cd_Tp_Cont] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nome_Tp_Cont] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
