SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SIM_UoM](
	[Cod_SIM] [varchar](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[Sim_Descricao] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_SIM_UoM] PRIMARY KEY CLUSTERED 
(
	[Cod_SIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
