SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Data_Pedidos](
	[Cd_Pedido] [int] NOT NULL,
	[ID_Ref] [int] NOT NULL,
	[Data] [datetime] NULL,
	[IDDtPedidos] [bigint] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

GO
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20240603-093751] ON [dbo].[Data_Pedidos]
(
	[IDDtPedidos] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
