SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Saldo_Adiantamento_Temp](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Apelido] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Saldo_Anterior] [float] NULL,
	[Movimento_Atual] [float] NULL,
	[Saldo_Final] [float] NULL,
	[Data] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Saldo_Adiantamento_Temp] PRIMARY KEY CLUSTERED 
(
	[Num_Proc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
