SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NF_Extract](
	[ID] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Name] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[JOB_Master] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[IC_Number] [bigint] NULL,
	[Delete_YN] [bit] NULL,
	[delete_Dt] [datetime] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [I] ON [dbo].[NF_Extract]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
