SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[E_AirFreight_Shipment_Description_Codes](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Meaning] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Abbr_Code] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
	[Notes] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_E_AirFreight_Shipment_Description_Codes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
