SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Log_FollowUp_Envio](
	[ID_Envio] [bigint] IDENTITY(1,1) NOT NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Envio] [datetime] NULL,
	[Assunto] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[CorpoMSG] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[Anexo] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Destinatario] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Log_FollowUp_Envio] PRIMARY KEY CLUSTERED 
(
	[ID_Envio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
