SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Armador](
	[Cd_Armador] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Armador] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Arm_Ofc] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[SCAC] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[CNPJ] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[FreeTime] [int] NULL,
	[dt_criacao] [datetime] NULL,
	[Cd_Termo] [int] NULL,
	[GIX_Armador] [bit] NULL,
	[SAP_Code] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Booking_Request] [bit] NULL,
 CONSTRAINT [PK__Armador__778AC167] PRIMARY KEY CLUSTERED 
(
	[Cd_Armador] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Armador__634EBE90] UNIQUE NONCLUSTERED 
(
	[Nome_Armador] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Armador]  WITH NOCHECK ADD  CONSTRAINT [FK_Armador_Armador1] FOREIGN KEY([Cd_Armador])
REFERENCES [dbo].[Armador] ([Cd_Armador])
GO
ALTER TABLE [dbo].[Armador] CHECK CONSTRAINT [FK_Armador_Armador1]
GO
