SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Historico_Pro_Exp_Mar](
	[Num_Prop_EM] [varchar](11) COLLATE Latin1_General_CI_AI NOT NULL,
	[Hist_PEM] [varchar](2000) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_Prop_EM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Historico_Pro_Exp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Historico__Num_P__7DCDAAA2] FOREIGN KEY([Num_Prop_EM])
REFERENCES [dbo].[Proposta_Exp_Mar] ([Num_Prop_EM])
GO
ALTER TABLE [dbo].[Historico_Pro_Exp_Mar] CHECK CONSTRAINT [FK__Historico__Num_P__7DCDAAA2]
GO
