SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Locais_Atrac](
	[ID_Loc_Atrac] [int] NOT NULL,
	[Nome_Loc_Atrac] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Locais_Atrac] PRIMARY KEY CLUSTERED 
(
	[ID_Loc_Atrac] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
