SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Centro_Custo](
	[Cd_Centro_Custo] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Centro_Custo] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Conta_C] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
PRIMARY KEY NONCLUSTERED 
(
	[Cd_Centro_Custo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
