SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[House_BDP_OUT](
	[Num_Proc_HBO] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Dt_Emis_HBO] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Descr_Serv_HBO] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[cd_cliente_hbo] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Tp_Oper] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_House_BDP_OUT] PRIMARY KEY CLUSTERED 
(
	[Num_Proc_HBO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
