SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Report_Parametro](
	[ID_Report] [int] NOT NULL,
	[Ordem] [int] NOT NULL,
	[Descr] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Tipo] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Report_Parametro] PRIMARY KEY CLUSTERED 
(
	[ID_Report] ASC,
	[Ordem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
