SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmpLOG](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Job] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[cd_usuario] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[host] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[session_id] [int] NULL,
 CONSTRAINT [PK_tmpLOG] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
