SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Localidade](
	[Cd_Local] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Local] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cidade_Local] [varchar](25) COLLATE Latin1_General_CI_AI NOT NULL,
	[Pais_Local] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Regiao] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Aerop] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Porto] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Gate] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[BITRI] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Pais] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[IATACODE] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SCAC] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[Desat_loc] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[dt_criacao] [datetime] NOT NULL,
 CONSTRAINT [PK__Localidade__114A936A] PRIMARY KEY CLUSTERED 
(
	[Cd_Local] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Localidade__01D345B0] UNIQUE NONCLUSTERED 
(
	[Nome_Local] ASC,
	[Porto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Localidade__02C769E9] UNIQUE NONCLUSTERED 
(
	[Nome_Local] ASC,
	[Aerop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Localidade]  WITH NOCHECK ADD  CONSTRAINT [FK__Localidad__Cd_Re__16CE6296] FOREIGN KEY([Cd_Regiao])
REFERENCES [dbo].[Regiao] ([Cd_Regiao])
GO
ALTER TABLE [dbo].[Localidade] CHECK CONSTRAINT [FK__Localidad__Cd_Re__16CE6296]
GO
