SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Fatura_CHB_Item](
	[Fatura_CC] [char](17) COLLATE Latin1_General_CI_AI NOT NULL,
	[Item] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_tp_tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Vlr_PC] [float] NULL,
	[Tp_Pgto] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[Imprime] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[DC] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[idfatchbitem] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Fatura_CHB_Item] PRIMARY KEY CLUSTERED 
(
	[Fatura_CC] ASC,
	[Item] ASC,
	[Cd_tp_tx] ASC,
	[DC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20200515-162707] ON [dbo].[Fatura_CHB_Item]
(
	[idfatchbitem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
