SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Integracao_Layout](
	[Cd_Layout] [int] NOT NULL,
	[Nome_Layout] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Integracao_Layout] PRIMARY KEY CLUSTERED 
(
	[Cd_Layout] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
