SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Livro_Contabil](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Ano] [int] NOT NULL,
	[Mes] [int] NOT NULL,
	[Numero] [int] NULL,
	[Data] [datetime] NULL,
	[Dt_Ins] [datetime] NULL,
	[cd_usuario] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Ativo] [bit] NULL,
 CONSTRAINT [PK_Livro_Contabil_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
