SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CtaCtbLivro](
	[Desc_Cta_Ctb] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cta_Ctb] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
