SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Proposta_Tar_Aer](
	[PROCOD] [varchar](12) COLLATE Latin1_General_CI_AI NOT NULL,
	[PRAID] [int] NOT NULL,
	[PTARangMin] [float] NOT NULL,
	[PTARangMax] [float] NOT NULL,
	[PTAValor] [float] NOT NULL,
 CONSTRAINT [PK_Proposta_Tar_Aer_1] PRIMARY KEY CLUSTERED 
(
	[PROCOD] ASC,
	[PRAID] ASC,
	[PTARangMin] ASC,
	[PTARangMax] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Proposta_Tar_Aer]  WITH CHECK ADD  CONSTRAINT [FK_Proposta_Tar_Aer_Proposta_Rot_Aer] FOREIGN KEY([PROCOD], [PRAID])
REFERENCES [dbo].[Proposta_Rot_Aer] ([PROCOD], [PRAID])
GO
ALTER TABLE [dbo].[Proposta_Tar_Aer] CHECK CONSTRAINT [FK_Proposta_Tar_Aer_Proposta_Rot_Aer]
GO
