SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Pedido](
	[cd_Tp_Pedido] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Pedido] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Nome_TP_Pedido_PT] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Pedido] PRIMARY KEY CLUSTERED 
(
	[cd_Tp_Pedido] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
