SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Rel_221_Doc_Anexo](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_DC] [int] NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
