SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Represent_Manif](
	[Cd_Represent] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Represent] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[CPF_Represent] [char](14) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Represent_Manif] PRIMARY KEY CLUSTERED 
(
	[Cd_Represent] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
