SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RPS_Situacao](
	[SitId] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[SitDescricao] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_RPS_Situacao] PRIMARY KEY CLUSTERED 
(
	[SitId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
