SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Historico_Imp_Aer](
	[Num_Proc_HIA] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Hist_IA] [varchar](2000) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_Proc_HIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Historico_Imp_Aer]  WITH NOCHECK ADD  CONSTRAINT [FK__Historico__Num_P__405A880E] FOREIGN KEY([Num_Proc_HIA])
REFERENCES [dbo].[House_Imp_Aer] ([Num_Proc_HIA])
GO
ALTER TABLE [dbo].[Historico_Imp_Aer] CHECK CONSTRAINT [FK__Historico__Num_P__405A880E]
GO
