SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AX_DOC_XML_NEW](
	[ID_AX] [bigint] NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[Cd_tp_Tx_ATL] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[DC] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
	[Cancel] [bit] NULL,
	[Dt_Envio] [datetime] NULL,
	[XML_DOC] [xml] NULL,
	[Nome_Arquivo] [varchar](75) COLLATE Latin1_General_CI_AI NULL,
	[Verificado] [bit] NULL,
	[MessageId] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Reenvio] [datetime] NULL,
	[ErrorMessage] [varchar](5000) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE CLUSTERED INDEX [ClusteredIndex-20200428-153716] ON [dbo].[AX_DOC_XML_NEW]
(
	[ID_AX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
