SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Classe](
	[Cd_Tp_Classe] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Classe] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY NONCLUSTERED 
(
	[Cd_Tp_Classe] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
