SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PDF2ATL_Group](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Id_Dc] [int] NOT NULL,
	[Cd_Pes_Grupo] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Modal] [varchar](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[Origin] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[Ativo] [bit] NOT NULL,
	[Dt_Ins] [datetime] NULL,
	[Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_PDF2ATL_Group] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[Id_Dc] ASC,
	[Cd_Pes_Grupo] ASC,
	[Cd_Tp_Modal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[PDF2ATL_Group]  WITH CHECK ADD  CONSTRAINT [FK_PDF2ATL_Group_Grupo] FOREIGN KEY([Cd_Pes_Grupo])
REFERENCES [dbo].[Grupo] ([Cd_Pes_Grupo])
GO
ALTER TABLE [dbo].[PDF2ATL_Group] CHECK CONSTRAINT [FK_PDF2ATL_Group_Grupo]
GO
ALTER TABLE [dbo].[PDF2ATL_Group]  WITH CHECK ADD  CONSTRAINT [FK_PDF2ATL_Group_Tipo_Doc_Cliente] FOREIGN KEY([Id_Dc])
REFERENCES [dbo].[Tipo_Doc_Cliente] ([ID_DC])
GO
ALTER TABLE [dbo].[PDF2ATL_Group] CHECK CONSTRAINT [FK_PDF2ATL_Group_Tipo_Doc_Cliente]
GO
ALTER TABLE [dbo].[PDF2ATL_Group]  WITH CHECK ADD  CONSTRAINT [FK_PDF2ATL_Group_Tipo_Modal_Imp_Exp] FOREIGN KEY([Cd_Tp_Modal])
REFERENCES [dbo].[Tipo_Modal_Imp_Exp] ([CD_TP_MODAL])
GO
ALTER TABLE [dbo].[PDF2ATL_Group] CHECK CONSTRAINT [FK_PDF2ATL_Group_Tipo_Modal_Imp_Exp]
GO
