SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Alerta_Grupo](
	[cd_grupo_alerta] [int] NOT NULL,
	[Nome_Grupo_Alerta] [varchar](250) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Alerta_Grupo] PRIMARY KEY CLUSTERED 
(
	[cd_grupo_alerta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
