SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Hist_Sol_Pgto_Cta_Cte](
	[HSGID] [bigint] NOT NULL,
	[HSGSeq] [int] NOT NULL,
	[Cd_Tp_Ocor] [int] NOT NULL,
	[HSGDescr] [varchar](500) COLLATE Latin1_General_CI_AI NOT NULL,
	[HSGData] [datetime] NOT NULL,
	[Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NOT NULL,
	[Disp_Cliente] [bit] NOT NULL,
	[HSGDataPrev] [datetime] NULL,
 CONSTRAINT [PK_Hist_Sol_Pgto_Cta_Cte] PRIMARY KEY CLUSTERED 
(
	[HSGID] ASC,
	[HSGSeq] ASC,
	[Cd_Tp_Ocor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
