SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Fatura_ARG_Det](
	[ID_Fat] [int] NOT NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_tp_Moeda] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[DC] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Valor_Org] [float] NOT NULL,
	[Paridade] [float] NULL,
	[Valor_ARP] [float] NOT NULL,
	[Valor_IVA_ARP] [float] NULL,
	[IDFatDet] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_Fatura_ARG_Det] PRIMARY KEY CLUSTERED 
(
	[IDFatDet] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20200514-151826] ON [dbo].[Fatura_ARG_Det]
(
	[IDFatDet] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fatura_ARG_Det]  WITH CHECK ADD  CONSTRAINT [FK_Fatura_ARG_Det_Tipo_Moeda] FOREIGN KEY([Cd_tp_Moeda])
REFERENCES [dbo].[Tipo_Moeda] ([Cd_Tp_Moeda])
GO
ALTER TABLE [dbo].[Fatura_ARG_Det] CHECK CONSTRAINT [FK_Fatura_ARG_Det_Tipo_Moeda]
GO
ALTER TABLE [dbo].[Fatura_ARG_Det]  WITH CHECK ADD  CONSTRAINT [FK_Fatura_ARG_Det_Tipo_Taxa] FOREIGN KEY([Cd_Tp_Tx])
REFERENCES [dbo].[Tipo_Taxa] ([Cd_Tp_Tx])
GO
ALTER TABLE [dbo].[Fatura_ARG_Det] CHECK CONSTRAINT [FK_Fatura_ARG_Det_Tipo_Taxa]
GO
