SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Produto_CHB_Det](
	[cd_prod] [int] NOT NULL,
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Porcentagem] [float] NULL,
 CONSTRAINT [PK_Produto_CHB_Det] PRIMARY KEY CLUSTERED 
(
	[cd_prod] ASC,
	[Cd_Tp_Tx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Produto_CHB_Det]  WITH CHECK ADD  CONSTRAINT [FK_Produto_CHB_Det_Produto_CHB] FOREIGN KEY([cd_prod])
REFERENCES [dbo].[Produto_CHB_ERRO] ([cd_prod])
GO
ALTER TABLE [dbo].[Produto_CHB_Det] CHECK CONSTRAINT [FK_Produto_CHB_Det_Produto_CHB]
GO
ALTER TABLE [dbo].[Produto_CHB_Det]  WITH CHECK ADD  CONSTRAINT [FK_Produto_CHB_Det_Produto_CHB_Det] FOREIGN KEY([Cd_Tp_Tx])
REFERENCES [dbo].[Tipo_Taxa] ([Cd_Tp_Tx])
GO
ALTER TABLE [dbo].[Produto_CHB_Det] CHECK CONSTRAINT [FK_Produto_CHB_Det_Produto_CHB_Det]
GO
