SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Type_BuscaCashFlow](
	[ID_BuscaCashFlow] [int] NOT NULL,
	[Nome_BuscaCashFlow] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Type_BuscaCashFlow] PRIMARY KEY CLUSTERED 
(
	[ID_BuscaCashFlow] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
