SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Altera_BL](
	[num_proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[cmbShipper] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[txtShipper] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[cmbConsignee] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[txtConsignee] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[cmbNotify] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[txtNotify] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[cmbOrigin] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[cmbLoading] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[cmbDelivery] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[cmbFinalDestination] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[cmbCarrier] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[cmbVoyage] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[txtVessel] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[cd_usuario] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[status] [bit] NULL,
	[dt_ins] [datetime] NULL,
	[cmbCiaAerea] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[txtVoo] [varchar](13) COLLATE Latin1_General_CI_AI NULL,
	[txtVoyage] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[cmbVessel] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[cmbIssuing] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuing] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtCarriage] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[txtCustoms] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[txtAmount] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[txtSignatureShipper] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[txtSignatureCarrier] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperPostcodeCode] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperStreetName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperCityName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperCountryID] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperCountryName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperPersonName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperDepartmentName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperDirectTelephoneCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperFaxCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtShipperURIEmailCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneePostcodeCode] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeStreetName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeCityName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeCountryID] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeCountryName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneePersonName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeDepartmentName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeDirectTelephoneCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeFaxCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtConsigneeURIEmailCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyPostcodeCode] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyStreetName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyCityName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyCountryID] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyCountryName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyPersonName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyDepartmentName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyDirectTelephoneCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyFaxCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtNotifyURIEmailCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingPostcodeCode] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingStreetName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingCityName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingCountryID] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingCountryName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingPersonName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingDepartmentName] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingDirectTelephoneCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingFaxCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[txtIssuingURIEmailCommunication] [varchar](200) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
