SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Container_Hou_Imp_Mar](
	[Num_Proc_MIM] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Item_Cont_IM] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Num_Proc_HIM] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK__Container_Hou_Im__5224328E] PRIMARY KEY CLUSTERED 
(
	[Num_Proc_MIM] ASC,
	[Item_Cont_IM] ASC,
	[Num_Proc_HIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_Container_Hou_Imp_Mar_01] ON [dbo].[Container_Hou_Imp_Mar]
(
	[Num_Proc_HIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Container_Hou_Imp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Container__Num_P__2A6B46EF] FOREIGN KEY([Num_Proc_HIM])
REFERENCES [dbo].[House_Imp_Mar] ([Num_Proc_HIM])
GO
ALTER TABLE [dbo].[Container_Hou_Imp_Mar] CHECK CONSTRAINT [FK__Container__Num_P__2A6B46EF]
GO
ALTER TABLE [dbo].[Container_Hou_Imp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Container_Hou_Im__2B5F6B28] FOREIGN KEY([Num_Proc_MIM], [Item_Cont_IM])
REFERENCES [dbo].[Container_Mas_Imp_Mar] ([Num_Proc_MIM], [Item_Cont_IM])
GO
ALTER TABLE [dbo].[Container_Hou_Imp_Mar] CHECK CONSTRAINT [FK__Container_Hou_Im__2B5F6B28]
GO
