SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AKZO_FUN](
	[BDP_CSR] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Nome_PO] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Modal] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[Ref_BDP] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Consignee] [varchar](20) COLLATE Latin1_General_CI_AI NOT NULL,
	[CNPJ] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[Master] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[House] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[PO] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[CustomerPO] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Cod_Prod] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Produto] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Origem] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Destino] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Carrier] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Navio_Voo] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Containers_VOL] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Nome_Terminal] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[LI] [varchar](80) COLLATE Latin1_General_CI_AI NULL,
	[Def_LI] [datetime] NULL,
	[ETD] [datetime] NULL,
	[ATD] [datetime] NULL,
	[ETA] [datetime] NULL,
	[ATA] [datetime] NULL,
	[Chegada_Docs] [datetime] NULL,
	[Entrada_Terminal] [datetime] NULL,
	[Presenca_Carga] [datetime] NULL,
	[DI] [varchar](80) COLLATE Latin1_General_CI_AI NULL,
	[Data_DI] [datetime] NULL,
	[Dt_Desemb] [datetime] NULL,
	[DSM_Ref] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Num_Invoice] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Canal] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Entr_Docs_Transp] [datetime] NULL,
	[Entrega_Planta] [datetime] NULL,
	[Historico] [varchar](700) COLLATE Latin1_General_CI_AI NULL,
	[Prest_Contas] [datetime] NULL,
	[Desova] [datetime] NULL,
	[Digitacao] [datetime] NULL,
	[Containers] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[TEUS] [int] NULL,
	[NFE] [datetime] NULL,
	[Notes] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[Nome_Grupo] [varchar](20) COLLATE Latin1_General_CI_AI NOT NULL,
	[N_LI] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Sol_Numerario] [datetime] NULL,
	[Shipper] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Ref_Consolidada] [varchar](14) COLLATE Latin1_General_CI_AI NULL,
	[Incoterm] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Urgente] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_BL_Original] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_Invoice] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_Packing] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_Doc_Embarque] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_Shipping] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_DI_Number] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_AFRMM] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_CI_Number] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[SN_Prestacao] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Prev_Entrega] [datetime] NULL,
	[EnvDrafCom] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[LI_dtVcto] [datetime] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
