SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Grupo](
	[Cd_Pes_Grupo] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Grupo] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Smart_EXP] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Smart_IMP] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Admin] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Unit] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[AX_GRUPO] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Responsavel] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Grupo] PRIMARY KEY CLUSTERED 
(
	[Cd_Pes_Grupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Grupo] ON [dbo].[Grupo]
(
	[Grupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
