SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Data](
	[ID_Tp_Data] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome_Tp_Data] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Data] PRIMARY KEY CLUSTERED 
(
	[ID_Tp_Data] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
