SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[E_AirFreight_Rate_Class_Codes](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Codigo] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Nome] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_E_AirFreight_Rate_Class_Codes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
