SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Fatura](
	[Cd_Tp_Fatura] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Fatura] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Fatura] PRIMARY KEY CLUSTERED 
(
	[Cd_Tp_Fatura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
