SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_cta_cte](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Valor_Org] [decimal](12, 2) NULL,
	[Paridade] [float] NULL,
	[Vlr_Pgto_Rcto] [decimal](12, 2) NULL,
	[DC] [char](10) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_tmp_cta_cte] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
