SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SI_Imp_Aer](
	[Num_Proc_SIA] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Obs_SIA] [varchar](1000) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
