SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Log_WebService_Eventos](
	[Seq] [int] NOT NULL,
	[Interface] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Tipo] [varchar](250) COLLATE Latin1_General_CI_AI NULL,
	[Responsavel] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Log_WebService_Eventos] PRIMARY KEY CLUSTERED 
(
	[Seq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
