SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Pedido_Det_Perigoso](
	[cd_pedido] [int] NOT NULL,
	[cd_produto] [int] NOT NULL,
	[Item] [varchar](6) COLLATE Latin1_General_CI_AI NOT NULL,
	[Lote] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[HAZMAT_CD] [varchar](7) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_CLASS_CD] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_DESC] [varchar](300) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_CONTACT] [varchar](24) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_PAGE] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_FPOINT] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_FPOINT_CD] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_PULL_DESC_FRM_BDP] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_ORG_DESC] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
	[HAZMAT_DESC_QUAL] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Pedido_Det_Perigoso] PRIMARY KEY CLUSTERED 
(
	[cd_pedido] ASC,
	[cd_produto] ASC,
	[Item] ASC,
	[Lote] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
