SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Fatura_ARG_Det_Index](
	[ID_Fat] [int] NOT NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_tp_Moeda] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[DC] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Valor_Org] [float] NOT NULL,
	[Paridade] [float] NULL,
	[Valor_ARP] [float] NOT NULL,
	[Valor_IVA_ARP] [float] NULL,
 CONSTRAINT [PK_Fatura_ARG_Det_Index] PRIMARY KEY CLUSTERED 
(
	[ID_Fat] ASC,
	[Num_Proc] ASC,
	[Cd_Tp_Tx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
