SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SI_Imp_Mar](
	[Num_Proc_SIM] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Obs_Sim] [varchar](1000) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
