SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Grupo_Acesso](
	[Cd_Tela] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Pes_Grupo] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Leitura] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[Gravacao] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[Exclusao] [char](1) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Grupo_Pessoa_Acesso] PRIMARY KEY CLUSTERED 
(
	[Cd_Tela] ASC,
	[Cd_Pes_Grupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
