SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Oracle_Receivables](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Category] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Ledger_Name] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Source] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Period] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Currency] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Batch] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Status] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Accounting_Flexfield] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Account_Description] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Company] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[GL_Account] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Product] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Resp_Center] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Location] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Interco] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Customer] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Future1] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Future2] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Entered_DR] [decimal](18, 2) NULL,
	[Entered_CR] [decimal](18, 2) NULL,
	[Entered_Net] [decimal](18, 2) NULL,
	[Accounted_DR] [decimal](18, 2) NULL,
	[Accounted_CR] [decimal](18, 2) NULL,
	[Accounted_Net] [decimal](18, 2) NULL,
	[Header_Desc] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Line_Description] [nvarchar](250) COLLATE Latin1_General_CI_AI NULL,
	[Journal_Sequence] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Accounting_Date] [datetime] NULL,
	[Invoice_Num] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Invoice_Date] [datetime] NULL,
	[Trading_Partner_Name] [nvarchar](250) COLLATE Latin1_General_CI_AI NULL,
	[Trading_Partner_Number] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Trading_Partner_Site] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Account_type] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[H_Job_No] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[H_Master_BOL] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[H_House_BOL] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[H_Master_Booking_Number] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[H_Global_Customer] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[H_Customer_Ref] [nvarchar](250) COLLATE Latin1_General_CI_AI NULL,
	[H_CSR_Email] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[H_Voucher_Reference_Num] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Job_No] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Master_BOL] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[House_BOL] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Master_Booking_Number] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Global_Customer] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Customer_PO] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Customer_Ref] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[CSR_Email] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Job_Customer_Account] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Customer_Vendor_Group] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Charge_Code] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Sales_Invoice_Number] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Voucher_Reference_Num] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Tax_Classification] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Actual_Date] [datetime] NULL,
	[Created_by] [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Original_Invoice_Amount_Entered] [decimal](18, 2) NULL,
	[Original_Invoice_Amount_Accounting] [decimal](18, 2) NULL,
	[Exchange_Rate] [decimal](18, 2) NULL,
	[Open_Amount_Entered] [decimal](18, 2) NULL,
	[Open_Amount_Local] [decimal](18, 2) NULL,
	[Oracle_UserID] [bigint] NOT NULL,
	[IsActive] [bit] NULL,
	[CreateadDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
 CONSTRAINT [PK_Oracle_Receivables] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
