SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tela_ATL](
	[Cd_Tela] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tela] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[dt_criacao] [datetime] NULL,
 CONSTRAINT [PK_Tela_ATL] PRIMARY KEY CLUSTERED 
(
	[Cd_Tela] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
