SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Peso_Tarifa](
	[Cd_Peso_Trf] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Peso_Trf_In] [decimal](8, 2) NOT NULL,
	[Peso_Trf_Fn] [decimal](8, 2) NOT NULL,
PRIMARY KEY NONCLUSTERED 
(
	[Cd_Peso_Trf] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
