SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IBROKER_AG4A](
	[ID_ITDI] [bigint] NOT NULL,
	[01] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[02] [varchar](60) COLLATE Latin1_General_CI_AI NULL,
	[03] [varchar](80) COLLATE Latin1_General_CI_AI NULL,
	[04] [varchar](70) COLLATE Latin1_General_CI_AI NULL,
	[05] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[06] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[07] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[08] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[09] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_IBROKER_AG4A] PRIMARY KEY CLUSTERED 
(
	[ID_ITDI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
