SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Produto_Cliente_Erro](
	[cd_prod] [int] NOT NULL,
	[cd_Proc_Cliente] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[cd_Cliente] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Produto_Descr] [varchar](500) COLLATE Latin1_General_CI_AI NOT NULL,
	[NCM_Cliente] [varchar](8) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Produto_Cliente] PRIMARY KEY CLUSTERED 
(
	[cd_prod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Produto_Cliente] ON [dbo].[Produto_Cliente_Erro]
(
	[Produto_Descr] ASC,
	[cd_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Produto_Cliente_Erro]  WITH CHECK ADD  CONSTRAINT [FK_Produto_Cliente_Pessoa] FOREIGN KEY([cd_Cliente])
REFERENCES [dbo].[Pessoa] ([Cd_Pes])
GO
ALTER TABLE [dbo].[Produto_Cliente_Erro] CHECK CONSTRAINT [FK_Produto_Cliente_Pessoa]
GO
