SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Destinacao_Arg](
	[Modal] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Codigo] [varchar](4) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao_Destinacao] [varchar](100) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Tipo_Destinacao_Arg] PRIMARY KEY CLUSTERED 
(
	[Modal] ASC,
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
