SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Report_Imp_Completo](
	[BDP Ref.] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[File Open Date] [datetime] NULL,
	[Consol Ref.] [varchar](14) COLLATE Latin1_General_CI_AI NULL,
	[PO Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Customer PO] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Product ID] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Delivery Note] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Group Name] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Business Group] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[Business Name] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[Manufacturer] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Order Date] [datetime] NULL,
	[Order Type] [varchar](13) COLLATE Latin1_General_CI_AI NULL,
	[Order Received - Date] [datetime] NULL,
	[Register Date] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Incoterm] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Modal] [varchar](12) COLLATE Latin1_General_CI_AI NULL,
	[Type of cargo] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Shipper] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Shipper Address] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[Consignee] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Consignee Address] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[City of Consignee] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Company ID] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[CNPJ] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[Country of Destination] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Destination] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[NOMEAÇÃO DE TERMINAL] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Country of Origin] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Origin] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Country of Final Destination] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Data Aprov. Draft] [datetime] NULL,
	[Master] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[House] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[NCM] [varchar](8) COLLATE Latin1_General_CI_AI NULL,
	[Containers] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Container Type] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Container Qty] [int] NULL,
	[Product Description] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Product IDs by Shipment] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Carrier] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Vessel] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[TEUS Qtys] [int] NULL,
	[Netweight KG– Shipment] [float] NULL,
	[Certificado de Origem] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Invoice Currency] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Invoice Value] [float] NULL,
	[Invoice Date] [datetime] NULL,
	[Invoice Sent Date] [datetime] NULL,
	[Necessidade de LI?] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[LI Request - Date] [datetime] NULL,
	[LI Date] [datetime] NULL,
	[Import License] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[LI - Type] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Def.  LI - Date] [datetime] NULL,
	[Deferimento de LI Prévia] [datetime] NULL,
	[AUTORIZAÇÃO DE EMBARQUE] [datetime] NULL,
	[LI Expired - Date] [datetime] NULL,
	[Government Agency] [varchar](60) COLLATE Latin1_General_CI_AI NULL,
	[Import License - Value] [decimal](10, 2) NULL,
	[PDF - LI] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Booking Confirmation Date] [datetime] NULL,
	[Qty KG] [float] NULL,
	[Net Weight KG] [float] NULL,
	[Gross Weight KG] [float] NULL,
	[Gross Weight - NF] [float] NULL,
	[Gross Weight - Shipment - Value] [float] NULL,
	[Exchange Rates Value] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[SELECIONADA P/ INSP. MADEIRA] [datetime] NULL,
	[INSP. MADEIRA CONCLUÍDA] [datetime] NULL,
	[MADEIRA LIBERADA] [datetime] NULL,
	[Pre-Alert Sending - Date] [datetime] NULL,
	[Advanced Request Date] [datetime] NULL,
	[PRE DI Date] [datetime] NULL,
	[Docs Received Date] [datetime] NULL,
	[RECEB. DOCS. ORIGINAIS CHB] [datetime] NULL,
	[RECEB. DOCS. ORIGINAIS CSR] [datetime] NULL,
	[Data Abertura Pasta] [datetime] NULL,
	[PRESENÇA DE CARGA P/ DI] [datetime] NULL,
	[ENTREGA P/ PRÉ-DI] [datetime] NULL,
	[Courier - Value] [decimal](10, 2) NULL,
	[Freight Type] [varchar](7) COLLATE Latin1_General_CI_AI NULL,
	[Freight - USD] [decimal](18, 2) NULL,
	[Freight Currency] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Freight BL] [decimal](10, 2) NULL,
	[Freight Value] [float] NULL,
	[Green light - Date] [datetime] NULL,
	[ETD Date] [datetime] NULL,
	[ATD Date] [datetime] NULL,
	[ETA Date] [datetime] NULL,
	[ATA Date] [datetime] NULL,
	[Month of Arrival] [nvarchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Insurance Value] [decimal](10, 2) NULL,
	[THC Value] [decimal](10, 2) NULL,
	[TUP - Value] [decimal](10, 2) NULL,
	[Terminal] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Data Redest. Container] [datetime] NULL,
	[Data Entr. Terminal] [datetime] NULL,
	[Terminal Pier Name] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[Port Entry Date] [datetime] NULL,
	[Advancement Received Date] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Unloaded Date] [datetime] NULL,
	[Desconsolidation Value] [decimal](10, 2) NULL,
	[Effective Position Container - Date] [datetime] NULL,
	[Posicionamento - Value] [decimal](10, 2) NULL,
	[ISPS Value] [decimal](10, 2) NULL,
	[AFRMM Payment Date] [datetime] NULL,
	[AFRMM Value] [decimal](10, 2) NULL,
	[PDF - AFRMM] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[BENEFICIO AFRMM] [datetime] NULL,
	[BL Payment Date] [datetime] NULL,
	[BL Fee Value] [decimal](10, 2) NULL,
	[Deferimento de LI Pós] [datetime] NULL,
	[Customs Transmission Date] [datetime] NULL,
	[REGISTRO DE DI] [datetime] NULL,
	[Entry Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Siscomex Value] [decimal](10, 2) NULL,
	[FOB - USD] [decimal](18, 2) NULL,
	[FOB Value] [float] NULL,
	[CFR - USD] [decimal](19, 2) NULL,
	[CIF Value] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[% II] [float] NULL,
	[Import Duty Value] [decimal](10, 2) NULL,
	[Import Duties Value by Shipment] [decimal](10, 2) NULL,
	[% IPI] [float] NULL,
	[IPI - Value] [decimal](10, 2) NULL,
	[IPI Value by Shipment] [decimal](10, 2) NULL,
	[% PIS] [float] NULL,
	[PIS - Value] [decimal](10, 2) NULL,
	[PIS Value by Shipment] [decimal](10, 2) NULL,
	[% Cofins] [float] NULL,
	[Cofins - Value] [decimal](10, 2) NULL,
	[Cofins Value by Shipment] [decimal](10, 2) NULL,
	[AntiDumping Value] [decimal](10, 2) NULL,
	[AntiDumping Value by Shipment] [decimal](10, 2) NULL,
	[Channel] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Customs Clearance Date] [datetime] NULL,
	[PDF - DI] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - CI] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[TP - Despesas Acessorias - Value] [decimal](10, 2) NULL,
	[TP - Despesas Calc ICMS - Value] [decimal](10, 2) NULL,
	[% ICMS] [float] NULL,
	[ICMS - Value] [decimal](10, 2) NULL,
	[ICMS Base] [float] NULL,
	[ICMS Payment Date] [datetime] NULL,
	[PDF - ICMS] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[ICMS Exonaration Date] [datetime] NULL,
	[Danfe Request - Date] [datetime] NULL,
	[Danfe Receipt - Date - BR only] [datetime] NULL,
	[RECEBIMENTO DE DANFE] [datetime] NULL,
	[REBEB. DANFE CLIENTE] [datetime] NULL,
	[NFE Draft - Date] [datetime] NULL,
	[NF Date] [datetime] NULL,
	[NF Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[CFOP] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[NF Serie] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[NF Issue - Value] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[PDF - NF] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Transport. Doc Delivery Date] [datetime] NULL,
	[DOCS DISPONÍVEIS P/ TRANSP.] [datetime] NULL,
	[DOCS RETIRADOS PELA TRANSP.] [datetime] NULL,
	[Docs to BDP Billing Date] [datetime] NULL,
	[Inland Freight Value] [decimal](10, 2) NULL,
	[Pesagem - Value] [decimal](10, 2) NULL,
	[Warehousing Value] [decimal](10, 2) NULL,
	[Data Pgto Armazenagem] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[NF BDP Date] [datetime] NULL,
	[Invoice approval by customer - Date] [datetime] NULL,
	[Invoice] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Customs Brokerage Value] [float] NULL,
	[PDF - PC] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Last Update] [datetime] NULL,
	[Process Status] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Saldo Processo Valor] [decimal](10, 2) NULL,
	[Notes] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[Last Historic] [varchar](700) COLLATE Latin1_General_CI_AI NULL,
	[Complete Historic] [varchar](4000) COLLATE Latin1_General_CI_AI NULL,
	[AUDITORIA DATA MANEGMENT] [datetime] NULL,
	[PDF - INVOICE] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - CONHECIMENTO DE EMBARQUE] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - COA] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - PACKING LIST] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[ENVIO DE COA PARA TRANSPORTADORA] [datetime] NULL,
	[ENVIO DE DOCS PARA CAMBIO] [datetime] NULL,
	[DOCUMENTOS OK PARA REGISTRO] [datetime] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
