SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Rec_Cta_Cte](
	[Num_Lcto_Mov] [varchar](12) COLLATE Latin1_General_CI_AI NOT NULL,
	[Num_Lcto_Rec] [varchar](12) COLLATE Latin1_General_CI_AI NOT NULL,
	[Perc_Rec] [decimal](6, 2) NULL,
PRIMARY KEY NONCLUSTERED 
(
	[Num_Lcto_Mov] ASC,
	[Num_Lcto_Rec] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Rec_Cta_Cte]  WITH CHECK ADD FOREIGN KEY([Num_Lcto_Mov])
REFERENCES [dbo].[Mvto_Cta_Cte] ([Num_Lcto_Mov])
GO
