SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmpSLI](
	[num_proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[cd_prod] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[SLI] [varchar](16) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
