SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Alerta_Redestinacao](
	[ID_Tp_Alerta] [bigint] IDENTITY(1,1) NOT NULL,
	[Stored] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Regra] [varchar](max) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Alerta] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Alerta_Redestinacao] PRIMARY KEY CLUSTERED 
(
	[ID_Tp_Alerta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
