SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Moeda](
	[Cd_Tp_Moeda] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Moeda] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cod_Nac_Moeda] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Cod_Int_Moeda] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Moeda_Ofc] [char](5) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Loc_Ofc] [varchar](5) COLLATE Latin1_General_CI_AI NULL,
	[ativo] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Cd_Tp_Moeda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nome_Tp_Moeda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tipo_Moeda]  WITH CHECK ADD  CONSTRAINT [FK_Tipo_Moeda_Aux_Moeda] FOREIGN KEY([Cd_Moeda_Ofc])
REFERENCES [dbo].[Aux_Moeda] ([Cd_Moeda_Ofc])
GO
ALTER TABLE [dbo].[Tipo_Moeda] CHECK CONSTRAINT [FK_Tipo_Moeda_Aux_Moeda]
GO
