SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Item_Fat_Arg](
	[FatCod] [varchar](17) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[DC] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Tipo] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Credor_Devedor] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[NUM_LCTO] [varchar](12) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Item_Fat_Arg] PRIMARY KEY CLUSTERED 
(
	[FatCod] ASC,
	[Cd_Tp_tx] ASC,
	[DC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
