SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Status_LI](
	[ID_Status_LI] [int] NOT NULL,
	[Status_LI_Descricao] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Status_LI] PRIMARY KEY CLUSTERED 
(
	[ID_Status_LI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
