SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Aux_Tipo_Container](
	[Cd_CC_Ofc] [char](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Cont_Ofc] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
