SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Historico_Exp_Mar](
	[Num_Proc_HEM] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Hist_EM] [varchar](2000) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_Proc_HEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Historico_Exp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Historico__Num_P__3F6663D5] FOREIGN KEY([Num_Proc_HEM])
REFERENCES [dbo].[House_Exp_Mar] ([Num_Proc_HEM])
GO
ALTER TABLE [dbo].[Historico_Exp_Mar] CHECK CONSTRAINT [FK__Historico__Num_P__3F6663D5]
GO
