SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RH_Ponto](
	[ID] [bigint] NOT NULL,
	[Nome_Funcionario] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Centro_Custo] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Pis] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Responsavel] [varchar](6) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_RH_Ponto] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
