SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[E_MIX_XML](
	[ID] [bigint] NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[id_consulta_tipo] [int] NULL,
	[Dt_Envio] [datetime] NULL,
	[Envio_Erro] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[XML_DOC] [xml] NULL,
	[Nome_Arquivo] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[XML_DOC2] [xml] NULL,
	[Dt_Retorno] [datetime] NULL,
	[Retorno_Erro] [varchar](400) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20230613-144601_2] ON [dbo].[E_MIX_XML]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20230613-144601_3] ON [dbo].[E_MIX_XML]
(
	[ID] ASC,
	[Dt_Envio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
