SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GTNEXUS_XML](
	[ID_Smart] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_GTNEXUS] [bigint] NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Type] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[XML_DOC] [nvarchar](max) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Arquivo] [varchar](500) COLLATE Latin1_General_CI_AI NOT NULL,
	[Dt_Ins] [datetime] NOT NULL,
	[Dt_Envio] [datetime] NULL,
	[XML_DOC2] [xml] NULL,
 CONSTRAINT [PK_GTNEXUS_XML] PRIMARY KEY CLUSTERED 
(
	[ID_Smart] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
