SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Temp_Seguro](
	[Num_proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[valor] [float] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
