SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Aux_Moeda](
	[Cd_Moeda_Ofc] [char](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Moeda] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Aux_Moeda] PRIMARY KEY CLUSTERED 
(
	[Cd_Moeda_Ofc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
