SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Item_Nota_Fiscal](
	[Num_NF] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Item_NF] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Vlr_Item_NF] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_NF] ASC,
	[Num_Proc] ASC,
	[Cd_Tp_Item_NF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [XIF352Item_Nota_Fiscal] ON [dbo].[Item_Nota_Fiscal]
(
	[Cd_Tp_Item_NF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Item_Nota_Fiscal]  WITH CHECK ADD FOREIGN KEY([Cd_Tp_Item_NF])
REFERENCES [dbo].[Tipo_Item_Nota_Fiscal] ([Cd_Tp_Item_NF])
GO
ALTER TABLE [dbo].[Item_Nota_Fiscal]  WITH CHECK ADD FOREIGN KEY([Num_NF])
REFERENCES [dbo].[Nota_Fiscal] ([Num_NF])
GO
