SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Rel_221_PEDIDO](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[NCM PO] [varchar](8) COLLATE Latin1_General_CI_AI NULL,
	[FOB Value] [float] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
