SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NCM_SIM_ARG_SUBITEM](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Item] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[SubItem] [varchar](4) COLLATE Latin1_General_CI_AI NOT NULL,
	[Quantidade] [decimal](18, 2) NULL,
	[Preco_Unit] [float] NULL,
	[FOB] [float] NULL,
	[GMID] [varchar](8) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_NCM_SIM_ARG_SUBITEM] PRIMARY KEY CLUSTERED 
(
	[Num_Proc] ASC,
	[Item] ASC,
	[SubItem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
