SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Rel_SCHCASS_INVOICE_TRATADO](
	[NUM_PROC] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[FATCOD] [varchar](17) COLLATE Latin1_General_CI_AI NOT NULL,
	[FATDTEMISSAO] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[FATDTVENC] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CURR_CONVERT_1] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CURR_EXCHANGE_1] [float] NULL,
	[CURR_CONVERT_2] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CURR_EXCHANGE_2] [float] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
