SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Tax_AX](
	[Cd_Tax_AX] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao_Tax_AX] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[Porcentagem] [float] NULL,
	[ISS] [decimal](10, 2) NULL,
	[IRRF] [decimal](10, 2) NULL,
 CONSTRAINT [PK_Tipo_Tax_AX] PRIMARY KEY CLUSTERED 
(
	[Cd_Tax_AX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
