SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RPS_Servicos](
	[CdsId] [int] NOT NULL,
	[CdsDescricao] [varchar](70) COLLATE Latin1_General_CI_AI NOT NULL,
	[CdsAliquota] [decimal](6, 2) NOT NULL,
	[CdsFilial] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_RPS_Servicos] PRIMARY KEY CLUSTERED 
(
	[CdsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[RPS_Servicos] ADD  CONSTRAINT [DF_RPS_Servicos_CdsFilial]  DEFAULT ('A') FOR [CdsFilial]
GO
