SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Proposta](
	[PROCOD] [varchar](12) COLLATE Latin1_General_CI_AI NOT NULL,
	[CD_PES] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[CD_TP_COM] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[PROFAX] [varchar](14) COLLATE Latin1_General_CI_AI NULL,
	[PRODATA] [datetime] NOT NULL,
	[STACOD] [int] NOT NULL,
	[PROCABEC] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[PROCONSULTOR] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[PROVALIDADE] [datetime] NOT NULL,
	[PROOBS] [varchar](5000) COLLATE Latin1_General_CI_AI NULL,
	[PROROD] [varchar](5000) COLLATE Latin1_General_CI_AI NULL,
	[PRODTSOL] [datetime] NOT NULL,
	[PROPRODUTO] [varchar](500) COLLATE Latin1_General_CI_AI NOT NULL,
	[PROPRINT] [bit] NOT NULL,
 CONSTRAINT [PK_Proposta] PRIMARY KEY CLUSTERED 
(
	[PROCOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Proposta] ADD  CONSTRAINT [DF_Proposta_PROPRODUTO]  DEFAULT ('') FOR [PROPRODUTO]
GO
ALTER TABLE [dbo].[Proposta] ADD  CONSTRAINT [DF_Proposta_PROPRINT]  DEFAULT (0) FOR [PROPRINT]
GO
ALTER TABLE [dbo].[Proposta]  WITH NOCHECK ADD  CONSTRAINT [FK_Proposta_Comunicacao] FOREIGN KEY([CD_PES], [CD_TP_COM])
REFERENCES [dbo].[Comunicacao] ([Cd_Pes], [Cd_Tp_Com])
GO
ALTER TABLE [dbo].[Proposta] CHECK CONSTRAINT [FK_Proposta_Comunicacao]
GO
ALTER TABLE [dbo].[Proposta]  WITH NOCHECK ADD  CONSTRAINT [FK_Proposta_Status] FOREIGN KEY([STACOD])
REFERENCES [dbo].[Status] ([STACOD])
GO
ALTER TABLE [dbo].[Proposta] CHECK CONSTRAINT [FK_Proposta_Status]
GO
ALTER TABLE [dbo].[Proposta]  WITH NOCHECK ADD  CONSTRAINT [FK_Proposta_Usuario] FOREIGN KEY([PROCONSULTOR])
REFERENCES [dbo].[Usuario] ([Cd_Usuario])
GO
ALTER TABLE [dbo].[Proposta] CHECK CONSTRAINT [FK_Proposta_Usuario]
GO
