SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Log_Sol_Pgto_Cta_Cte_Autorizacao](
	[ID] [bigint] NOT NULL,
	[Status_Aprovacao] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Aprovacao] [datetime] NULL,
	[Cd_Gerente] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Log_Sol_Pgto_Cta_Cte_Autorizacao] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
