SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Eve_Lido](
	[Arquivo_Lid] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Data_Lid] [datetime] NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
