SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Dolar_Ref](
	[Dt_DR] [varchar](7) COLLATE Latin1_General_CI_AI NOT NULL,
	[Espec_DR] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[Par_DR] [decimal](10, 6) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Dt_DR] ASC,
	[Espec_DR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
