SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Evento_House](
	[TpeId] [int] NOT NULL,
	[Num_Proc_H] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[EvhData] [datetime] NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
