SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Relacao](
	[Cd_Pes_A] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Pes_B] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Rel] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Obs_Rel] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
PRIMARY KEY CLUSTERED 
(
	[Cd_Pes_A] ASC,
	[Cd_Pes_B] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Relacao]  WITH NOCHECK ADD  CONSTRAINT [FK__Relacao__Cd_Pes___7167D3BD] FOREIGN KEY([Cd_Pes_A])
REFERENCES [dbo].[Pessoa] ([Cd_Pes])
GO
ALTER TABLE [dbo].[Relacao] CHECK CONSTRAINT [FK__Relacao__Cd_Pes___7167D3BD]
GO
ALTER TABLE [dbo].[Relacao]  WITH NOCHECK ADD  CONSTRAINT [FK__Relacao__Cd_Pes___725BF7F6] FOREIGN KEY([Cd_Pes_B])
REFERENCES [dbo].[Pessoa] ([Cd_Pes])
GO
ALTER TABLE [dbo].[Relacao] CHECK CONSTRAINT [FK__Relacao__Cd_Pes___725BF7F6]
GO
ALTER TABLE [dbo].[Relacao]  WITH CHECK ADD FOREIGN KEY([Cd_Tp_Rel])
REFERENCES [dbo].[Tipo_Relacao] ([Cd_Tp_Rel])
GO
