SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Div_Lucro](
	[Nivel_DL] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Parceiro] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Perc_DL] [decimal](6, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Nivel_DL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Div_Lucro]  WITH NOCHECK ADD  CONSTRAINT [FK__Div_Lucro__Cd_Pa__5006DFF2] FOREIGN KEY([Cd_Parceiro])
REFERENCES [dbo].[Pessoa] ([Cd_Pes])
GO
ALTER TABLE [dbo].[Div_Lucro] CHECK CONSTRAINT [FK__Div_Lucro__Cd_Pa__5006DFF2]
GO
