SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Pais_Itau](
	[Cd_Pais_Itau] [varchar](4) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Pais] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Pais] [varchar](2) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
