SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Estoque_NF](
	[Nr_NF] [varchar](12) COLLATE Latin1_General_CI_AI NOT NULL,
	[Site] [char](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[Status] [int] NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
