SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_relatorio_Custo_Processo_Demais_colunas](
	[Modal] [varchar](12) COLLATE Latin1_General_CI_AI NOT NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Numero da Ordem] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Incoterm] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Consignee] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
	[CNPJ] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[Origin] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Country of Origin] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Destination] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Carrier] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Vessel] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[House] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[ETD] [datetime] NULL,
	[ATD] [datetime] NULL,
	[ETA] [datetime] NULL,
	[ATA] [datetime] NULL,
	[Numero da DI] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Exchange Rates Value] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Customs Transmission Date] [datetime] NULL,
	[Data Desembaraço] [datetime] NULL,
	[Month of Clearance] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Canal] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[NF Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Transport. Doc Delivery Date] [datetime] NULL,
	[Containers] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[Container Qty] [decimal](9, 2) NULL,
	[Net Weight KG] [float] NULL,
	[Gross Weight] [float] NULL,
	[Despesas Portuárias] [float] NULL,
	[Arqueação] [float] NULL,
	[TUP] [float] NULL,
	[ATRACACAO] [float] NULL,
	[Liberação de BL] [float] NULL,
	[Emissão de BL] [float] NULL,
	[Desconsolidação] [float] NULL,
	[Capatazias / THC] [float] NULL,
	[Carta de Correção] [float] NULL,
	[Correção Siscarga] [float] NULL,
	[TAXA SISCARGA] [float] NULL,
	[Demurrage] [float] NULL,
	[Taxa de retirada de Doc] [float] NULL,
	[Taxa do Agente] [float] NULL,
	[Damage Protection charge] [float] NULL,
	[Exame Laboratorial] [float] NULL,
	[Taxa de Lacre] [float] NULL,
	[Armazenagem] [float] NULL,
	[Handling] [float] NULL,
	[Manuseio de Carga] [float] NULL,
	[Inspeção de Madeira] [float] NULL,
	[Desova] [float] NULL,
	[Estadia] [float] NULL,
	[Posicionamento de CNTR] [float] NULL,
	[Remoção CNTR] [float] NULL,
	[Pesagem CNTR] [float] NULL,
	[Equip. Surcharge] [float] NULL,
	[VISTORIA DE CNTR] [float] NULL,
	[DESPESA CONTAINER] [float] NULL,
	[Devolução de CNTR] [float] NULL,
	[Drop Off] [float] NULL,
	[Lavagem CNTR] [float] NULL,
	[Reparo de Container] [float] NULL,
	[Seguro] [float] NULL,
	[Frete Interno] [float] NULL,
	[Serviços de Despacho] [float] NULL,
	[Cartório] [float] NULL,
	[Correio] [float] NULL,
	[Courier] [float] NULL,
	[Acompanhamento Operacional] [float] NULL,
	[Anuência de LI] [float] NULL,
	[LI] [float] NULL,
	[Min. Exercito LI] [float] NULL,
	[AFRMM] [float] NULL,
	[Taxas Siscomex] [float] NULL,
	[Imposto de Importação] [float] NULL,
	[IPI] [float] NULL,
	[PIS] [float] NULL,
	[COFINS] [float] NULL,
	[ICMS] [float] NULL,
	[AntiDumping Value] [float] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
