SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Prd_Hou_Exp_Aer](
	[Num_Proc_HEA] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Prod_HEA] [varchar](2000) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_Proc_HEA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Prd_Hou_Exp_Aer]  WITH NOCHECK ADD  CONSTRAINT [FK__Prd_Hou_E__Num_P__442B18F2] FOREIGN KEY([Num_Proc_HEA])
REFERENCES [dbo].[House_Exp_Aer] ([Num_Proc_HEA])
GO
ALTER TABLE [dbo].[Prd_Hou_Exp_Aer] CHECK CONSTRAINT [FK__Prd_Hou_E__Num_P__442B18F2]
GO
