SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATL_Capa_Valores](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[FOB_USD] [decimal](18, 2) NULL,
	[CIF_USD] [decimal](18, 2) NULL,
	[FRETE_USD] [decimal](18, 2) NULL,
	[FOB_REAIS] [decimal](18, 2) NULL,
	[ACRESCIMOS_REAIS] [decimal](18, 2) NULL,
	[SEGURO_REAIS] [decimal](18, 2) NULL,
	[FRETE_REAIS] [decimal](18, 2) NULL,
	[Cd_Tp_Moeda_Frete] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Tp_Moeda_CFR] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CIF_REAIS] [decimal](18, 2) NULL,
 CONSTRAINT [PK_ATL_Capa_Valores] PRIMARY KEY CLUSTERED 
(
	[Num_Proc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
