SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Tipo_Doc_RF](
	[Cd_Tipo_Doc_RF] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao_Tp_Doc] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Ativo] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[Debito] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[Credito] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Doc_RF] PRIMARY KEY CLUSTERED 
(
	[Cd_Tipo_Doc_RF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
