SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Terminal](
	[Cd_Terminal] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Terminal] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Repart] [char](7) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Term_Ofc] [varchar](7) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
SET ANSI_PADDING OFF
ALTER TABLE [dbo].[Terminal] ADD [Email] [varchar](max) COLLATE Latin1_General_CI_AI NULL
ALTER TABLE [dbo].[Terminal] ADD [Email_CC] [varchar](max) COLLATE Latin1_General_CI_AI NULL
ALTER TABLE [dbo].[Terminal] ADD [Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NULL
ALTER TABLE [dbo].[Terminal] ADD [Dt_Ins] [datetime] NULL
ALTER TABLE [dbo].[Terminal] ADD [Ativo] [bit] NULL
PRIMARY KEY CLUSTERED 
(
	[Cd_Terminal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
UNIQUE NONCLUSTERED 
(
	[Nome_Terminal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
