SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Prd_Mas_Exp_Aer](
	[Num_Proc_MEA] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Prod_MEA] [varchar](2000) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_Proc_MEA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Prd_Mas_Exp_Aer]  WITH NOCHECK ADD  CONSTRAINT [FK__Prd_Mas_E__Num_P__1B29035F] FOREIGN KEY([Num_Proc_MEA])
REFERENCES [dbo].[Master_Exp_Aer] ([Num_Proc_MEA])
GO
ALTER TABLE [dbo].[Prd_Mas_Exp_Aer] CHECK CONSTRAINT [FK__Prd_Mas_E__Num_P__1B29035F]
GO
