SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Type_Expense](
	[ID_TypeExpense] [int] IDENTITY(1,1) NOT NULL,
	[Type_Expense] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[Status] [bit] NULL,
 CONSTRAINT [PK_Type_Expense] PRIMARY KEY CLUSTERED 
(
	[ID_TypeExpense] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
