SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Operador_Portuario](
	[ID_OP] [int] NOT NULL,
	[Descricao_OP] [varchar](100) COLLATE Latin1_General_CI_AI NOT NULL,
	[Ativo] [bit] NOT NULL,
	[Dt_Criacao] [datetime] NOT NULL,
	[Cd_Usuario] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Tipo_Operador_Portuario_1] PRIMARY KEY CLUSTERED 
(
	[ID_OP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Tipo_Operador_Portuario] ON [dbo].[Tipo_Operador_Portuario]
(
	[Descricao_OP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE FULLTEXT INDEX ON [dbo].[Tipo_Operador_Portuario]
KEY INDEX [PK_Tipo_Operador_Portuario_1]ON ([num_proc], FILEGROUP [ftfg_num_proc])
WITH (CHANGE_TRACKING = AUTO, STOPLIST = SYSTEM)


GO
ALTER FULLTEXT INDEX ON [dbo].[Tipo_Operador_Portuario] DISABLE
GO
