SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NCM_Custo](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Item] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[TXCode] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[PORC] [float] NULL,
	[PGC] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
	[TX_Valor] [float] NULL,
 CONSTRAINT [PK_NCM_Custo] PRIMARY KEY CLUSTERED 
(
	[Num_Proc] ASC,
	[Item] ASC,
	[TXCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
