SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Relacao_Cta_Ctb](
	[Cd_Cta_Ctb] [varchar](13) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Cta_Ctb_Ass] [varchar](13) COLLATE Latin1_General_CI_AI NOT NULL,
	[Obs_Rel_Cta_Ctb] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
PRIMARY KEY NONCLUSTERED 
(
	[Cd_Cta_Ctb] ASC,
	[Cd_Cta_Ctb_Ass] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Relacao_Cta_Ctb]  WITH CHECK ADD FOREIGN KEY([Cd_Cta_Ctb_Ass])
REFERENCES [dbo].[Cta_Ctb] ([Cd_Cta_Ctb])
GO
ALTER TABLE [dbo].[Relacao_Cta_Ctb]  WITH CHECK ADD FOREIGN KEY([Cd_Cta_Ctb])
REFERENCES [dbo].[Cta_Ctb] ([Cd_Cta_Ctb])
GO
