SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Mens_Dest](
	[MnsID] [int] NOT NULL,
	[Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NOT NULL,
	[MndSis] [bit] NOT NULL,
	[MndMail] [bit] NOT NULL,
 CONSTRAINT [PK_Mens_Dest] PRIMARY KEY CLUSTERED 
(
	[MnsID] ASC,
	[Cd_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Mens_Dest] ADD  CONSTRAINT [DF_Mens_Dest_MndSis]  DEFAULT (0) FOR [MndSis]
GO
ALTER TABLE [dbo].[Mens_Dest] ADD  CONSTRAINT [DF_Mens_Dest_MndMail]  DEFAULT (0) FOR [MndMail]
GO
ALTER TABLE [dbo].[Mens_Dest]  WITH CHECK ADD  CONSTRAINT [FK_Mens_Dest_Mensagem] FOREIGN KEY([MnsID])
REFERENCES [dbo].[Mensagem] ([MnsID])
GO
ALTER TABLE [dbo].[Mens_Dest] CHECK CONSTRAINT [FK_Mens_Dest_Mensagem]
GO
