SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Taxa_Contabilidade_Impostos](
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Tx] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Cta_Ctb_Red] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Data] [datetime] NULL,
 CONSTRAINT [PK_Tipo_Taxa_Contabilidade_Impostos] PRIMARY KEY CLUSTERED 
(
	[Cd_Tp_Tx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
