SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Doc_Tarefas](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_Task] [int] NOT NULL,
	[ID_DC] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Status] [bit] NOT NULL,
	[Dt_Insert] [datetime] NOT NULL,
	[Modal] [varchar](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[ID_PD] [int] NOT NULL,
 CONSTRAINT [PK_Doc_Tarefas] PRIMARY KEY CLUSTERED 
(
	[ID_Task] ASC,
	[ID_DC] ASC,
	[Modal] ASC,
	[ID_PD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
