SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Exchange_Alerta](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_TP_Alerta] [bigint] NOT NULL,
	[Dt_Ins] [datetime] NULL,
	[Dt_Envio] [datetime] NULL,
	[Campo] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[Dados_Alterados] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Exchange_Alerta] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
