SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IBROKER_DOC_V2](
	[ID] [bigint] NOT NULL,
	[ID_DOC] [int] NOT NULL,
	[GNC] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Documento] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Status] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_IBROKER_DOC_V2] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[ID_DOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
