SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHB_Cliente_Localidade](
	[cd_pes_grupo] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Localidade] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_CHB_Cliente_Localidade] PRIMARY KEY CLUSTERED 
(
	[cd_pes_grupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
