SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IntFMC_Plano_Contas](
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Pes] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Conta_Debito] [varchar](7) COLLATE Latin1_General_CI_AI NULL,
	[Conta_Credito] [varchar](7) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_IntFMC_Plano_Contas] PRIMARY KEY CLUSTERED 
(
	[Cd_Tp_Tx] ASC,
	[Cd_Pes] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
