SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Rel_SCHCASS_JOB_ITINERARY_ID](
	[NUM_PROC] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[ITINERARY_ID] [varchar](20) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
