SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATL_Master_Per](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[Master] [varchar](14) COLLATE Latin1_General_CI_AI NULL,
	[Per_Valor] [decimal](10, 4) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
