SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Historico_Imp_Mar](
	[Num_Proc_HIM] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Hist_IM] [varchar](2000) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_Proc_HIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Historico_Imp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Historico__Num_P__414EAC47] FOREIGN KEY([Num_Proc_HIM])
REFERENCES [dbo].[House_Imp_Mar] ([Num_Proc_HIM])
GO
ALTER TABLE [dbo].[Historico_Imp_Mar] CHECK CONSTRAINT [FK__Historico__Num_P__414EAC47]
GO
