SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TIPO_TAXA_CASS_SCH](
	[CD_TP_TX_SCH] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CD_TP_TX] [varchar](3) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
