SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_RetificacaoDI](
	[ID_TP_RET] [bigint] IDENTITY(1,1) NOT NULL,
	[NOME_TP_RET] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[Ativo] [bit] NULL,
	[Cd_Usuario] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[dt_ins] [datetime] NULL,
 CONSTRAINT [PK_Tipo_RetificacaoDI] PRIMARY KEY CLUSTERED 
(
	[ID_TP_RET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
