SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Cont_Verificacao](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Data] [datetime] NULL,
	[Conta_Debito] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[Conta_Credito] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[valor] [float] NULL,
	[Historico] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Cont_Verificacao] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
