SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Log_WebService](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Interface] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Mensagem] [varchar](5000) COLLATE Latin1_General_CI_AI NULL,
	[Ref_BDP] [varchar](160) COLLATE Latin1_General_CI_AI NULL,
	[Ref_Cliente] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Referencia] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Log_Dt] [datetime] NULL,
	[Dt_Envio] [datetime] NULL,
	[Email] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Log_WebService] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
