SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Nota_Fiscal](
	[Num_NF] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Dt_Emis_NF] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Pes] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Dt_Vcto_NF] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Vlr_Tot_NF] [decimal](10, 2) NOT NULL,
	[Obs_NF] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_NF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [XIF361Nota_Fiscal] ON [dbo].[Nota_Fiscal]
(
	[Cd_Pes] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Nota_Fiscal]  WITH NOCHECK ADD  CONSTRAINT [FK__Nota_Fisc__Cd_Pe__5D60DB10] FOREIGN KEY([Cd_Pes])
REFERENCES [dbo].[Pessoa] ([Cd_Pes])
GO
ALTER TABLE [dbo].[Nota_Fiscal] CHECK CONSTRAINT [FK__Nota_Fisc__Cd_Pe__5D60DB10]
GO
