SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Regras_Contabeis](
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[DC] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Modal] [char](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[Conta_Credito] [nchar](13) COLLATE Latin1_General_CI_AI NULL,
	[Conta_Debito] [nchar](13) COLLATE Latin1_General_CI_AI NULL,
	[Tipo] [char](1) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Regras_Contabeis] PRIMARY KEY CLUSTERED 
(
	[Cd_Tp_Tx] ASC,
	[DC] ASC,
	[Modal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
