SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Adm_Pricing](
	[Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Adm_Pricing] PRIMARY KEY CLUSTERED 
(
	[Cd_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Adm_Pricing]  WITH CHECK ADD  CONSTRAINT [FK_Adm_Pricing_Usuario] FOREIGN KEY([Cd_Usuario])
REFERENCES [dbo].[Usuario] ([Cd_Usuario])
GO
ALTER TABLE [dbo].[Adm_Pricing] CHECK CONSTRAINT [FK_Adm_Pricing_Usuario]
GO
