SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Regiao](
	[Cd_Regiao] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Regiao] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[LocICS2] [bit] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[Cd_Regiao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Regiao] ADD  DEFAULT ((0)) FOR [LocICS2]
GO
