SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Nota_Fiscal_Lote](
	[Num_NF] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Fornecedor] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Lote] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Pedido] [int] NULL,
 CONSTRAINT [PK_Nota_Fiscal_Lote] PRIMARY KEY CLUSTERED 
(
	[Num_NF] ASC,
	[Cd_Fornecedor] ASC,
	[Lote] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
