SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductCosts_Temp](
	[Cd_Produto] [int] NOT NULL,
	[ALIQ_II] [float] NULL,
	[ALIQ_IPI] [float] NULL,
	[VL_ALIQ_PIS] [float] NULL,
	[VL_ALIQ_COFINS] [float] NULL,
	[ALIQ_ICMS] [float] NULL,
	[Emissao] [datetime] NULL,
	[ID_NF] [int] NULL,
 CONSTRAINT [PK_ProductCosts_Temp] PRIMARY KEY CLUSTERED 
(
	[Cd_Produto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
