SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Schneider_TCT](
	[ServiceCodeIndicator] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[LLP] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Input Date Time] [datetime] NULL,
	[Job Number] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Transport Mode] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[MAWB] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Housebill / Shipment] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Vessel name] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Origin Station] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[Origin Country Code] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[Origin Region] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Shipper Name] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
	[Destination Station] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[Destination Country Code] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[Destination Region] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Consignee Name] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
	[Transport Lane ID] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Lane] [varchar](12) COLLATE Latin1_General_CI_AI NULL,
	[LCL/FCL] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Loading Type] [varchar](7) COLLATE Latin1_General_CI_AI NOT NULL,
	[Container Number] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[Container Size] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Container Type] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[TEU] [float] NULL,
	[No of Packages] [float] NULL,
	[Gross Weight] [float] NULL,
	[Chargeable Weight] [float] NULL,
	[Volume] [float] NULL,
	[Scope] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[Shipment Status] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Booking date] [datetime] NULL,
	[Cargo ready date] [datetime] NULL,
	[Pre-alert date] [datetime] NULL,
	[Shipment Pickup] [datetime] NULL,
	[Received at Origin] [datetime] NULL,
	[MB ETD 1] [datetime] NULL,
	[MB ETD 2] [datetime] NULL,
	[MB ETD 3] [datetime] NULL,
	[MB ETA 1] [datetime] NULL,
	[MB ETA 2] [datetime] NULL,
	[MB ETA 3] [datetime] NULL,
	[Actual Time Departure] [datetime] NULL,
	[Actual Time Arrival] [datetime] NULL,
	[CALC ARRIVAL DATE] [int] NOT NULL,
	[QTY DAYS TO DROP] [int] NOT NULL,
	[Broker Notified] [datetime] NULL,
	[Shipment Hand-Over To the broker] [datetime] NULL,
	[Estimated Customs Clearance] [datetime] NULL,
	[Actual Customs Completion] [datetime] NULL,
	[Estimated Delivery Date] [datetime] NULL,
	[Actual Delivery Date] [datetime] NULL,
	[Estimated Completion Date] [datetime] NULL,
	[Actual Completion Date] [datetime] NULL,
	[TT1 Benchmark] [int] NOT NULL,
	[TT2 Benchmark] [int] NOT NULL,
	[TT3 Benchmark] [int] NOT NULL,
	[TT4 Benchmark] [int] NOT NULL,
	[Total TT Benchmark] [int] NOT NULL,
	[TT1 Planned/Actual] [int] NOT NULL,
	[TT2 Planned/Actual] [int] NOT NULL,
	[TT3 Planned/Actual] [int] NOT NULL,
	[TT4 Planned/Actual] [int] NOT NULL,
	[Total TT Planned/Actual] [int] NOT NULL,
	[TT1 status] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[TT2 status] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[TT3 status] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[TT4 status] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[Total Status] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[Delay Responsibility] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Delay Code] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[Reason of Delay] [varchar](300) COLLATE Latin1_General_CI_AI NULL,
	[CO2 emission] [varchar](1) COLLATE Latin1_General_CI_AI NULL,
	[Track and trace URL address] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[Shipper Address] [varchar](8000) COLLATE Latin1_General_CI_AI NULL,
	[Shipper City] [varchar](8000) COLLATE Latin1_General_CI_AI NULL,
	[Shipper Postcode] [varchar](8000) COLLATE Latin1_General_CI_AI NULL,
	[Consignee Address] [varchar](8000) COLLATE Latin1_General_CI_AI NULL,
	[Consignee City] [varchar](8000) COLLATE Latin1_General_CI_AI NULL,
	[Consignee Postcode] [varchar](8000) COLLATE Latin1_General_CI_AI NULL,
	[Shipper Reference BIT_Invoice] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Itinerary ID] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Plant of origin ID] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Plant of origin] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Plant of Destination ID] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Plant of Destination] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Incoterm] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Source Sytem] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[Flight 1] [varchar](13) COLLATE Latin1_General_CI_AI NULL,
	[Flight 2] [varchar](13) COLLATE Latin1_General_CI_AI NULL,
	[Voyage Number] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Seal Number] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Master Carrier] [varchar](30) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
