SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Navio_LLP](
	[Id_Navio] [int] NOT NULL,
	[Nome_Navio] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Nacionalidade] [char](2) COLLATE Latin1_General_CI_AI NULL,
	[LLoyd] [varchar](8) COLLATE Latin1_General_CI_AI NULL,
	[cd_pais] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[cd_armador] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Navio_LLP] PRIMARY KEY CLUSTERED 
(
	[Id_Navio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Navio_LLP]  WITH CHECK ADD  CONSTRAINT [FK_Navio_LLP_Navio_LLP] FOREIGN KEY([Id_Navio])
REFERENCES [dbo].[Navio_LLP] ([Id_Navio])
GO
ALTER TABLE [dbo].[Navio_LLP] CHECK CONSTRAINT [FK_Navio_LLP_Navio_LLP]
GO
