SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Transf_Price_Dow_Exp_2015](
	[ID] [bigint] NOT NULL,
	[REMETENTE_CNPJ_CPF] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[NUMERO_NOTA_FISCAL] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[SERIE_SUBSERIE] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[MERCADORIA_CODIGO] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Transf_Proce_Dow_Exp_2015] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
