SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIM_Transb](
	[Num_proc_MIM] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_Transb_MIM] [int] NOT NULL,
	[Navio_MIM] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Transb_MIM] [datetime] NULL,
 CONSTRAINT [PK_MIM_Transb] PRIMARY KEY CLUSTERED 
(
	[Num_proc_MIM] ASC,
	[Id_Transb_MIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[MIM_Transb]  WITH CHECK ADD  CONSTRAINT [FK_MIM_Transb_Master_Imp_Mar] FOREIGN KEY([Num_proc_MIM])
REFERENCES [dbo].[Master_Imp_Mar] ([Num_Proc_MIM])
GO
ALTER TABLE [dbo].[MIM_Transb] CHECK CONSTRAINT [FK_MIM_Transb_Master_Imp_Mar]
GO
