SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Projeto_DowAlpena](
	[Cd_Produto_Cliente] [nchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Grupo] [nchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Projeto_DowAlpena] PRIMARY KEY CLUSTERED 
(
	[Cd_Produto_Cliente] ASC,
	[Cd_Grupo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
