SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Cia_Aerea](
	[Cd_Cia_Aer] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Cia_Aer] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[SCAC] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[dt_criacao] [datetime] NULL,
	[IATA_CODE] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Prefix] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[EfreightDescartes] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Cd_Cia_Aer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nome_Cia_Aer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
