SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tela_Cargo](
	[Cd_Tela] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Cargo] [int] NOT NULL,
 CONSTRAINT [PK_Tela_Cargo] PRIMARY KEY CLUSTERED 
(
	[Cd_Tela] ASC,
	[Cd_Cargo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tela_Cargo]  WITH CHECK ADD  CONSTRAINT [FK_Tela_Cargo_Cargo] FOREIGN KEY([Cd_Cargo])
REFERENCES [dbo].[Cargo] ([Cd_Cargo])
GO
ALTER TABLE [dbo].[Tela_Cargo] CHECK CONSTRAINT [FK_Tela_Cargo_Cargo]
GO
ALTER TABLE [dbo].[Tela_Cargo]  WITH CHECK ADD  CONSTRAINT [FK_Tela_Cargo_Tela] FOREIGN KEY([Cd_Tela])
REFERENCES [dbo].[Tela] ([Cd_Tela])
GO
ALTER TABLE [dbo].[Tela_Cargo] CHECK CONSTRAINT [FK_Tela_Cargo_Tela]
GO
