SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Acesso_Area](
	[Cd_Area] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tela] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Obs_Acesso_Area] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
PRIMARY KEY NONCLUSTERED 
(
	[Cd_Area] ASC,
	[Cd_Tela] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Acesso_Area]  WITH CHECK ADD FOREIGN KEY([Cd_Area])
REFERENCES [dbo].[Area] ([Cd_Area])
GO
ALTER TABLE [dbo].[Acesso_Area]  WITH CHECK ADD FOREIGN KEY([Cd_Tela])
REFERENCES [dbo].[Tela] ([Cd_Tela])
GO
