SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Campo_Impostos](
	[Nota_Fiscal] [varchar](8) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Site] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_Imposto] [int] NOT NULL,
	[Valor] [decimal](18, 2) NULL,
	[Base] [decimal](18, 2) NOT NULL,
	[Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Campo_Impostos] PRIMARY KEY CLUSTERED 
(
	[Nota_Fiscal] ASC,
	[Cd_Site] ASC,
	[Id_Imposto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
