SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Campo_Label](
	[ID_Coluna] [int] NOT NULL,
	[Campo_ATL] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[ID_Label] [int] NOT NULL,
	[Cd_Tp_Layout] [int] NULL,
	[Status] [bit] NULL,
	[Divisao] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Campo_Label] PRIMARY KEY CLUSTERED 
(
	[ID_Coluna] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
