SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Report_Exp_Completo](
	[BDP Ref.] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[HAWB] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[MAWB] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Master] [varchar](14) COLLATE Latin1_General_CI_AI NULL,
	[Sales Order] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Register Date] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Customer PO] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[PO Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[PO Request Del Date] [datetime] NULL,
	[Order Date] [datetime] NULL,
	[Order Received - Date] [datetime] NULL,
	[Shipment Creation Date] [datetime] NULL,
	[Shipment Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Modal] [varchar](12) COLLATE Latin1_General_CI_AI NULL,
	[Shipper] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Consignee] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Group Name] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Origin] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Destination] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Country of Destination] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Region of Destination] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Carrier] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Containers] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Container Type] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[CONTAINER PARA O REDEX] [datetime] NULL,
	[ABERTURA DE GATE] [datetime] NULL,
	[REVISÃO DE DRAFT DE BL] [datetime] NULL,
	[DEPÓSITO CONTAINER NO TERMINAL] [datetime] NULL,
	[Gross Weight - Shipment - Value] [float] NULL,
	[Vessel] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[PAGTO FRETE E TAXAS AO ARMADOR] [datetime] NULL,
	[AUTORIZAÇÃO DE EMBARQUE] [datetime] NULL,
	[ETD Date] [datetime] NULL,
	[ATD Date] [datetime] NULL,
	[Original ETA - Date] [datetime] NULL,
	[ETA Date] [datetime] NULL,
	[ATA Date] [datetime] NULL,
	[EMISSÃO DE FORM A] [datetime] NULL,
	[EMISSÃO DE CO] [datetime] NULL,
	[PROTOCOLO DE MDGF] [datetime] NULL,
	[ENVIO DE MAS/ENS AO DESTINO] [datetime] NULL,
	[ENVIO DE ISF AO DESTINO] [datetime] NULL,
	[Good Receipt Date - Actual] [datetime] NULL,
	[Good Receipt Date - Estimated] [datetime] NULL,
	[Advanced Request Date] [datetime] NULL,
	[Advancement Received Date] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Draft EXP - Date] [datetime] NULL,
	[Dead Line Draft - Date] [datetime] NULL,
	[BL Payment Date] [datetime] NULL,
	[BL Released - Date] [datetime] NULL,
	[BL Description] [varchar](3000) COLLATE Latin1_General_CI_AI NULL,
	[Cut-off - Date] [datetime] NULL,
	[Port Entry Date] [datetime] NULL,
	[Dead at Terminal - Date] [datetime] NULL,
	[Plant Exit Date - Actual] [datetime] NULL,
	[Plant Exit Date - Estimated] [datetime] NULL,
	[Doc Sent - Date] [datetime] NULL,
	[Invoice Date] [datetime] NULL,
	[Invoice Sent Date] [datetime] NULL,
	[1 Envio Docs Brasilia - Date] [datetime] NULL,
	[1 Receb. em Brasilia - Date] [datetime] NULL,
	[Courier Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Courier Number - 2nd] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Bank] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Dispatch Type] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Government Agency] [varchar](60) COLLATE Latin1_General_CI_AI NULL,
	[RE Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[DDE Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[DDE - Date] [datetime] NULL,
	[Customs Clearance Date] [datetime] NULL,
	[Customs Transmission Date] [datetime] NULL,
	[1 Deferimento - Date] [datetime] NULL,
	[Channel] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Month of Clearance] [nvarchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Averbacao EXP - Date] [datetime] NULL,
	[Booking Number] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Booking Request Date] [datetime] NULL,
	[Booking Confirmation Date] [datetime] NULL,
	[Pre-Alert Sending - Date] [datetime] NULL,
	[SOLICIT. APROVAÇÃO IMO] [datetime] NULL,
	[IMO Approval - Date] [datetime] NULL,
	[ENVIO DE DOCS IMO] [datetime] NULL,
	[ENTREGA DOCS P/ FAT.CHB] [datetime] NULL,
	[NF BDP Date] [datetime] NULL,
	[NF Date] [datetime] NULL,
	[Docs to BDP Billing Date] [datetime] NULL,
	[BDP Invoice Creation - Date] [datetime] NULL,
	[BDP Invoice Date] [datetime] NULL,
	[PDF - Invoice] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - PL] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - COA] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - COO] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - NF] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - BL] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Saque] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - RE] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - DDE] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Courier] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Courier 2] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Form A] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Fumigacao] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Insurance] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - PC] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - Arqueacao] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PDF - DSE] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[Process Status] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Cd_BDP Last Historic] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Last Historic] [varchar](700) COLLATE Latin1_General_CI_AI NULL,
	[Last Update] [datetime] NULL,
	[Complete Historic] [varchar](4000) COLLATE Latin1_General_CI_AI NULL,
	[REGISTRO DE PROFIT] [datetime] NULL,
	[AUDITORIA DATA MANEGMENT] [datetime] NULL,
	[Arrival at the border - Date] [datetime] NULL,
	[Invoice] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Invoice value] [float] NULL,
	[Direct Collection] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Arktec Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[NF Number] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Net weight] [float] NULL,
	[NCM PO] [varchar](8) COLLATE Latin1_General_CI_AI NULL,
	[FOB Value] [float] NULL,
	[Registro AMS] [datetime] NULL,
	[Envio ISF] [datetime] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
