SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Aviso_Demurrage](
	[Num_Proc_MIM] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Item_Cont_IM] [varchar](2) COLLATE Latin1_General_CI_AI NOT NULL,
	[AvdPeriodo] [smallint] NOT NULL,
	[AvdEmail] [varchar](100) COLLATE Latin1_General_CI_AI NOT NULL,
	[AvdDtEnvio] [datetime] NOT NULL,
	[AvdFinal] [smallint] NOT NULL,
 CONSTRAINT [PK_Aviso_Demurrage] PRIMARY KEY CLUSTERED 
(
	[Num_Proc_MIM] ASC,
	[Item_Cont_IM] ASC,
	[AvdPeriodo] ASC,
	[AvdEmail] ASC,
	[AvdFinal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
