SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Doc_Anexos](
	[Item_Doc] [int] NOT NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_DC] [int] NOT NULL,
	[Nome_Arquivo] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Envio] [datetime] NULL,
	[Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[Anexado_Em] [datetime] NULL,
	[dt_creacao] [datetime] NULL,
	[cd_usuario_creacao] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[Numero_Doc] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Doc_Anexos] PRIMARY KEY CLUSTERED 
(
	[Item_Doc] ASC,
	[Num_Proc] ASC,
	[Id_DC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [Doc_Anexos_IX] ON [dbo].[Doc_Anexos]
(
	[Dt_Envio] ASC
)
INCLUDE([Num_Proc],[Id_DC]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Doc_Anexos_IX_2] ON [dbo].[Doc_Anexos]
(
	[Id_DC] ASC
)
INCLUDE([Num_Proc],[Nome_Arquivo],[Dt_Envio],[Anexado_Em],[dt_creacao]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
