SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Lancamento_RF](
	[Cd_Tipo_Lanc] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descricao_Tp_Lancamento] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[Ativo] [char](1) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Lancamento_RF] PRIMARY KEY CLUSTERED 
(
	[Cd_Tipo_Lanc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
