SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Evento](
	[TpeId] [int] IDENTITY(1,1) NOT NULL,
	[TpeDescricao] [varchar](20) COLLATE Latin1_General_CI_AI NOT NULL,
	[TpeAtivo] [int] NOT NULL,
	[TpeObriga_EA] [bit] NOT NULL,
	[TpeObriga_EM] [bit] NOT NULL,
	[TpeObriga_IA] [bit] NOT NULL,
	[TpeObriga_IM] [bit] NOT NULL,
	[TpeExchange] [bit] NOT NULL,
	[TpeRefExchange] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
	[TpeStatus] [bit] NOT NULL,
 CONSTRAINT [PK_Tipo_Evento] PRIMARY KEY CLUSTERED 
(
	[TpeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Tipo_Evento] UNIQUE NONCLUSTERED 
(
	[TpeDescricao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tipo_Evento] ADD  CONSTRAINT [DF_Tipo_Evento_TpeStatus]  DEFAULT (1) FOR [TpeStatus]
GO
