SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PO_HBO](
	[Num_Proc_HBO] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[ID_PO_HBO] [int] NOT NULL,
	[Numero_PO_HBO] [varchar](80) COLLATE Latin1_General_CI_AI NOT NULL,
	[Data_PO_HBO] [datetime] NULL,
	[ID_DC] [int] NULL,
	[cd_usuario] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[dt_ins] [datetime] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
CREATE NONCLUSTERED INDEX [IX_PO_HBO_01] ON [dbo].[PO_HBO]
(
	[Num_Proc_HBO] ASC,
	[ID_DC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
