SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Rel_SCHCASS_INVOICE_PARIDADES](
	[FATCOD] [varchar](17) COLLATE Latin1_General_CI_AI NOT NULL,
	[PARIDADE_01] [float] NULL,
	[MOEDA_PARIDADE_01] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[PARIDADE_02] [float] NULL,
	[MOEDA_PARIDADE_02] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[QTD_PARIDADE] [int] NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
