SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tar_Tar_Mar](
	[TAMID] [int] NOT NULL,
	[Cd_Tp_Cont] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[TTMVlrComp] [float] NULL,
	[TTMVlrVnd] [float] NULL,
	[TTMBAF] [float] NULL,
 CONSTRAINT [PK_Tar_Tar_Mar] PRIMARY KEY CLUSTERED 
(
	[TAMID] ASC,
	[Cd_Tp_Cont] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tar_Tar_Mar]  WITH CHECK ADD  CONSTRAINT [FK_Tar_Tar_Mar_Tipo_Cont_Tar] FOREIGN KEY([Cd_Tp_Cont])
REFERENCES [dbo].[Tipo_Cont_Tar] ([Cd_Tp_Cont])
GO
ALTER TABLE [dbo].[Tar_Tar_Mar] CHECK CONSTRAINT [FK_Tar_Tar_Mar_Tipo_Cont_Tar]
GO
