SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Container_Hou_Exp_Mar](
	[Num_Proc_MEM] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Item_Cont_EM] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Num_Proc_HEM] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK__Container_Hou_Ex__51300E55] PRIMARY KEY CLUSTERED 
(
	[Num_Proc_MEM] ASC,
	[Item_Cont_EM] ASC,
	[Num_Proc_HEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_Container_Hou_Exp_Mar_01] ON [dbo].[Container_Hou_Exp_Mar]
(
	[Num_Proc_HEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Container_Hou_Exp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Container__Num_P__2882FE7D] FOREIGN KEY([Num_Proc_HEM])
REFERENCES [dbo].[House_Exp_Mar] ([Num_Proc_HEM])
GO
ALTER TABLE [dbo].[Container_Hou_Exp_Mar] CHECK CONSTRAINT [FK__Container__Num_P__2882FE7D]
GO
ALTER TABLE [dbo].[Container_Hou_Exp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Container_Hou_Ex__297722B6] FOREIGN KEY([Num_Proc_MEM], [Item_Cont_EM])
REFERENCES [dbo].[Container_Mas_Exp_Mar] ([Num_Proc_MEM], [Item_Cont_EM])
GO
ALTER TABLE [dbo].[Container_Hou_Exp_Mar] CHECK CONSTRAINT [FK__Container_Hou_Ex__297722B6]
GO
