SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ALFRIO_TB_ARMADOR](
	[CODIGO] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[NOME] [varchar](60) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
