SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Prd_Mas_Exp_Mar](
	[Num_Proc_MEM] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Prod_MEM] [varchar](2000) COLLATE Latin1_General_CI_AI NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Num_Proc_MEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Prd_Mas_Exp_Mar]  WITH NOCHECK ADD  CONSTRAINT [FK__Prd_Mas_E__Num_P__1C1D2798] FOREIGN KEY([Num_Proc_MEM])
REFERENCES [dbo].[Master_Exp_Mar] ([Num_Proc_MEM])
GO
ALTER TABLE [dbo].[Prd_Mas_Exp_Mar] CHECK CONSTRAINT [FK__Prd_Mas_E__Num_P__1C1D2798]
GO
