SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Grupo_Taxa](
	[Cd_Gp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Gp_Tx] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Status] [bit] NOT NULL,
	[Descricao] [varchar](250) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Grupo_Taxa] PRIMARY KEY CLUSTERED 
(
	[Cd_Gp_Tx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
