SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AUX_ALE_DESENV_TRACKING_CORTEVA](
	[BDP Ref.] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[Register Date] [datetime] NULL,
	[Requisição do Cliente - Number] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Order Received - Date] [datetime] NULL,
	[Order Type] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Customer PO] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Product ID] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Product Description] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[NCM] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[UOM] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Qty] [float] NULL,
	[UNIT Price] [float] NULL,
	[Invoice Value] [float] NULL,
	[Invoice Currency] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Manufacturer] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Country Manufacturer] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Shipper] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Shipper Address] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Country of Origin] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Consignee] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Consignee Address] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Modal] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Incoterm] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Origin] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Destination] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Booking Request Date] [datetime] NULL,
	[Booking Number] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Booking Confirmation Date] [datetime] NULL,
	[ETD - Date] [datetime] NULL,
	[ETA - Date] [datetime] NULL,
	[ETA - Promised] [datetime] NULL,
	[GR Requested - Date] [datetime] NULL,
	[Customer Partner] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[LI Request - Date] [datetime] NULL,
	[LI Date] [datetime] NULL,
	[Import License] [varchar](400) COLLATE Latin1_General_CI_AI NULL,
	[Green light - Date] [datetime] NULL,
	[Invoice] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Master] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[House] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Freight Type] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Freight - USD] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Carrier] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Vessel] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Containers] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[Container Type] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Container Qty] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Docs Received Date] [datetime] NULL,
	[Unloaded Date] [datetime] NULL,
	[Terminal] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Inspection MAPA - Date] [datetime] NULL,
	[Def. LI - Date] [datetime] NULL,
	[Customs Transmission Date] [datetime] NULL,
	[Entry Number] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[NF Number] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[NF Date] [datetime] NULL,
	[Transport. Doc Delivery Date] [datetime] NULL,
	[Loading at the Terminal] [datetime] NULL,
	[Inland trucker] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Good Receipt Date - Estimated] [datetime] NULL,
	[Good Receipt Date - Actual] [datetime] NULL,
	[GR - Date] [datetime] NULL,
	[Container Returned CC] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Container Returned] [datetime] NULL,
	[Days at the Port] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Last Historic] [varchar](2000) COLLATE Latin1_General_CI_AI NULL,
	[Process Status] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Transshipment Arrival - Date] [datetime] NULL,
	[Transshipment Departure - Date] [datetime] NULL,
	[Reponsible PO] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Packing] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Reason Code Events] [varchar](300) COLLATE Latin1_General_CI_AI NULL,
	[Order Reference] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Processo Critico(Y/N)] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Country of Destination] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[CSR Name] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[PO Request Delivery Date] [datetime] NULL,
	[ETA Requested Date] [datetime] NULL,
	[Plant ID] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[Item] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Net Weight KG] [float] NULL,
	[Gross Weight KG] [float] NULL,
	[Voyage] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[ATD Date] [datetime] NULL,
	[ATA Date] [datetime] NULL,
	[CNPJ] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Type of Cargo] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Netweight KG- Shipment] [float] NULL,
	[Gross Weight - Shipment - Value] [float] NULL,
	[Volume M3] [float] NULL,
	[BL Pieces] [float] NULL,
	[Freight Currency] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Freight BL] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Freight BL VALUE] [float] NULL,
	[Original ETA - Date] [datetime] NULL,
	[Notes] [varchar](1000) COLLATE Latin1_General_CI_AI NULL,
	[BDP Product] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Despacho] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Necessidade de LI?] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Invoice Date] [datetime] NULL,
	[Container Yard Request Date] [datetime] NULL,
	[Port Entry Date] [datetime] NULL,
	[Protocol MAPA IN26 date] [datetime] NULL,
	[Post Import License Release date] [datetime] NULL,
	[Customs Clearance Date] [datetime] NULL,
	[Channel] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Gross Weight - NF] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Demurrage Period] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Demurrage Value] [float] NULL,
	[Aprovação de Draft (copias)] [datetime] NULL,
	[Pré-alerta enviado] [datetime] NULL,
	[Nº Protocolo MAPA] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Delivery Address] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[cd_produto] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[cd_pedido] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[Item_Pedido] [varchar](200) COLLATE Latin1_General_CI_AI NULL,
	[GR Original] [datetime] NULL,
	[Documentos OK para Registro] [datetime] NULL,
	[MADEIRA LIBERADA] [datetime] NULL,
	[SLA Calculado] [datetime] NULL,
	[SLA Ontime] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Responsability] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Free Time] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[Taxa Moeda da Fatura] [float] NULL,
	[Taxa Moeda do Frete] [float] NULL,
	[Valor PRG] [float] NULL,
	[Margem] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[Liberação de BL] [datetime] NULL,
	[Valor PGR R$] [float] NULL,
	[Courier Number] [varchar](100) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
