SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Account_SFDC_BKP](
	[Cd_Pes] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_AX] [int] NOT NULL,
	[Tipo] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[SFDCID] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Ins] [datetime] NOT NULL,
	[Dt_Envio] [datetime] NULL,
	[Dt_Upd] [datetime] NULL,
 CONSTRAINT [PK_Account_SFDC_BKP] PRIMARY KEY CLUSTERED 
(
	[Cd_Pes] ASC,
	[Cd_AX] ASC,
	[Tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
