SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BDP_Produto](
	[ID_PD] [int] NOT NULL,
	[Nome_BDP_Produto] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_BDP_Produto] PRIMARY KEY CLUSTERED 
(
	[ID_PD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
