SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Pais_IBGE](
	[Cd_Pais_IBGE] [varchar](15) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Pais] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Cd_Pais] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Pais_IBGE] PRIMARY KEY CLUSTERED 
(
	[Cd_Pais_IBGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
