SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Alerta_Padrao](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Alerta] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Conteudo] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[cd_usuario] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[dt_ins] [datetime] NULL,
	[Ativo] [char](1) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Alerta_Padrao] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
