SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[LLP_BDP_OUT](
	[Num_Proc_LBO] [varchar](16) COLLATE Latin1_General_CI_AI NOT NULL,
	[ID_Status] [int] NULL,
	[Cd_Usuario] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[Id_TP_Servico] [bigint] NULL,
	[PO_Req_Date] [datetime] NULL,
 CONSTRAINT [PK_LLP_BDP_OUT] PRIMARY KEY CLUSTERED 
(
	[Num_Proc_LBO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
