SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Aux_Embalagem](
	[Cd_Embal_Ofc] [char](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Embalagem] [varchar](60) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Aux_Embalagem] PRIMARY KEY CLUSTERED 
(
	[Cd_Embal_Ofc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
