SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Produto_Cliente_16112018](
	[cd_prod] [int] NOT NULL,
	[cd_Proc_Cliente] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[cd_Cliente] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[Produto_Descr] [varchar](500) COLLATE Latin1_General_CI_AI NOT NULL,
	[NCM_Cliente] [varchar](8) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Produto_Cliente_16112018] PRIMARY KEY CLUSTERED 
(
	[cd_prod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
