SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Orgao_Anuente](
	[ID_Orgao] [int] NOT NULL,
	[Nome_Orgao_Anuente] [varchar](60) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Orgao_Anuente] PRIMARY KEY CLUSTERED 
(
	[ID_Orgao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
