SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IBROKER_ITDI](
	[ID_ITDI] [bigint] NOT NULL,
	[ID_View] [bigint] NULL,
	[01] [varchar](4) COLLATE Latin1_General_CI_AI NULL,
	[02] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[03] [varchar](6) COLLATE Latin1_General_CI_AI NULL,
	[04] [varchar](14) COLLATE Latin1_General_CI_AI NULL,
	[05] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[06] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[07] [varchar](150) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_IBROKER_ITDI] PRIMARY KEY CLUSTERED 
(
	[ID_ITDI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
