SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tax_Tar_Mar](
	[TAMID] [int] NOT NULL,
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Moeda] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[TXMValor] [float] NOT NULL,
	[TXMEspec] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tax_Tar_Mar] PRIMARY KEY CLUSTERED 
(
	[TAMID] ASC,
	[Cd_Tp_Tx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tax_Tar_Mar]  WITH CHECK ADD  CONSTRAINT [FK_Tax_Tar_Mar_Tipo_Moeda] FOREIGN KEY([Cd_Tp_Moeda])
REFERENCES [dbo].[Tipo_Moeda] ([Cd_Tp_Moeda])
GO
ALTER TABLE [dbo].[Tax_Tar_Mar] CHECK CONSTRAINT [FK_Tax_Tar_Mar_Tipo_Moeda]
GO
ALTER TABLE [dbo].[Tax_Tar_Mar]  WITH CHECK ADD  CONSTRAINT [FK_Tax_Tar_Mar_Tipo_Taxa] FOREIGN KEY([Cd_Tp_Tx])
REFERENCES [dbo].[Tipo_Taxa] ([Cd_Tp_Tx])
GO
ALTER TABLE [dbo].[Tax_Tar_Mar] CHECK CONSTRAINT [FK_Tax_Tar_Mar_Tipo_Taxa]
GO
