SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADICAO_TEMP](
	[CD_ACORDO_ALADI] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[CD_AUSENCIA_FABRIC] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[CD_COBERT_CAMBIAL] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[CD_INCOTERMS] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[CD_MERC_NALADI] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[CD_MERC_NBM_SH] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[CD_MERCADORIA_NCM] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[DT_ANO_ATO_VINCUL_1] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[DT_ANO_ATO_VINCUL_2] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[DT_ANO_ATO_VINCUL_3] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[DT_ANO_ATO_VINCUL_4] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[DT_ANO_ATO_VINCUL_5] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[DT_ANO_ATO_VINCUL_6] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[IN_MATERIAL_USADO] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[NM_COBERT_CAMBIAL] [varchar](10) COLLATE Latin1_General_CI_AI NULL,
	[NM_FABRICANTE_MERC] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[NM_FORN_ESTR] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[NM_FUND_LEGAL] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[NM_MERCADORIA_NCM] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[NM_METODO_VALORACAO] [varchar](500) COLLATE Latin1_General_CI_AI NULL,
	[NM_MOEDA_FRETE_MERC] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[NM_MOEDA_NEGOCIADA] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[NM_MOEDA_SEG_MERC] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[NM_MOTIVO_SEM_COB] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[NM_PAIS_AQUIS_MERC] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_PAIS_ORIG_MERC] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_REGIME_TRIBUTAR] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_TIPO_ACORDO_TAR] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_TIPO_ALIQ_ANDP] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_TIPO_ALIQUOTA_II] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_TIPO_ALIQUOTA_IPI] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_TIPO_BENEF_IPI] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_TIPO_DCTO_VINC] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_UN_ALIQ_ESP_ANDP] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_UN_ALIQ_ESP_IPI] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_ADICAO_IMP] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[NR_ATO_DRAWBACK] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_ATO_VINCULADO_1] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_ATO_VINCULADO_2] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_ATO_VINCULADO_3] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_ATO_VINCULADO_4] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_ATO_VINCULADO_5] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_ATO_VINCULADO_6] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_DCTO_REDUCAO] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_DCTO_VINCULADO] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_DECLARACAO_IMP] [varchar](40) COLLATE Latin1_General_CI_AI NULL,
	[NR_EX_ATO_VINCUL_1] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_EX_ATO_VINCUL_2] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_EX_ATO_VINCUL_5] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_EX_ATO_VINCUL_6] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_NOTA_COMPL_TIPI] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NR_OPER_TRAT_PREV] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[PC_REDUCAO_II] [float] NULL,
	[PC_REDUCAO_IPI] [float] NULL,
	[PL_MERCADORIA] [float] NULL,
	[SG_ORG_ATO_VINCUL_1] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_ORG_ATO_VINCUL_2] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_ORG_ATO_VINCUL_3] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_ORG_ATO_VINCUL_4] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_ORG_ATO_VINCUL_5] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_ORG_ATO_VINCUL_6] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_TIPO_ATO_VINCUL_1] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_TIPO_ATO_VINCUL_2] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_TIPO_ATO_VINCUL_3] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_TIPO_ATO_VINCUL_4] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_TIPO_ATO_VINCUL_5] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[SG_TIPO_ATO_VINCUL_6] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[TX_COMPL_VL_ADUAN] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_ANDP] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_II] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_IPI] [decimal](18, 2) NULL,
	[VL_BASE_CALC_ADVAL_II] [decimal](18, 2) NULL,
	[VL_BASE_CALC_ANDP] [decimal](18, 2) NULL,
	[VL_BASE_CALC_IPI] [decimal](18, 2) NULL,
	[VL_CALC_ADVAL_II] [decimal](18, 2) NULL,
	[VL_CALC_ANDP] [decimal](18, 2) NULL,
	[VL_CALC_ESPEC_II] [decimal](18, 2) NULL,
	[VL_CALC_IPI] [decimal](18, 2) NULL,
	[VL_COEF_REDUC_II] [decimal](18, 2) NULL,
	[VL_COMISSAO_AG_IMP] [decimal](18, 2) NULL,
	[VL_FRETE_MERC_MNEG] [decimal](18, 2) NULL,
	[VL_II_A_REC_ZFM] [decimal](18, 2) NULL,
	[VL_II_CALCULADO_DCR] [decimal](18, 2) NULL,
	[VL_MERC_COND_VENDA] [decimal](18, 2) NULL,
	[VL_REC_II] [decimal](18, 2) NULL,
	[VL_REC_IPI] [decimal](18, 2) NULL,
	[VL_SEG_MERC_MNEG] [decimal](18, 2) NULL,
	[NM_REGIME_TRIBUTAR_PISCOF] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[VL_ALIQUOTA_PIS] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_COFINS] [decimal](18, 2) NULL,
	[VL_BASE_CALC_PISCOFINS] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_REDU_PIS] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_REDU_COFINS] [decimal](18, 2) NULL,
	[VL_DEVIDO_PIS] [decimal](18, 2) NULL,
	[VL_DEVIDO_COFINS] [decimal](18, 2) NULL,
	[VL_RECOLHER_PIS] [decimal](18, 2) NULL,
	[VL_RECOLHER_COFINS] [decimal](18, 2) NULL,
	[NM_UN_ALIQ_ESP_PIS] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[NM_UN_ALIQ_ESP_COFINS] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[QT_UN_MED_PIS] [decimal](18, 2) NULL,
	[QT_UN_MED_COFINS] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_ESP_PIS] [decimal](18, 2) NULL,
	[VL_ALIQUOTA_ESP_COFINS] [decimal](18, 2) NULL,
	[PC_REDUC_BASE_PISCOFINS] [decimal](18, 2) NULL,
	[VL_ALIQ_ICMS] [decimal](18, 2) NULL,
	[NM_TIPO_CERTIFICADO] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[IN_CERTIFICADO_BR] [varchar](100) COLLATE Latin1_General_CI_AI NULL,
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
