SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[custo_temp](
	[Num_Proc] [varchar](16) COLLATE Latin1_General_CI_AI NULL,
	[Valor] [decimal](18, 2) NULL,
	[Cd_TP_Tx] [char](3) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
