SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Centro_Custo_Site](
	[Cd_Centro_Custo] [varchar](5) COLLATE Latin1_General_CI_AI NOT NULL,
	[Site] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Particip] [decimal](4, 2) NOT NULL,
 CONSTRAINT [PK_Centro_Custo_Site] PRIMARY KEY CLUSTERED 
(
	[Cd_Centro_Custo] ASC,
	[Site] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
