SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS](
	[BILLING_NUMBER] [varchar](22) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_1] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_1] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_1] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_1] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_2] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_2] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_2] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_2] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_3] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_3] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_3] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_3] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_4] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_4] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_4] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_4] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_5] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_5] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_5] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_5] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_6] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_6] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_6] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_6] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_7] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_7] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_7] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_7] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_8] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_8] [varchar](2) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_8] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_8] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_9] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_9] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_9] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_9] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_10] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_10] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_10] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_10] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_11] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_11] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_11] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_11] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_12] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_12] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_12] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_12] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_13] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_13] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_13] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_13] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_14] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_14] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_14] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_14] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CODE_15] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_DESC_15] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_CURR_15] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CHRG_AMNT_15] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[VAT_CODE] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[VAT_CURR] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[VAT_AMNT] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[CURR_CONVERT_1] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CURR_EXCHANGE_1] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CURR_CONVERT_2] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[CURR_EXCHANGE_2] [varchar](15) COLLATE Latin1_General_CI_AI NULL,
	[CURR_PAYMENT] [varchar](3) COLLATE Latin1_General_CI_AI NULL,
	[TOTAL_EXCL_VAT] [char](1) COLLATE Latin1_General_CI_AI NULL,
	[TOTAL_INCL_VAT] [char](1) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
