SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Pessoa_ATL_AX](
	[Cd_Pes] [varchar](11) COLLATE Latin1_General_CI_AI NOT NULL,
	[cd_ax] [int] NOT NULL,
	[CNPJ] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Sales_Tax_Group] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
	[Tipo] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Pessoa_ATL_AX] PRIMARY KEY CLUSTERED 
(
	[Cd_Pes] ASC,
	[cd_ax] ASC,
	[Tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
