SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Solicitacao_LI_Orgao_Anuente](
	[Num_Solicitacao] [varchar](13) COLLATE Latin1_General_CI_AI NOT NULL,
	[ID_Orgao_Anuente] [int] NOT NULL,
 CONSTRAINT [PK_Solicitacao_LI_Orgao_Anuente] PRIMARY KEY CLUSTERED 
(
	[Num_Solicitacao] ASC,
	[ID_Orgao_Anuente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
