SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tax_Tar_Aer](
	[TAEID] [int] NOT NULL,
	[Cd_Tp_Tx] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Tp_Moeda] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[TXAValor] [float] NOT NULL,
	[TXAEspec] [varchar](30) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tax_Tar_Aer] PRIMARY KEY CLUSTERED 
(
	[TAEID] ASC,
	[Cd_Tp_Tx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Tax_Tar_Aer]  WITH NOCHECK ADD  CONSTRAINT [FK_Tax_Tar_Aer_Tar_Aer] FOREIGN KEY([TAEID])
REFERENCES [dbo].[Tar_Aer] ([TAEID])
GO
ALTER TABLE [dbo].[Tax_Tar_Aer] CHECK CONSTRAINT [FK_Tax_Tar_Aer_Tar_Aer]
GO
ALTER TABLE [dbo].[Tax_Tar_Aer]  WITH CHECK ADD  CONSTRAINT [FK_Tax_Tar_Aer_Tipo_Moeda] FOREIGN KEY([Cd_Tp_Moeda])
REFERENCES [dbo].[Tipo_Moeda] ([Cd_Tp_Moeda])
GO
ALTER TABLE [dbo].[Tax_Tar_Aer] CHECK CONSTRAINT [FK_Tax_Tar_Aer_Tipo_Moeda]
GO
ALTER TABLE [dbo].[Tax_Tar_Aer]  WITH CHECK ADD  CONSTRAINT [FK_Tax_Tar_Aer_Tipo_Taxa] FOREIGN KEY([Cd_Tp_Tx])
REFERENCES [dbo].[Tipo_Taxa] ([Cd_Tp_Tx])
GO
ALTER TABLE [dbo].[Tax_Tar_Aer] CHECK CONSTRAINT [FK_Tax_Tar_Aer_Tipo_Taxa]
GO
