SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Aduanas_ARG](
	[CodAduana] [varchar](3) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Aduana] [varchar](30) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_Aduanas_AR] PRIMARY KEY CLUSTERED 
(
	[CodAduana] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
