SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IBrokerView_Log](
	[ID] [bigint] NOT NULL,
	[ID_View] [bigint] NOT NULL,
	[Num_Proc] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Tipo] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Cd_Usuario] [varchar](10) COLLATE Latin1_General_CI_AI NOT NULL,
	[Dt_Insert] [datetime] NOT NULL,
 CONSTRAINT [PK_IBrokerView_Log] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
