SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Tipo_Master](
	[Cd_Tp_Master] [char](1) COLLATE Latin1_General_CI_AI NOT NULL,
	[Nome_Tp_Master] [varchar](20) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_Tipo_Master] PRIMARY KEY CLUSTERED 
(
	[Cd_Tp_Master] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
