SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IBROKER_Pessoa_V2](
	[ID] [bigint] NOT NULL,
	[Cd_Pes] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Ibroker] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Apelido] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Detalhe] [varchar](max) COLLATE Latin1_General_CI_AI NULL,
	[Tipo] [varchar](1) COLLATE Latin1_General_CI_AI NOT NULL,
 CONSTRAINT [PK_IBROKER_Pessoa] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[Tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
