SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATL_Labels](
	[ID] [int] NOT NULL,
	[Descr_ING] [varchar](50) COLLATE Latin1_General_CI_AI NOT NULL,
	[Descr_PTG] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
	[Descr_ESP] [varchar](50) COLLATE Latin1_General_CI_AI NULL,
 CONSTRAINT [PK_ATL_Labels] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_ATL_Labels] ON [dbo].[ATL_Labels]
(
	[Descr_ING] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE FULLTEXT INDEX ON [dbo].[ATL_Labels]
KEY INDEX [PK_ATL_Labels]ON ([num_proc], FILEGROUP [ftfg_num_proc])
WITH (CHANGE_TRACKING = AUTO, STOPLIST = SYSTEM)


GO
ALTER FULLTEXT INDEX ON [dbo].[ATL_Labels] DISABLE
GO
