SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Interlog_LOG](
	[Arquivo] [varchar](100) COLLATE Latin1_General_CI_AI NOT NULL,
	[Erro] [varchar](600) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Erro] [datetime] NULL,
 CONSTRAINT [PK_Interlog_LOG] PRIMARY KEY CLUSTERED 
(
	[Arquivo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
