SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MEM_Transb](
	[Num_proc_MEM] [varchar](14) COLLATE Latin1_General_CI_AI NOT NULL,
	[Id_Transb_MEM] [int] NOT NULL,
	[Navio_MEM] [varchar](25) COLLATE Latin1_General_CI_AI NULL,
	[Dt_Transb_MEM] [datetime] NULL,
 CONSTRAINT [PK_MEM_Transb] PRIMARY KEY CLUSTERED 
(
	[Num_proc_MEM] ASC,
	[Id_Transb_MEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[MEM_Transb]  WITH CHECK ADD  CONSTRAINT [FK_MEM_Transb_Master_Exp_Mar] FOREIGN KEY([Num_proc_MEM])
REFERENCES [dbo].[Master_Exp_Mar] ([Num_Proc_MEM])
GO
ALTER TABLE [dbo].[MEM_Transb] CHECK CONSTRAINT [FK_MEM_Transb_Master_Exp_Mar]
GO
