SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure spReportNF_Aberto

as


SELECT CTA.NUM_PROC_HIM,CTA.NUM_NF_HIM,SUM(VLR_PGTO_NF_HIM) FROM CTA_CTE_HOU_IMP_MAR CTA
lEFT jOIN CAIXA_HOU_IMP_MAR cxA ON CTA.NUM_PROc_HIM=CXA.NUM_PROC_HIM AND CTA.CD_TP_TX=CXA.CD_TP_TX AND CTA.DC_HIM=CXA.DC_HIM
WHERE CTA.NUM_NF_HIM IS NOT NULL AND CXA.NUM_PROC_HIM IS NULL AND REF_ACESSO_NF_HIM='B'
GROUP BY CTA.NUM_NF_HIM ,CTA.NUM_PROC_HIM

UNION

SELECT CTA.NUM_PROC_HIA,CTA.NUM_NF_HIA,SUM(VLR_PGTO_NF_HIA) FROM CTA_CTE_HOU_IMP_AER CTA
lEFT jOIN CAIXA_HOU_IMP_AER cxA ON CTA.NUM_PROc_HIA=CXA.NUM_PROC_HIA AND CTA.CD_TP_TX=CXA.CD_TP_TX AND CTA.DC_HIA=CXA.DC_HIA
WHERE CTA.NUM_NF_HIA IS NOT NULL AND CXA.NUM_PROC_HIA IS NULL AND REF_ACESSO_NF_HIA='B'
GROUP BY CTA.NUM_NF_HIA ,CTA.NUM_PROC_HIA

UNION


SELECT CTA.NUM_PROC_HIO,CTA.NUM_NF_HIO,SUM(VLR_PGTO_NF_HIO) FROM CTA_CTE_HOU_IMP_OUT CTA
lEFT jOIN CAIXA_HOU_IMP_OUT cxA ON CTA.NUM_PROc_HIO=CXA.NUM_PROC_HIO AND CTA.CD_TP_TX=CXA.CD_TP_TX AND CTA.DC_HIO=CXA.DC_HIO
WHERE CTA.NUM_NF_HIO IS NOT NULL AND CXA.NUM_PROC_HIO IS NULL AND REF_ACESSO_NF_HIO='B'
GROUP BY CTA.NUM_NF_HIO ,CTA.NUM_PROC_HIO

union

SELECT CTA.NUM_PROC_HEM,CTA.NUM_NF_HEM,SUM(VLR_PGTO_NF_HEM) FROM CTA_CTE_HOU_EXP_MAR CTA
lEFT jOIN CAIXA_HOU_EXP_MAR cxA ON CTA.NUM_PROc_HEM=CXA.NUM_PROC_HEM AND CTA.CD_TP_TX=CXA.CD_TP_TX AND CTA.DC_HEM=CXA.DC_HEM
WHERE CTA.NUM_NF_HEM IS NOT NULL AND CXA.NUM_PROC_HEM IS NULL AND REF_ACESSO_NF_HEM='B'
GROUP BY CTA.NUM_NF_HEM ,CTA.NUM_PROC_HEM

UNION

SELECT CTA.NUM_PROC_HEA,CTA.NUM_NF_HEA,SUM(VLR_PGTO_NF_HEA) FROM CTA_CTE_HOU_EXP_AER CTA
lEFT jOIN CAIXA_HOU_EXP_AER cxA ON CTA.NUM_PROc_HEA=CXA.NUM_PROC_HEA AND CTA.CD_TP_TX=CXA.CD_TP_TX AND CTA.DC_HEA=CXA.DC_HEA
WHERE CTA.NUM_NF_HEA IS NOT NULL AND CXA.NUM_PROC_HEA IS NULL AND REF_ACESSO_NF_HEA='B'
GROUP BY CTA.NUM_NF_HEA ,CTA.NUM_PROC_HEA

UNION


SELECT CTA.NUM_PROC_heo,CTA.NUM_NF_heo,SUM(VLR_PGTO_NF_heo) FROM CTA_CTE_HOU_EXP_OUT CTA
lEFT jOIN CAIXA_HOU_EXP_OUT cxA ON CTA.NUM_PROc_heo=CXA.NUM_PROC_heo AND CTA.CD_TP_TX=CXA.CD_TP_TX AND CTA.DC_heo=CXA.DC_heo
WHERE CTA.NUM_NF_heo IS NOT NULL AND CXA.NUM_PROC_heo IS NULL AND REF_ACESSO_NF_heo='B'
GROUP BY CTA.NUM_NF_heo ,CTA.NUM_PROC_heo
GO
