SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[pOracle_Receivables_InsUpd]
(
    @ID BIGINT,
    @Category NVARCHAR(50),
    @Ledger_Name NVARCHAR(50),
    @Source NVARCHAR(50),
    @Period NVARCHAR(50),
    @Currency NVARCHAR(50),
    @Batch NVARCHAR(50),
    @Status NVARCHAR(50),
    @Accounting_Flexfield NVARCHAR(50),
    @Account_Description NVARCHAR(50),
    @Company NVARCHAR(50),
    @GL_Account NVARCHAR(50),
    @Product NVARCHAR(50),
    @Resp_Center NVARCHAR(50),
    @Location NVARCHAR(50),
    @Interco NVARCHAR(50),
    @Customer NVARCHAR(50),
    @Future1 NVARCHAR(50),
    @Future2 NVARCHAR(50),
    @Entered_DR DECIMAL(18,2),
    @Entered_CR DECIMAL(18,2),
    @Entered_Net DECIMAL(18,2),
    @Accounted_DR DECIMAL(18,2),
    @Accounted_CR DECIMAL(18,2),
    @Accounted_Net DECIMAL(18,2),
    @Header_Desc NVARCHAR(50),
    @Line_Description NVARCHAR(250),
    @Journal_Sequence NVARCHAR(50),
    @Accounting_Date DATETIME,
    @Invoice_Num NVARCHAR(50),
    @Invoice_Date DATETIME,
    @Trading_Partner_Name NVARCHAR(250),
    @Trading_Partner_Number NVARCHAR(50),
    @Trading_Partner_Site NVARCHAR(50),
    @Account_type NVARCHAR(50),
    @H_Job_No NVARCHAR(50),
    @H_Master_BOL NVARCHAR(50),
    @H_House_BOL NVARCHAR(50),
    @H_Master_Booking_Number NVARCHAR(50),
    @H_Global_Customer NVARCHAR(50),
    @H_Customer_Ref NVARCHAR(250),
    @H_CSR_Email NVARCHAR(50),
    @H_Voucher_Reference_Num NVARCHAR(50),
    @Job_No NVARCHAR(50),
    @Master_BOL NVARCHAR(50),
    @House_BOL NVARCHAR(50),
    @Master_Booking_Number NVARCHAR(50),
    @Global_Customer NVARCHAR(50),
    @Customer_PO NVARCHAR(50),
    @Customer_Ref NVARCHAR(50),
    @CSR_Email NVARCHAR(50),
    @Job_Customer_Account NVARCHAR(50),
    @Customer_Vendor_Group NVARCHAR(50),
    @Charge_Code NVARCHAR(50),
    @Sales_Invoice_Number NVARCHAR(50),
    @Voucher_Reference_Num NVARCHAR(50),
    @Tax_Classification NVARCHAR(50),
    @Actual_Date DATETIME,
    @Created_by NVARCHAR(50),
    @Original_Invoice_Amount_Entered DECIMAL(18,2),
    @Original_Invoice_Amount_Accounting DECIMAL(18,2),
    @Exchange_Rate DECIMAL(18,2),
    @Open_Amount_Entered DECIMAL(18,2),
    @Open_Amount_Local DECIMAL(18,2),
    @Oracle_UserID BIGINT,
    @IsActive BIT,
    @CreateadDate DATETIME,
    @UpdatedDate DATETIME
)
AS
BEGIN
    BEGIN TRY
        BEGIN TRAN         
            DECLARE @ID_New AS BIGINT;

			IF EXISTS(SELECT TOP 1 ID FROM Oracle_Receivables WHERE Invoice_Num = @Invoice_Num)
			BEGIN
				Set @ID = (SELECT TOP 1 ID FROM Oracle_Receivables WHERE Invoice_Num = @Invoice_Num)
			END            

            IF EXISTS(SELECT ID FROM Oracle_Receivables WHERE ID = @ID)
            BEGIN
                UPDATE 
                    Oracle_Receivables
                SET
     --               Category = @Category,
					--Ledger_Name = @Ledger_Name,
					--Source = @Source,
					--Period = @Period,
					--Currency = @Currency,
					--Batch = @Batch,
					--Status = @Status,
					--Accounting_Flexfield = @Accounting_Flexfield,
					--Account_Description = @Account_Description,
					--Company = @Company,
					--GL_Account = @GL_Account,
					--Product = @Product,
					--Resp_Center = @Resp_Center,
					--Location = @Location,
					--Interco = @Interco,
					--Customer = @Customer,
					--Future1 = @Future1,
					--Future2 = @Future2,
					--Entered_DR = @Entered_DR,
					--Entered_CR = @Entered_CR,
					--Entered_Net = @Entered_Net,
					--Accounted_DR = @Accounted_DR,
					--Accounted_CR = @Accounted_CR,
					--Accounted_Net = @Accounted_Net,
					--Header_Desc = @Header_Desc,
					--Line_Description = @Line_Description,
					Journal_Sequence = @Journal_Sequence,
					--Accounting_Date = @Accounting_Date,
					--Invoice_Num = @Invoice_Num,
					--Invoice_Date = @Invoice_Date,
					--Trading_Partner_Name = @Trading_Partner_Name,
					--Trading_Partner_Number = @Trading_Partner_Number,
					--Trading_Partner_Site = @Trading_Partner_Site,
					--Account_type = @Account_type,
					--H_Job_No = @H_Job_No,
					--H_Master_BOL = @H_Master_BOL,
					--H_House_BOL = @H_House_BOL,
					--H_Master_Booking_Number = @H_Master_Booking_Number,
					--H_Global_Customer = @H_Global_Customer,
					--H_Customer_Ref = @H_Customer_Ref,
					--H_CSR_Email = @H_CSR_Email,
					--H_Voucher_Reference_Num = @H_Voucher_Reference_Num,
					--Job_No = @Job_No,
					--Master_BOL = @Master_BOL,
					--House_BOL = @House_BOL,
					--Master_Booking_Number = @Master_Booking_Number,
					--Global_Customer = @Global_Customer,
					--Customer_PO = @Customer_PO,
					--Customer_Ref = @Customer_Ref,
					--CSR_Email = @CSR_Email,
					--Job_Customer_Account = @Job_Customer_Account,
					--Customer_Vendor_Group = @Customer_Vendor_Group,
					--Charge_Code = @Charge_Code,
					--Sales_Invoice_Number = @Sales_Invoice_Number,
					--Voucher_Reference_Num = @Voucher_Reference_Num,
					--Tax_Classification = @Tax_Classification,
					--Actual_Date = @Actual_Date,
					--Created_by = @Created_by,
					--Original_Invoice_Amount_Entered = @Original_Invoice_Amount_Entered,
					--Original_Invoice_Amount_Accounting = @Original_Invoice_Amount_Accounting,
					--Exchange_Rate = @Exchange_Rate,
					--Open_Amount_Entered = @Open_Amount_Entered,
					--Open_Amount_Local = @Open_Amount_Local,
					--Oracle_UserID = @Oracle_UserID,
					--IsActive = @IsActive,
					--CreateadDate = @CreateadDate,
					UpdatedDate = GETDATE()                    
                WHERE
                    ID = @ID                    
                SET @ID_New = @ID
            END
            ELSE
            BEGIN
                INSERT INTO Oracle_Receivables
                (
Category,
Ledger_Name,
Source,
Period,
Currency,
Batch,
Status,
Accounting_Flexfield,
Account_Description,
Company,
GL_Account,
Product,
Resp_Center,
Location,
Interco,
Customer,
Future1,
Future2,
Entered_DR,
Entered_CR,
Entered_Net,
Accounted_DR,
Accounted_CR,
Accounted_Net,
Header_Desc,
Line_Description,
Journal_Sequence,
Accounting_Date,
Invoice_Num,
Invoice_Date,
Trading_Partner_Name,
Trading_Partner_Number,
Trading_Partner_Site,
Account_type,
H_Job_No,
H_Master_BOL,
H_House_BOL,
H_Master_Booking_Number,
H_Global_Customer,
H_Customer_Ref,
H_CSR_Email,
H_Voucher_Reference_Num,
Job_No,
Master_BOL,
House_BOL,
Master_Booking_Number,
Global_Customer,
Customer_PO,
Customer_Ref,
CSR_Email,
Job_Customer_Account,
Customer_Vendor_Group,
Charge_Code,
Sales_Invoice_Number,
Voucher_Reference_Num,
Tax_Classification,
Actual_Date,
Created_by,
Original_Invoice_Amount_Entered,
Original_Invoice_Amount_Accounting,
Exchange_Rate,
Open_Amount_Entered,
Open_Amount_Local,
Oracle_UserID,
IsActive,
CreateadDate,
UpdatedDate
                )
                VALUES
                (
@Category,
@Ledger_Name,
@Source,
@Period,
@Currency,
@Batch,
@Status,
@Accounting_Flexfield,
@Account_Description,
@Company,
@GL_Account,
@Product,
@Resp_Center,
@Location,
@Interco,
@Customer,
@Future1,
@Future2,
@Entered_DR,
@Entered_CR,
@Entered_Net,
@Accounted_DR,
@Accounted_CR,
@Accounted_Net,
@Header_Desc,
@Line_Description,
@Journal_Sequence,
@Accounting_Date,
@Invoice_Num,
@Invoice_Date,
@Trading_Partner_Name,
@Trading_Partner_Number,
@Trading_Partner_Site,
@Account_type,
@H_Job_No,
@H_Master_BOL,
@H_House_BOL,
@H_Master_Booking_Number,
@H_Global_Customer,
@H_Customer_Ref,
@H_CSR_Email,
@H_Voucher_Reference_Num,
@Job_No,
@Master_BOL,
@House_BOL,
@Master_Booking_Number,
@Global_Customer,
@Customer_PO,
@Customer_Ref,
@CSR_Email,
@Job_Customer_Account,
@Customer_Vendor_Group,
@Charge_Code,
@Sales_Invoice_Number,
@Voucher_Reference_Num,
@Tax_Classification,
@Actual_Date,
@Created_by,
@Original_Invoice_Amount_Entered,
@Original_Invoice_Amount_Accounting,
@Exchange_Rate,
@Open_Amount_Entered,
@Open_Amount_Local,
@Oracle_UserID,
@IsActive,
@CreateadDate,
@UpdatedDate
                )
                SET @ID_New = SCOPE_IDENTITY();
            END
            
            SELECT @ID_New AS ReturnValue;
        
        COMMIT TRAN
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN
        SELECT ERROR_MESSAGE() AS ReturnValue;
    END CATCH
END
GO
