SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO


/****** Object:  Stored Procedure dbo.pMAWB_Ins    Script Date: 17/10/2002 07:32:50 ******/
CREATE PROCEDURE pMAWB_Ins
-- Status do Master 
-- (A - Aguardando Confirmaçao do Usuário) 
-- (N - Recusado pelo Usuário)
-- (I  - Importado para o Atlantis) 
(
@TypeRec			char(1),
@Origin				char(3),
@AirLine_Pref			int, 
@Ser_Numb			int,
@Ship_Name			varchar(35)='',
@Ship_Adress1			varchar(35)='',
@Ship_Adress2			varchar(35)='', 
@Ship_Adress3			varchar(35)='', 
@Ship_AccNumb		varchar(14), 
@Consig_Name			varchar(	35)='', 
@Consig_Add1			varchar(35)='',
@Consig_Add2			varchar(35)='', 
@Consig_Add3			varchar(35)='', 	
@Consig_Acc_Numb		varchar(14), 	
@Iss_Car_Agent		varchar(35) = '', 	
@Iss_Car_Agent_Cit1		varchar(35) = '',
@Iss_Car_Agent_Cit2		varchar(35) = '' ,	
@IATA_Code			varchar(16)='', 	
@Agent_Acc			varchar(35)='', 	
@AirPort_Dep			varchar(35),
@AccInf1			varchar(35)='',
@AccInf2			varchar(35)='',	
@AccInf3			varchar(35)='',
@AccInf4			varchar(35)='', 	
@AccInf5			varchar(35)='', 
@To1				varchar(20),
@FirstCar			varchar(20), 
@To2				char(3)='',	 
@By1				char(2)='', 
@To3				char(3)='', 
@By2				char(3)='',
@Currency			char(3), 
@Charg_Cod			char(2)='', 
@WtVal_PPD			char(1)='', 
@WtVal_Coll			char(1)='', 
@Other_PPD			char(1)='', 
@Other_Coll			char(1)='', 
@Dec_Val_Carr			float, 
@Dec_Val_Cust			float,
@Airp_Dest			varchar(	18), 
@Flight_Numb1			varchar(9),
@Flight_Numb2			varchar(9)='',
@Month_Flight			int, 
@Amount_Ins			float=Null,
@Hand_Inf1			varchar(60) = '', 
@Hand_Inf2			varchar(60) ='', 
@Hand_Inf3			varchar(60) ='', 
@SCI				char(2)='', 
@Pieces_RCP			float, 
@Gross_Weight			float, 
@Kg_Lb			char(1) ,
@Rat_Clas_Cod			char(1),
@Com_Item_Cod		varchar(7)='', 
@Charg_Wei			float, 
@Rate_Charge			varchar(8), 
@Total_Each			float, 
@Natur_Goods1		varchar(160), 
@Natur_Goods2		varchar(160)='', 
@Natur_Goods3		varchar(160	)='', 
@Natur_Goods4		varchar(160)='', 
@Natur_Goods5		varchar(160) = '', 
@Natur_Goods6		varchar(160) = '', 
@Natur_Goods7		varchar(160) = '', 
@Natur_Goods8		varchar(160) = '', 
@Jas_SCC			char(2)='', 
@Total_Pieces			float, 
@Total_Gross_Weight		float,
@Total_All			float,
@Prep_Weig_Charg_Amount	float=Null,
@Coll_Weig_Charg_Amount	float=Null,
@Prep_Val_Charg_Amount	float=Null,
@Coll_Val_Charg_Amount	float=Null,
@Prep_Tax			float=Null, 
@Coll_Tax			float=Null, 
@Prep_Tot_OC_Agent		float=Null, 
@Coll_Tot_OC_Agent		float=Null, 
@Prep_Tot_OC_Carrier		float=Null, 
@Coll_Tot_OC_Carrier		float=Null, 
@Total_Prep			float=Null,
@Total_Coll			float=Null,
@Signat_Ship			char(35)='' , 
@Exec_On			char(18), 
@At				char(18), 
@Signat_Car			varchar(35)='', 
@Currency_Rate		float=Null, 
@CC_Charg_Dest		float=Null, 
@Charg_Dest			float=Null, 
@Total_Coll_Charg		float=Null 
)
AS
	Declare @Max as int 
	Set @Max = IsNull((Select max(IMAWB_ID) From Imp_MAWB),0) + 1 
	Insert Into 
		Imp_MAWB
	Values ( 
		@Max,
		@Ser_Numb,
		@TypeRec,
		@Origin,
		@AirLine_Pref,
		@Ship_Name,
		@Ship_Adress1,
		@Ship_Adress2,
		@Ship_Adress3,
		@Ship_AccNumb,
		@Consig_Name,
		@Consig_Add1,
		@Consig_Add2,
		@Consig_Add3,
		@Consig_Acc_Numb,
		@Iss_Car_Agent,
		@Iss_Car_Agent_Cit1,
		@Iss_Car_Agent_Cit2,
		@IATA_Code,
		@Agent_Acc,
		@AirPort_Dep,
		@AccInf1,
		@AccInf2,
		@AccInf3,
		@AccInf4,
		@AccInf5,
		@To1,
		@FirstCar,
		@To2,
		@By1,
		@To3,
		@By2,
		@Currency,
		@Charg_Cod,
		@WtVal_PPD,
		@WtVal_Coll,
		@Other_PPD,
		@Other_Coll,
		@Dec_Val_Carr,
		@Dec_Val_Cust,
		@Airp_Dest,
		@Flight_Numb1,
		@Flight_Numb2,
		@Month_Flight,
		@Amount_Ins,
		@Hand_Inf1,
		@Hand_Inf2,
		@Hand_Inf3,
		@SCI,
		@Pieces_RCP,
		@Gross_Weight,
		@Kg_Lb,
		@Rat_Clas_Cod	,
		@Com_Item_Cod,
		@Charg_Wei,
		@Rate_Charge,
		@Total_Each,
		@Natur_Goods1,
		@Natur_Goods2,
		@Natur_Goods3,
		@Natur_Goods4,
		@Natur_Goods5,
		@Natur_Goods6,
		@Natur_Goods7,
		@Natur_Goods8,
		@Jas_SCC,
		@Total_Pieces,
		@Total_Gross_Weight,
		@Total_All,
		@Prep_Weig_Charg_Amount,
		@Coll_Weig_Charg_Amount,
		@Prep_Val_Charg_Amount,
		@Coll_Val_Charg_Amount,
		@Prep_Tax,
		@Coll_Tax,
		@Prep_Tot_OC_Agent,
		@Coll_Tot_OC_Agent,
		@Prep_Tot_OC_Carrier,
		@Coll_Tot_OC_Carrier,
		@Total_Prep,
		@Total_Coll,
		@Signat_Ship,
		@Exec_On,
		@At,
		@Signat_Car,
		@Currency_Rate,
		@CC_Charg_Dest,
		@Charg_Dest,
		@Total_Coll_Charg, 
		'A'		
		) 		
	If @@Error <> 0 
		Return -1 
	Else
		Return @Max



GO
