SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO













CREATE procedure [dbo].[spContabilidadeCXA_Sel]
			@DataInicial	DAtetime,
			@DataFinal		Datetime
as

--SOMENTE ITENS DE NOTA FISCAL


SELECT REF_aCESSO Filial,emissao Data_Mov,514 Conta_Debito,97976 Conta_Credito,VLR_PGTO_NF_HEA Vlr_Pgto_Rcto_hia,458 codigo_historico,'"'+ NOTa_FISCAL +  '"' Hist_1,'"' + NOME_RAZ_SOC + '"' Hist_2,'"' + NUM_PROC_HEA + '"' Hist_3,DC_HEA DC FROM CTa_CTE_HOU_EXP_AER CTA
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HEA=NOTA_FISCAL AND REF_ACESSO_NF_HEA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
	and cd_cta_ctb_atv is null
	
--	AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,97976,VLR_PGTO_NF_MEA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MEA + '"',DC_MEA dc FROM CTa_CTE_MAS_EXP_AER CTA
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_mEA=NOTA_FISCAL AND REF_ACESSO_NF_mEA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
	and cd_cta_ctb_atv is null
--	AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,97982,VLR_PGTO_NF_HIA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HIA + '"',DC_HIA dc FROM CTa_CTE_HOU_IMP_AER Cta
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HIA=NOTA_FISCAL AND REF_ACESSO_NF_HIA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx

WHERE
	EMISSAO between @DataInicial and @DataFinal
	--AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	and cd_Cta_ctb_atv is null
UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,97982,VLR_PGTO_NF_MIA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MIA + '"',DC_MIA DC FROM CTa_CTE_MAS_IMP_AER cta
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_MIA=NOTA_FISCAL AND REF_ACESSO_NF_MIA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
	--AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	and cd_cta_ctb_atv is null

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,97999,VLR_PGTO_NF_HEM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HEM + '"',DC_HEM DC FROM CTa_CTE_HOU_EXP_MAR cta
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HEM=NOTA_FISCAL AND REF_ACESSO_NF_HEM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx

WHERE
	EMISSAO between @DataInicial and @DataFinal
--	AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	and cd_Cta_Ctb_atv is null	
UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,97999,VLR_PGTO_NF_MEM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MEM + '"',DC_MEM DC FROM CTa_CTE_MAS_EXP_MAR CTA
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_MEM=NOTA_FISCAL AND REF_ACESSO_NF_MEM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
--	AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	and cd_cta_ctb_atv is null
UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,98007,VLR_PGTO_NF_HIM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HIM + '"',DC_HIM DC FROM CTa_CTE_HOU_IMP_MAR cta
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HIM=NOTA_FISCAL AND REF_ACESSO_NF_HIM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
	--AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	and cd_Cta_ctb_Atv is null
UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,98007,VLR_PGTO_NF_MIM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MIM + '"',DC_MIM DC FROM CTa_CTE_MAS_IMP_MAR CTA
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_MIM=NOTA_FISCAL AND REF_ACESSO_NF_MIM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
	--AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	and cd_cta_ctb_atv is null
UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,98015,VLR_PGTO_NF_HIO,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HIO + '"',DC_HIO DC FROM CTa_CTE_HOU_IMP_OUT CTA
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HIO=NOTA_FISCAL AND REF_ACESSO_NF_HIO=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
--	AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	AND CD_cTA_CTB_ATV IS NULL
UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,98015,VLR_PGTO_NF_HEO,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HEO + '"',DC_HEO DC FROM CTa_CTE_HOU_EXP_OUT CTA
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HEO=NOTA_FISCAL AND REF_ACESSO_NF_HEO=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_Tx=cta.cd_Tp_Tx
WHERE
	EMISSAO between @DataInicial and @DataFinal
--	AND CD_TP_TX NOT IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')
	and CD_CTA_cTB_ATV IS NULL	


--NF de DESEMBARAÇO ADUANEIRO
union all

SELECT REF_aCESSO,emissao Data_Mov,514,cd_Cta_ctb_red,VLR_PGTO_NF_HIA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HIA + '"',DC_HIA DC FROM vwcta_Cte cta
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HIA=NOTA_FISCAL AND REF_ACESSO_NF_HIA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
jOIN Tipo_Taxa TT on TT.cd_tp_tx=cta.cd_tp_tx
JOIN CTA_cTB CTB ON CTB.CD_cta_Ctb=cd_cta_ctb_atv
WHERE
	EMISSAO between @DataInicial and @DataFinal
	and cd_Cta_ctb_atv is not null


/*
union ALL



SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_HEA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HEA + '"' FROM CTa_CTE_HOU_EXP_AER
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HEA=NOTA_FISCAL AND REF_ACESSO_NF_HEA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_MEA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MEA + '"' FROM CTa_CTE_MAS_EXP_AER
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_mEA=NOTA_FISCAL AND REF_ACESSO_NF_mEA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_HIA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HIA + '"' FROM CTa_CTE_HOU_IMP_AER
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HIA=NOTA_FISCAL AND REF_ACESSO_NF_HIA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_MIA,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MIA + '"' FROM CTa_CTE_MAS_IMP_AER
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_MIA=NOTA_FISCAL AND REF_ACESSO_NF_MIA=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_HEM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HEM + '"' FROM CTa_CTE_HOU_EXP_MAR
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HEM=NOTA_FISCAL AND REF_ACESSO_NF_HEM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv')

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_MEM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MEM + '"' FROM CTa_CTE_MAS_EXP_MAR
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_MEM=NOTA_FISCAL AND REF_ACESSO_NF_MEM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_HIM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HIM + '"' FROM CTa_CTE_HOU_IMP_MAR
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HIM=NOTA_FISCAL AND REF_ACESSO_NF_HIM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_MIM,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_MIM + '"' FROM CTa_CTE_MAS_IMP_MAR
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_MIM=NOTA_FISCAL AND REF_ACESSO_NF_MIM=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_HIO,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HIO + '"' FROM CTa_CTE_HOU_IMP_OUT
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HIO=NOTA_FISCAL AND REF_ACESSO_NF_HIO=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)

UNION ALL

SELECT REF_aCESSO,emissao Data_Mov,514,8036,VLR_PGTO_NF_HEO,458,'"'+ NOTa_FISCAL +  '"','"' + NOME_RAZ_SOC + '"','"' + NUM_PROC_HEO + '"' FROM CTa_CTE_HOU_EXP_OUT
JOIN BASE_NOTA_FISCAL NF ON NUM_NF_HEO=NOTA_FISCAL AND REF_ACESSO_NF_HEO=REF_ACESSO
jOIN PESSOA PP ON PP.CD_PES=NF.CD_PES
WHERE
	EMISSAO between @DataInicial and @DataFinal
	AND CD_TP_TX IN ('BRO','EF1','EF2','EF3','EF4','EF5','EFE','ERE','srv'
)


*/








GO
