SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[pAX_XML_Vendor_Recebido_InsUpd]
(
    @_DocumentHash VARCHAR(200),
    @AccountNum VARCHAR(200),
    @File VARCHAR(200),
    @Created_Date VARCHAR(200),
    @BidOnly VARCHAR(200),
    @Blocked VARCHAR(200),
    @CNPJCPFNum VARCHAR(200),
    @CompanyType_MX VARCHAR(200),
    @CompositionScheme_IN VARCHAR(200),
    @Currency VARCHAR(200),
    @DeliveryVendCategory VARCHAR(200),
    @Dimensao1 VARCHAR(200),
    @Dimensao2 VARCHAR(200),
    @Dimensao3 VARCHAR(200),
    @Dimensao4 VARCHAR(200),
    @Dimensao5 VARCHAR(200),
    @Dimensao6 VARCHAR(200),
    @Dimensao7 VARCHAR(200),
    @EletronicInvoice VARCHAR(200),
    @EstablishmentType VARCHAR(200),
    @FemaleOwned VARCHAR(200),
    @ForeignEntityIndicator VARCHAR(200),
    @ForeignVendor_IN VARCHAR(200),
    @GTAVendor_IN VARCHAR(200),
    @Heir_IT VARCHAR(200),
    @ICMSContributor VARCHAR(200),
    @IENum VARCHAR(200),
    @InclTax VARCHAR(200),
    @LanguageId VARCHAR(200),
    @LocallyOwned VARCHAR(200),
    @MinorityOwned VARCHAR(200),
    @ModifiedDateTime VARCHAR(200),
    @Name VARCHAR(200),
    @NameAlias VARCHAR(200),
    @NatureOfAssessee_IN VARCHAR(200),
    @NFSpecie_BR VARCHAR(200),
    @NonTaxable_BR VARCHAR(200),
    @OffsetAccountType VARCHAR(200),
    @OneTimeVendor VARCHAR(200),
    @PANStatus_IN VARCHAR(200),
    @PartyId VARCHAR(200),
    @PartyType VARCHAR(200),
    @PaymMode VARCHAR(200),
    @PaymTermId VARCHAR(200),
    @PreferentialVendor_IN VARCHAR(200),
    @PurchAmountPurchaseOrder VARCHAR(200),
    @RecId VARCHAR(200),
    @RecVersion VARCHAR(200),
    @SecondTIN VARCHAR(200),
    @ServiceCodeOnDlvAddress VARCHAR(200),
    @SmallBusiness VARCHAR(200),
    @SSIVendor_IN VARCHAR(200),
    @SubContractor_SA VARCHAR(200),
    @Tax1099NameChoice VARCHAR(200),
    @Tax1099Reports VARCHAR(200),
    @TaxGroup VARCHAR(200),
    @TaxIDType VARCHAR(200),
    @TaxWithholdCalculate VARCHAR(200),
    @TKR_CreditCard VARCHAR(200),
    @TKR_ElecInvoice VARCHAR(200),
    @TKR_RetailAlcoholic VARCHAR(200),
    @TKR_VATBizType VARCHAR(200),
    @TKR_WholesaleAlcoholic VARCHAR(200),
    @VendCategory VARCHAR(200),
    @VendConsumption_BR VARCHAR(200),
    @VendGroup VARCHAR(200),
    @W9 VARCHAR(200),
    @YourAccountNum VARCHAR(200),
    @IsPrimary1 VARCHAR(200),
    @PartyId1 VARCHAR(200),
    @RecId1 VARCHAR(200),
    @RecVersion1 VARCHAR(200),
    @Shared1 VARCHAR(200),
    @Status1 VARCHAR(200),
    @ValidFromDateTime1 VARCHAR(200),
    @ValidToDateTime1 VARCHAR(200),
    @AddressRecId2 VARCHAR(200),
    @PartyAddressRelationshipRecId2 VARCHAR(200),
    @RecId2 VARCHAR(200),
    @RecVersion2 VARCHAR(200),
    @RefCompanyId2 VARCHAR(200),
    @Address3 VARCHAR(200),
    @AddressComplement3 VARCHAR(200),
    @AddressNumber3 VARCHAR(200),
    @AddrRecId3 VARCHAR(200),
    @AddrTableId3 VARCHAR(200),
    @City3 VARCHAR(200),
    @CountryRegionId3 VARCHAR(200),
    @DeliveryCustVendCategory3 VARCHAR(200),
    @ExciseType_IN3 VARCHAR(200),
    @RecId3 VARCHAR(200),
    @RecVersion3 VARCHAR(200),
    @ShipCarrierBlindShipment3 VARCHAR(200),
    @ShipCarrierResidential3 VARCHAR(200),
    @State3 VARCHAR(200),
    @Street3 VARCHAR(500),
    @TimeZone3 VARCHAR(200),
    @type3 VARCHAR(200),
    @ZipCode3 VARCHAR(200),
    @DistrictName3 VARCHAR(200),
    @OffsetAccount VARCHAR(200),
    @City4 VARCHAR(200),
    @CountryRegionId4 VARCHAR(200),
    @DeliveryCustVendCategory4 VARCHAR(200),
    @ExciseType_IN4 VARCHAR(200),
    @Name4 VARCHAR(200),
    @RecId4 VARCHAR(200),
    @RecVersion4 VARCHAR(200),
    @ShipCarrierBlindShipment4 VARCHAR(200),
    @State4 VARCHAR(200),
    @ShipCarrierResidential4 VARCHAR(200),
    @Street4 VARCHAR(500),
    @type4 VARCHAR(200),
    @ZipCode4 VARCHAR(200),
    @AddressRecId3 VARCHAR(200),
    @PartyAddressRelationshipRecId3 VARCHAR(200),
    @AddressComplement4 VARCHAR(200),
    @AddressNumber4 VARCHAR(200),
    @AddrRecId4 VARCHAR(200),
    @AddrTableId4 VARCHAR(200),
    @Address4 VARCHAR(200),
    @RefCompanyId3 VARCHAR(200),
    @ValidToDateTime2 VARCHAR(200),
    @ValidFromDateTime2 VARCHAR(200),
    @Status2 VARCHAR(200),
    @Shared2 VARCHAR(200),
    @AddressComplement VARCHAR(200),
    @City VARCHAR(200),
    @CountryRegionId VARCHAR(200),
    @DeliveryVendCNPJCPFNum VARCHAR(200),
    @DeliveryVendIENum VARCHAR(200),
    @PANNumber_IN VARCHAR(200),
    @PartyId2 VARCHAR(200),
    @IsPrimary2 VARCHAR(200),
    @ZipCode VARCHAR(200),
    @TKR_Name VARCHAR(200),
    @TKR_Address VARCHAR(200),
    @Street VARCHAR(500),
    @Address VARCHAR(200),
    @State VARCHAR(200),
    @AddressNumber VARCHAR(200),
    @TimeZone4 VARCHAR(200),
    @BankAccount VARCHAR(200),
    @DistrictName VARCHAR(200),
    @TaxWithholdGroup VARCHAR(200),
    @DistrictName4 VARCHAR(200),
    @DeliveryCustVendCNPJCPFNum4 VARCHAR(200),
    @DeliveryCustVendIENum4 VARCHAR(200),
    @County VARCHAR(200),
    @County4 VARCHAR(200),
    @Dt_Envio_ATL DATETIME,
    @Dt_Atualiza_ATL DATETIME,
    @NameKana VARCHAR(200),
    @ContactPersonId VARCHAR(200),
    @Email VARCHAR(200),
    @Phone VARCHAR(200),
    @County3 VARCHAR(200),
    @Name3 VARCHAR(200),
    @CellularPhone VARCHAR(200),
    @IsPrimary4 VARCHAR(200),
    @PartyId4 VARCHAR(200),
    @Shared4 VARCHAR(200),
    @Status4 VARCHAR(200),
    @ValidFromDateTime4 VARCHAR(200),
    @ValidToDateTime4 VARCHAR(200),
    @AddressRecId5 VARCHAR(200),
    @PartyAddressRelationshipRecId5 VARCHAR(200),
    @RecId5 VARCHAR(200),
    @RecVersion5 VARCHAR(200),
    @RefCompanyId5 VARCHAR(200),
    @Address6 VARCHAR(200),
    @AddressComplement6 VARCHAR(200),
    @AddressNumber6 VARCHAR(200),
    @AddrRecId6 VARCHAR(200),
    @AddrTableId6 VARCHAR(200),
    @City6 VARCHAR(200),
    @CountryRegionId6 VARCHAR(200),
    @DeliveryCustVendCategory6 VARCHAR(200),
    @ExciseType_IN6 VARCHAR(200),
    @RecId6 VARCHAR(200),
    @RecVersion6 VARCHAR(200),
    @ShipCarrierBlindShipment6 VARCHAR(200),
    @ShipCarrierResidential6 VARCHAR(200),
    @State6 VARCHAR(200),
    @Street6 VARCHAR(200),
    @TimeZone6 VARCHAR(200),
    @type6 VARCHAR(200),
    @ZipCode6 VARCHAR(200),
    @CustStatGroupId VARCHAR(200),
    @InvoiceModel_BR VARCHAR(200),
    @numberSequenceGroup VARCHAR(200),
    @VendInvoiceType VARCHAR(200),
    @CCMnUM VARCHAR(200),
    @PhoneLocal VARCHAR(200),
    @DistrictName6 VARCHAR(200),
    @TeleFax VARCHAR(200),
    @Dimensao8 VARCHAR(200),
    @URL VARCHAR(200),
    @Pager VARCHAR(200),
    @BirthDate VARCHAR(200),
    @PaymSpec VARCHAR(200),
    @OrgId VARCHAR(200),
    @AccountStatement VARCHAR(200),
    @CreatedDateTime VARCHAR(200),
    @CustCategory VARCHAR(200),
    @CustFinalUser VARCHAR(200),
    @CustGroup VARCHAR(200),
    @DeliveryCustCategory VARCHAR(200),
    @ForeignCustomer_IN VARCHAR(200),
    @GiroType VARCHAR(200),
    @GiroTypeAccountStatement VARCHAR(200),
    @GiroTypeCollectionletter VARCHAR(200),
    @GiroTypeFreeTextInvoice VARCHAR(200),
    @GiroTypeInterestNote VARCHAR(200),
    @GiroTypeProjInvoice VARCHAR(200),
    @InterCompanyAllowIndirectCreation VARCHAR(200),
    @InterCompanyAutoCreateOrders VARCHAR(200),
    @InterCompanyDirectDelivery VARCHAR(200),
    @InvoiceAddress VARCHAR(200),
    @MandatoryCreditLimit VARCHAR(200),
    @OneTimeCustomer VARCHAR(200),
    @PreferentialCustomer_IN VARCHAR(200),
    @RFIDCaseTagging VARCHAR(200),
    @RFIDItemTagging VARCHAR(200),
    @RFIDPalletTagging VARCHAR(200),
    @ShipCarrierBlindShipment VARCHAR(200),
    @ShipCarrierFuelSurcharge VARCHAR(200),
    @Suframa VARCHAR(200),
    @SuframaPISCOFINS VARCHAR(200),
    @TaxWithholdCalculate_IN VARCHAR(200),
    @VendItemGroupId VARCHAR(200),
    @Tax1099RegNum VARCHAR(200),
    @DBA VARCHAR(200),
    @CustAccount VARCHAR(200),
    @Phone3 VARCHAR(200),
    @Email3 VARCHAR(200),
    @BankCentralBankPurposeCode VARCHAR(200),
    @ResidenceForeignCountryRegionId VARCHAR(200),
    @IsPrimary7 VARCHAR(200),
    @PartyId7 VARCHAR(200),
    @RecId7 VARCHAR(200),
    @RecVersion7 VARCHAR(200),
    @Shared7 VARCHAR(200),
    @Status7 VARCHAR(200),
    @ValidFromDateTime7 VARCHAR(200),
    @ValidToDateTime7 VARCHAR(200),
    @AddressRecId8 VARCHAR(200),
    @PartyAddressRelationshipRecId8 VARCHAR(200),
    @RecId8 VARCHAR(200),
    @RecVersion8 VARCHAR(200),
    @RefCompanyId8 VARCHAR(200),
    @Address9 VARCHAR(200),
    @AddressComplement9 VARCHAR(200),
    @AddressNumber9 VARCHAR(200),
    @AddrRecId9 VARCHAR(200),
    @AddrTableId9 VARCHAR(200),
    @City9 VARCHAR(200),
    @CountryRegionId9 VARCHAR(200),
    @DeliveryCustVendCategory9 VARCHAR(200),
    @DistrictName9 VARCHAR(200),
    @ExciseType_IN9 VARCHAR(200),
    @RecId9 VARCHAR(200),
    @RecVersion9 VARCHAR(200),
    @ShipCarrierBlindShipment9 VARCHAR(200),
    @ShipCarrierResidential9 VARCHAR(200),
    @State9 VARCHAR(200),
    @Street9 VARCHAR(200),
    @type9 VARCHAR(200),
    @ZipCode9 VARCHAR(200),
    @IsPrimary10 VARCHAR(200),
    @PartyId10 VARCHAR(200),
    @RecId10 VARCHAR(200),
    @RecVersion10 VARCHAR(200),
    @Shared10 VARCHAR(200),
    @Status10 VARCHAR(200),
    @ValidFromDateTime10 VARCHAR(200),
    @ValidToDateTime10 VARCHAR(200),
    @AddressRecId11 VARCHAR(200),
    @PartyAddressRelationshipRecId11 VARCHAR(200),
    @RecId11 VARCHAR(200),
    @RecVersion11 VARCHAR(200),
    @RefCompanyId11 VARCHAR(200),
    @Address12 VARCHAR(200),
    @AddressComplement12 VARCHAR(200),
    @AddressNumber12 VARCHAR(200),
    @AddrRecId12 VARCHAR(200),
    @AddrTableId12 VARCHAR(200),
    @City12 VARCHAR(200),
    @CountryRegionId12 VARCHAR(200),
    @DeliveryCustVendCategory12 VARCHAR(200),
    @DistrictName12 VARCHAR(200),
    @ExciseType_IN12 VARCHAR(200),
    @RecId12 VARCHAR(200),
    @RecVersion12 VARCHAR(200),
    @ShipCarrierBlindShipment12 VARCHAR(200),
    @ShipCarrierResidential12 VARCHAR(200),
    @State12 VARCHAR(200),
    @Street12 VARCHAR(200),
    @type12 VARCHAR(200),
    @ZipCode12 VARCHAR(200),
    @IsPrimary13 VARCHAR(200),
    @PartyId13 VARCHAR(200),
    @RecId13 VARCHAR(200),
    @RecVersion13 VARCHAR(200),
    @Shared13 VARCHAR(200),
    @Status13 VARCHAR(200),
    @ValidFromDateTime13 VARCHAR(200),
    @ValidToDateTime13 VARCHAR(200),
    @AddressRecId14 VARCHAR(200),
    @PartyAddressRelationshipRecId14 VARCHAR(200),
    @RecId14 VARCHAR(200),
    @RecVersion14 VARCHAR(200),
    @RefCompanyId14 VARCHAR(200),
    @Address15 VARCHAR(200),
    @AddressComplement15 VARCHAR(200),
    @AddressNumber15 VARCHAR(200),
    @AddrRecId15 VARCHAR(200),
    @AddrTableId15 VARCHAR(200),
    @City15 VARCHAR(200),
    @CountryRegionId15 VARCHAR(200),
    @DeliveryCustVendCategory15 VARCHAR(200),
    @DistrictName15 VARCHAR(200),
    @ExciseType_IN15 VARCHAR(200),
    @RecId15 VARCHAR(200),
    @RecVersion15 VARCHAR(200),
    @ShipCarrierBlindShipment15 VARCHAR(200),
    @ShipCarrierResidential15 VARCHAR(200),
    @State15 VARCHAR(200),
    @Street15 VARCHAR(200),
    @type15 VARCHAR(200),
    @ZipCode15 VARCHAR(200),
    @IsPrimary16 VARCHAR(200),
    @PartyId16 VARCHAR(200),
    @RecId16 VARCHAR(200),
    @RecVersion16 VARCHAR(200),
    @Shared16 VARCHAR(200),
    @Status16 VARCHAR(200),
    @ValidFromDateTime16 VARCHAR(200),
    @ValidToDateTime16 VARCHAR(200),
    @AddressRecId17 VARCHAR(200),
    @PartyAddressRelationshipRecId17 VARCHAR(200),
    @RecId17 VARCHAR(200),
    @RecVersion17 VARCHAR(200),
    @RefCompanyId17 VARCHAR(200),
    @Address18 VARCHAR(200),
    @AddressComplement18 VARCHAR(200),
    @AddressNumber18 VARCHAR(200),
    @AddrRecId18 VARCHAR(200),
    @AddrTableId18 VARCHAR(200),
    @City18 VARCHAR(200),
    @CountryRegionId18 VARCHAR(200),
    @DeliveryCustVendCategory18 VARCHAR(200),
    @DistrictName18 VARCHAR(200),
    @ExciseType_IN18 VARCHAR(200),
    @RecId18 VARCHAR(200),
    @RecVersion18 VARCHAR(200),
    @ShipCarrierBlindShipment18 VARCHAR(200),
    @ShipCarrierResidential18 VARCHAR(200),
    @State18 VARCHAR(200),
    @Street18 VARCHAR(200),
    @type18 VARCHAR(200),
    @ZipCode18 VARCHAR(200),
    @IsPrimary19 VARCHAR(200),
    @PartyId19 VARCHAR(200),
    @RecId19 VARCHAR(200),
    @RecVersion19 VARCHAR(200),
    @Shared19 VARCHAR(200),
    @Status19 VARCHAR(200),
    @ValidFromDateTime19 VARCHAR(200),
    @ValidToDateTime19 VARCHAR(200),
    @AddressRecId20 VARCHAR(200),
    @PartyAddressRelationshipRecId20 VARCHAR(200),
    @RecId20 VARCHAR(200),
    @RecVersion20 VARCHAR(200),
    @RefCompanyId20 VARCHAR(200),
    @Address21 VARCHAR(200),
    @AddressComplement21 VARCHAR(200),
    @AddressNumber21 VARCHAR(200),
    @AddrRecId21 VARCHAR(200),
    @AddrTableId21 VARCHAR(200),
    @City21 VARCHAR(200),
    @CountryRegionId21 VARCHAR(200),
    @DeliveryCustVendCategory21 VARCHAR(200),
    @DistrictName21 VARCHAR(200),
    @ExciseType_IN21 VARCHAR(200),
    @RecId21 VARCHAR(200),
    @RecVersion21 VARCHAR(200),
    @ShipCarrierBlindShipment21 VARCHAR(200),
    @ShipCarrierResidential21 VARCHAR(200),
    @State21 VARCHAR(200),
    @Street21 VARCHAR(200),
    @type21 VARCHAR(200),
    @ZipCode21 VARCHAR(200),
    @IsPrimary22 VARCHAR(200),
    @PartyId22 VARCHAR(200),
    @RecId22 VARCHAR(200),
    @RecVersion22 VARCHAR(200),
    @Shared22 VARCHAR(200),
    @Status22 VARCHAR(200),
    @ValidFromDateTime22 VARCHAR(200),
    @ValidToDateTime22 VARCHAR(200),
    @AddressRecId23 VARCHAR(200),
    @PartyAddressRelationshipRecId23 VARCHAR(200),
    @RecId23 VARCHAR(200),
    @RecVersion23 VARCHAR(200),
    @RefCompanyId23 VARCHAR(200),
    @Address24 VARCHAR(200),
    @AddressComplement24 VARCHAR(200),
    @AddressNumber24 VARCHAR(200),
    @AddrRecId24 VARCHAR(200),
    @AddrTableId24 VARCHAR(200),
    @City24 VARCHAR(200),
    @CountryRegionId24 VARCHAR(200),
    @DeliveryCustVendCategory24 VARCHAR(200),
    @DistrictName24 VARCHAR(200),
    @ExciseType_IN24 VARCHAR(200),
    @RecId24 VARCHAR(200),
    @RecVersion24 VARCHAR(200),
    @ShipCarrierBlindShipment24 VARCHAR(200),
    @ShipCarrierResidential24 VARCHAR(200),
    @State24 VARCHAR(200),
    @Street24 VARCHAR(200),
    @type24 VARCHAR(200),
    @ZipCode24 VARCHAR(200),
    @IsPrimary25 VARCHAR(200),
    @PartyId25 VARCHAR(200),
    @RecId25 VARCHAR(200),
    @RecVersion25 VARCHAR(200),
    @Shared25 VARCHAR(200),
    @Status25 VARCHAR(200),
    @ValidFromDateTime25 VARCHAR(200),
    @ValidToDateTime25 VARCHAR(200),
    @AddressRecId26 VARCHAR(200),
    @PartyAddressRelationshipRecId26 VARCHAR(200),
    @RecId26 VARCHAR(200),
    @RecVersion26 VARCHAR(200),
    @RefCompanyId26 VARCHAR(200),
    @Address27 VARCHAR(200),
    @AddressComplement27 VARCHAR(200),
    @AddressNumber27 VARCHAR(200),
    @AddrRecId27 VARCHAR(200),
    @AddrTableId27 VARCHAR(200),
    @City27 VARCHAR(200),
    @CountryRegionId27 VARCHAR(200),
    @DeliveryCustVendCategory27 VARCHAR(200),
    @DistrictName27 VARCHAR(200),
    @ExciseType_IN27 VARCHAR(200),
    @RecId27 VARCHAR(200),
    @RecVersion27 VARCHAR(200),
    @ShipCarrierBlindShipment27 VARCHAR(200),
    @ShipCarrierResidential27 VARCHAR(200),
    @State27 VARCHAR(200),
    @Street27 VARCHAR(200),
    @type27 VARCHAR(200),
    @ZipCode27 VARCHAR(200),
    @IsPrimary28 VARCHAR(200),
    @PartyId28 VARCHAR(200),
    @RecId28 VARCHAR(200),
    @RecVersion28 VARCHAR(200),
    @Shared28 VARCHAR(200),
    @Status28 VARCHAR(200),
    @ValidFromDateTime28 VARCHAR(200),
    @ValidToDateTime28 VARCHAR(200),
    @AddressRecId29 VARCHAR(200),
    @PartyAddressRelationshipRecId29 VARCHAR(200),
    @RecId29 VARCHAR(200),
    @RecVersion29 VARCHAR(200),
    @RefCompanyId29 VARCHAR(200),
    @Address30 VARCHAR(200),
    @AddressComplement30 VARCHAR(200),
    @AddressNumber30 VARCHAR(200),
    @AddrRecId30 VARCHAR(200),
    @AddrTableId30 VARCHAR(200),
    @City30 VARCHAR(200),
    @CountryRegionId30 VARCHAR(200),
    @DeliveryCustVendCategory30 VARCHAR(200),
    @DistrictName30 VARCHAR(200),
    @ExciseType_IN30 VARCHAR(200),
    @RecId30 VARCHAR(200),
    @RecVersion30 VARCHAR(200),
    @ShipCarrierBlindShipment30 VARCHAR(200),
    @ShipCarrierResidential30 VARCHAR(200),
    @State30 VARCHAR(200),
    @Street30 VARCHAR(200),
    @type30 VARCHAR(200),
    @ZipCode30 VARCHAR(200),
    @IsPrimary31 VARCHAR(200),
    @PartyId31 VARCHAR(200),
    @RecId31 VARCHAR(200),
    @RecVersion31 VARCHAR(200),
    @Shared31 VARCHAR(200),
    @Status31 VARCHAR(200),
    @ValidFromDateTime31 VARCHAR(200),
    @ValidToDateTime31 VARCHAR(200),
    @AddressRecId32 VARCHAR(200),
    @PartyAddressRelationshipRecId32 VARCHAR(200),
    @RecId32 VARCHAR(200),
    @RecVersion32 VARCHAR(200),
    @RefCompanyId32 VARCHAR(200),
    @Address33 VARCHAR(200),
    @AddressComplement33 VARCHAR(200),
    @AddressNumber33 VARCHAR(200),
    @AddrRecId33 VARCHAR(200),
    @AddrTableId33 VARCHAR(200),
    @City33 VARCHAR(200),
    @CountryRegionId33 VARCHAR(200),
    @DeliveryCustVendCategory33 VARCHAR(200),
    @DistrictName33 VARCHAR(200),
    @ExciseType_IN33 VARCHAR(200),
    @RecId33 VARCHAR(200),
    @RecVersion33 VARCHAR(200),
    @ShipCarrierBlindShipment33 VARCHAR(200),
    @ShipCarrierResidential33 VARCHAR(200),
    @State33 VARCHAR(200),
    @Street33 VARCHAR(200),
    @type33 VARCHAR(200),
    @ZipCode33 VARCHAR(200),
    @IsPrimary34 VARCHAR(200),
    @PartyId34 VARCHAR(200),
    @RecId34 VARCHAR(200),
    @RecVersion34 VARCHAR(200),
    @Shared34 VARCHAR(200),
    @Status34 VARCHAR(200),
    @ValidFromDateTime34 VARCHAR(200),
    @ValidToDateTime34 VARCHAR(200),
    @AddressRecId35 VARCHAR(200),
    @PartyAddressRelationshipRecId35 VARCHAR(200),
    @RecId35 VARCHAR(200),
    @RecVersion35 VARCHAR(200),
    @RefCompanyId35 VARCHAR(200),
    @Address36 VARCHAR(200),
    @AddressComplement36 VARCHAR(200),
    @AddressNumber36 VARCHAR(200),
    @AddrRecId36 VARCHAR(200),
    @AddrTableId36 VARCHAR(200),
    @City36 VARCHAR(200),
    @CountryRegionId36 VARCHAR(200),
    @DeliveryCustVendCategory36 VARCHAR(200),
    @DistrictName36 VARCHAR(200),
    @ExciseType_IN36 VARCHAR(200),
    @RecId36 VARCHAR(200),
    @RecVersion36 VARCHAR(200),
    @ShipCarrierBlindShipment36 VARCHAR(200),
    @ShipCarrierResidential36 VARCHAR(200),
    @State36 VARCHAR(200),
    @Street36 VARCHAR(200),
    @type36 VARCHAR(200),
    @ZipCode36 VARCHAR(200),
    @IsPrimary37 VARCHAR(200),
    @PartyId37 VARCHAR(200),
    @RecId37 VARCHAR(200),
    @RecVersion37 VARCHAR(200),
    @Shared37 VARCHAR(200),
    @Status37 VARCHAR(200),
    @ValidFromDateTime37 VARCHAR(200),
    @ValidToDateTime37 VARCHAR(200),
    @AddressRecId38 VARCHAR(200),
    @PartyAddressRelationshipRecId38 VARCHAR(200),
    @RecId38 VARCHAR(200),
    @RecVersion38 VARCHAR(200),
    @RefCompanyId38 VARCHAR(200),
    @Address39 VARCHAR(200),
    @AddressComplement39 VARCHAR(200),
    @AddressNumber39 VARCHAR(200),
    @AddrRecId39 VARCHAR(200),
    @AddrTableId39 VARCHAR(200),
    @City39 VARCHAR(200),
    @CountryRegionId39 VARCHAR(200),
    @DeliveryCustVendCategory39 VARCHAR(200),
    @DistrictName39 VARCHAR(200),
    @ExciseType_IN39 VARCHAR(200),
    @RecId39 VARCHAR(200),
    @RecVersion39 VARCHAR(200),
    @ShipCarrierBlindShipment39 VARCHAR(200),
    @ShipCarrierResidential39 VARCHAR(200),
    @State39 VARCHAR(200),
    @Street39 VARCHAR(200),
    @type39 VARCHAR(200),
    @ZipCode39 VARCHAR(200),
    @IsPrimary40 VARCHAR(200),
    @PartyId40 VARCHAR(200),
    @RecId40 VARCHAR(200),
    @RecVersion40 VARCHAR(200),
    @Shared40 VARCHAR(200),
    @Status40 VARCHAR(200),
    @ValidFromDateTime40 VARCHAR(200),
    @ValidToDateTime40 VARCHAR(200),
    @AddressRecId41 VARCHAR(200),
    @PartyAddressRelationshipRecId41 VARCHAR(200),
    @RecId41 VARCHAR(200),
    @RecVersion41 VARCHAR(200),
    @RefCompanyId41 VARCHAR(200),
    @Address42 VARCHAR(200),
    @AddressComplement42 VARCHAR(200),
    @AddressNumber42 VARCHAR(200),
    @AddrRecId42 VARCHAR(200),
    @AddrTableId42 VARCHAR(200),
    @City42 VARCHAR(200),
    @CountryRegionId42 VARCHAR(200),
    @DeliveryCustVendCategory42 VARCHAR(200),
    @DistrictName42 VARCHAR(200),
    @ExciseType_IN42 VARCHAR(200),
    @RecId42 VARCHAR(200),
    @RecVersion42 VARCHAR(200),
    @ShipCarrierBlindShipment42 VARCHAR(200),
    @ShipCarrierResidential42 VARCHAR(200),
    @State42 VARCHAR(200),
    @Street42 VARCHAR(200),
    @type42 VARCHAR(200),
    @ZipCode42 VARCHAR(200),
    @IsPrimary43 VARCHAR(200),
    @PartyId43 VARCHAR(200),
    @RecId43 VARCHAR(200),
    @RecVersion43 VARCHAR(200),
    @Shared43 VARCHAR(200),
    @Status43 VARCHAR(200),
    @ValidFromDateTime43 VARCHAR(200),
    @ValidToDateTime43 VARCHAR(200),
    @AddressRecId44 VARCHAR(200),
    @PartyAddressRelationshipRecId44 VARCHAR(200),
    @RecId44 VARCHAR(200),
    @RecVersion44 VARCHAR(200),
    @RefCompanyId44 VARCHAR(200),
    @Address45 VARCHAR(200),
    @AddressComplement45 VARCHAR(200),
    @AddressNumber45 VARCHAR(200),
    @AddrRecId45 VARCHAR(200),
    @AddrTableId45 VARCHAR(200),
    @City45 VARCHAR(200),
    @CountryRegionId45 VARCHAR(200),
    @DeliveryCustVendCategory45 VARCHAR(200),
    @DistrictName45 VARCHAR(200),
    @ExciseType_IN45 VARCHAR(200),
    @RecId45 VARCHAR(200),
    @RecVersion45 VARCHAR(200),
    @ShipCarrierBlindShipment45 VARCHAR(200),
    @ShipCarrierResidential45 VARCHAR(200),
    @State45 VARCHAR(200),
    @Street45 VARCHAR(200),
    @type45 VARCHAR(200),
    @ZipCode45 VARCHAR(200),
    @IsPrimary46 VARCHAR(200),
    @PartyId46 VARCHAR(200),
    @RecId46 VARCHAR(200),
    @RecVersion46 VARCHAR(200),
    @Shared46 VARCHAR(200),
    @Status46 VARCHAR(200),
    @ValidFromDateTime46 VARCHAR(200),
    @ValidToDateTime46 VARCHAR(200),
    @AddressRecId47 VARCHAR(200),
    @PartyAddressRelationshipRecId47 VARCHAR(200),
    @RecId47 VARCHAR(200),
    @RecVersion47 VARCHAR(200),
    @RefCompanyId47 VARCHAR(200),
    @Address48 VARCHAR(200),
    @AddressComplement48 VARCHAR(200),
    @AddressNumber48 VARCHAR(200),
    @AddrRecId48 VARCHAR(200),
    @AddrTableId48 VARCHAR(200),
    @City48 VARCHAR(200),
    @CountryRegionId48 VARCHAR(200),
    @DeliveryCustVendCategory48 VARCHAR(200),
    @DistrictName48 VARCHAR(200),
    @ExciseType_IN48 VARCHAR(200),
    @RecId48 VARCHAR(200),
    @RecVersion48 VARCHAR(200),
    @ShipCarrierBlindShipment48 VARCHAR(200),
    @ShipCarrierResidential48 VARCHAR(200),
    @State48 VARCHAR(200),
    @Street48 VARCHAR(200),
    @type48 VARCHAR(200),
    @ZipCode48 VARCHAR(200),
    @IsPrimary49 VARCHAR(200),
    @PartyId49 VARCHAR(200),
    @RecId49 VARCHAR(200),
    @RecVersion49 VARCHAR(200),
    @Shared49 VARCHAR(200),
    @Status49 VARCHAR(200),
    @ValidFromDateTime49 VARCHAR(200),
    @ValidToDateTime49 VARCHAR(200),
    @AddressRecId50 VARCHAR(200),
    @PartyAddressRelationshipRecId50 VARCHAR(200),
    @RecId50 VARCHAR(200),
    @RecVersion50 VARCHAR(200),
    @RefCompanyId50 VARCHAR(200),
    @VATNum VARCHAR(200)
)
AS
BEGIN
    BEGIN TRY
        BEGIN TRAN
            DECLARE @ID_New AS BIGINT;
                      

            IF EXISTS(SELECT AccountNum FROM AX_XML_Vendor_Recebido WHERE AccountNum = @AccountNum)
            BEGIN
                UPDATE 
                    AX_XML_Vendor_Recebido
                SET
     --               _DocumentHash = @_DocumentHash,        
					--[File] = @File,
					--[Created Date] = @Created_Date,
					--BidOnly = @BidOnly,
					Blocked = @Blocked,
					CNPJCPFNum = @CNPJCPFNum,
					--CompanyType_MX = @CompanyType_MX,
					--CompositionScheme_IN = @CompositionScheme_IN,
					--Currency = @Currency,
					--DeliveryVendCategory = @DeliveryVendCategory,
					Dimensao1 = @Dimensao1,
					Dimensao2 = @Dimensao2,
					Dimensao3 = @Dimensao3,
					Dimensao4 = @Dimensao4,
					Dimensao5 = @Dimensao5,
					Dimensao6 = @Dimensao6,
					Dimensao7 = @Dimensao7,
					--EletronicInvoice = @EletronicInvoice,
					--EstablishmentType = @EstablishmentType,
					--FemaleOwned = @FemaleOwned,
					--ForeignEntityIndicator = @ForeignEntityIndicator,
					--ForeignVendor_IN = @ForeignVendor_IN,
					--GTAVendor_IN = @GTAVendor_IN,
					--Heir_IT = @Heir_IT,
					--ICMSContributor = @ICMSContributor,
					IENum = @IENum,
					--InclTax = @InclTax,
					--LanguageId = @LanguageId,
					--LocallyOwned = @LocallyOwned,
					--MinorityOwned = @MinorityOwned,
					--ModifiedDateTime = @ModifiedDateTime,
					[Name] = @Name,
					NameAlias = @NameAlias,
					--NatureOfAssessee_IN = @NatureOfAssessee_IN,
					--NFSpecie_BR = @NFSpecie_BR,
					--NonTaxable_BR = @NonTaxable_BR,
					--OffsetAccountType = @OffsetAccountType,
					--OneTimeVendor = @OneTimeVendor,
					--PANStatus_IN = @PANStatus_IN,
					--PartyId = @PartyId,
					--PartyType = @PartyType,
					--PaymMode = @PaymMode,
					--PaymTermId = @PaymTermId,
					--PreferentialVendor_IN = @PreferentialVendor_IN,
					--PurchAmountPurchaseOrder = @PurchAmountPurchaseOrder,
					--RecId = @RecId,
					--RecVersion = @RecVersion,
					--SecondTIN = @SecondTIN,
					--ServiceCodeOnDlvAddress = @ServiceCodeOnDlvAddress,
					--SmallBusiness = @SmallBusiness,
					--SSIVendor_IN = @SSIVendor_IN,
					--SubContractor_SA = @SubContractor_SA,
					--Tax1099NameChoice = @Tax1099NameChoice,
					--Tax1099Reports = @Tax1099Reports,
					TaxGroup = @TaxGroup,
					--TaxIDType = @TaxIDType,
					--TaxWithholdCalculate = @TaxWithholdCalculate,
					--TKR_CreditCard = @TKR_CreditCard,
					--TKR_ElecInvoice = @TKR_ElecInvoice,
					--TKR_RetailAlcoholic = @TKR_RetailAlcoholic,
					--TKR_VATBizType = @TKR_VATBizType,
					--TKR_WholesaleAlcoholic = @TKR_WholesaleAlcoholic,
					--VendCategory = @VendCategory,
					--VendConsumption_BR = @VendConsumption_BR,
					VendGroup = @VendGroup,
					--W9 = @W9,
					YourAccountNum = @YourAccountNum,
					--IsPrimary1 = @IsPrimary1,
					--PartyId1 = @PartyId1,
					--RecId1 = @RecId1,
					--RecVersion1 = @RecVersion1,
					--Shared1 = @Shared1,
					--Status1 = @Status1,
					--ValidFromDateTime1 = @ValidFromDateTime1,
					--ValidToDateTime1 = @ValidToDateTime1,
					--AddressRecId2 = @AddressRecId2,
					--PartyAddressRelationshipRecId2 = @PartyAddressRelationshipRecId2,
					--RecId2 = @RecId2,
					--RecVersion2 = @RecVersion2,
					--RefCompanyId2 = @RefCompanyId2,
					--Address3 = @Address3,
					--AddressComplement3 = @AddressComplement3,
					--AddressNumber3 = @AddressNumber3,
					--AddrRecId3 = @AddrRecId3,
					--AddrTableId3 = @AddrTableId3,
					--City3 = @City3,
					--CountryRegionId3 = @CountryRegionId3,
					--DeliveryCustVendCategory3 = @DeliveryCustVendCategory3,
					--ExciseType_IN3 = @ExciseType_IN3,
					--RecId3 = @RecId3,
					--RecVersion3 = @RecVersion3,
					--ShipCarrierBlindShipment3 = @ShipCarrierBlindShipment3,
					--ShipCarrierResidential3 = @ShipCarrierResidential3,
					--State3 = @State3,
					--Street3 = @Street3,
					--TimeZone3 = @TimeZone3,
					--type3 = @type3,
					--ZipCode3 = @ZipCode3,
					--DistrictName3 = @DistrictName3,
					--OffsetAccount = @OffsetAccount,
					--City4 = @City4,
					--CountryRegionId4 = @CountryRegionId4,
					--DeliveryCustVendCategory4 = @DeliveryCustVendCategory4,
					--ExciseType_IN4 = @ExciseType_IN4,
					--Name4 = @Name4,
					--RecId4 = @RecId4,
					--RecVersion4 = @RecVersion4,
					--ShipCarrierBlindShipment4 = @ShipCarrierBlindShipment4,
					--State4 = @State4,
					--ShipCarrierResidential4 = @ShipCarrierResidential4,
					--Street4 = @Street4,
					--type4 = @type4,
					--ZipCode4 = @ZipCode4,
					--AddressRecId3 = @AddressRecId3,
					--PartyAddressRelationshipRecId3 = @PartyAddressRelationshipRecId3,
					--AddressComplement4 = @AddressComplement4,
					--AddressNumber4 = @AddressNumber4,
					--AddrRecId4 = @AddrRecId4,
					--AddrTableId4 = @AddrTableId4,
					--Address4 = @Address4,
					--RefCompanyId3 = @RefCompanyId3,
					--ValidToDateTime2 = @ValidToDateTime2,
					--ValidFromDateTime2 = @ValidFromDateTime2,
					--Status2 = @Status2,
					--Shared2 = @Shared2,
					--AddressComplement = @AddressComplement,
					--City = @City,
					--CountryRegionId = @CountryRegionId,
					--DeliveryVendCNPJCPFNum = @DeliveryVendCNPJCPFNum,
					--DeliveryVendIENum = @DeliveryVendIENum,
					--PANNumber_IN = @PANNumber_IN,
					--PartyId2 = @PartyId2,
					--IsPrimary2 = @IsPrimary2,
					--ZipCode = @ZipCode,
					--TKR_Name = @TKR_Name,
					--TKR_Address = @TKR_Address,
					--Street = @Street,
					--[Address] = @Address,
					--[State] = @State,
					--AddressNumber = @AddressNumber,
					--TimeZone4 = @TimeZone4,
					--BankAccount = @BankAccount,
					--DistrictName = @DistrictName,
					--TaxWithholdGroup = @TaxWithholdGroup,
					--DistrictName4 = @DistrictName4,
					--DeliveryCustVendCNPJCPFNum4 = @DeliveryCustVendCNPJCPFNum4,
					--DeliveryCustVendIENum4 = @DeliveryCustVendIENum4,
					--County = @County,
					--County4 = @County4,
					Dt_Envio_ATL = @Dt_Envio_ATL,
					Dt_Atualiza_ATL = @Dt_Atualiza_ATL,
					--NameKana = @NameKana,
					--ContactPersonId = @ContactPersonId,
					--Email = @Email,
					--Phone = @Phone,
					--County3 = @County3,
					--Name3 = @Name3,
					--CellularPhone = @CellularPhone,
					--IsPrimary4 = @IsPrimary4,
					--PartyId4 = @PartyId4,
					--Shared4 = @Shared4,
					--Status4 = @Status4,
					--ValidFromDateTime4 = @ValidFromDateTime4,
					--ValidToDateTime4 = @ValidToDateTime4,
					--AddressRecId5 = @AddressRecId5,
					--PartyAddressRelationshipRecId5 = @PartyAddressRelationshipRecId5,
					--RecId5 = @RecId5,
					--RecVersion5 = @RecVersion5,
					--RefCompanyId5 = @RefCompanyId5,
					--Address6 = @Address6,
					--AddressComplement6 = @AddressComplement6,
					--AddressNumber6 = @AddressNumber6,
					--AddrRecId6 = @AddrRecId6,
					--AddrTableId6 = @AddrTableId6,
					--City6 = @City6,
					--CountryRegionId6 = @CountryRegionId6,
					--DeliveryCustVendCategory6 = @DeliveryCustVendCategory6,
					--ExciseType_IN6 = @ExciseType_IN6,
					--RecId6 = @RecId6,
					--RecVersion6 = @RecVersion6,
					--ShipCarrierBlindShipment6 = @ShipCarrierBlindShipment6,
					--ShipCarrierResidential6 = @ShipCarrierResidential6,
					--State6 = @State6,
					--Street6 = @Street6,
					--TimeZone6 = @TimeZone6,
					--type6 = @type6,
					--ZipCode6 = @ZipCode6,
					--CustStatGroupId = @CustStatGroupId,
					--InvoiceModel_BR = @InvoiceModel_BR,
					--numberSequenceGroup = @numberSequenceGroup,
					--VendInvoiceType = @VendInvoiceType,
					--CCMnUM = @CCMnUM,
					--PhoneLocal = @PhoneLocal,
					--DistrictName6 = @DistrictName6,
					--TeleFax = @TeleFax,
					Dimensao8 = @Dimensao8,
					--[URL] = @URL,
					--Pager = @Pager,
					--BirthDate = @BirthDate,
					--PaymSpec = @PaymSpec,
					--OrgId = @OrgId,
					--AccountStatement = @AccountStatement,
					--CreatedDateTime = @CreatedDateTime,
					--CustCategory = @CustCategory,
					--CustFinalUser = @CustFinalUser,
					--CustGroup = @CustGroup,
					--DeliveryCustCategory = @DeliveryCustCategory,
					--ForeignCustomer_IN = @ForeignCustomer_IN,
					--GiroType = @GiroType,
					--GiroTypeAccountStatement = @GiroTypeAccountStatement,
					--GiroTypeCollectionletter = @GiroTypeCollectionletter,
					--GiroTypeFreeTextInvoice = @GiroTypeFreeTextInvoice,
					--GiroTypeInterestNote = @GiroTypeInterestNote,
					--GiroTypeProjInvoice = @GiroTypeProjInvoice,
					--InterCompanyAllowIndirectCreation = @InterCompanyAllowIndirectCreation,
					--InterCompanyAutoCreateOrders = @InterCompanyAutoCreateOrders,
					--InterCompanyDirectDelivery = @InterCompanyDirectDelivery,
					--InvoiceAddress = @InvoiceAddress,
					--MandatoryCreditLimit = @MandatoryCreditLimit,
					--OneTimeCustomer = @OneTimeCustomer,
					--PreferentialCustomer_IN = @PreferentialCustomer_IN,
					--RFIDCaseTagging = @RFIDCaseTagging,
					--RFIDItemTagging = @RFIDItemTagging,
					--RFIDPalletTagging = @RFIDPalletTagging,
					--ShipCarrierBlindShipment = @ShipCarrierBlindShipment,
					--ShipCarrierFuelSurcharge = @ShipCarrierFuelSurcharge,
					--Suframa = @Suframa,
					--SuframaPISCOFINS = @SuframaPISCOFINS,
					--TaxWithholdCalculate_IN = @TaxWithholdCalculate_IN,
					--VendItemGroupId = @VendItemGroupId,
					--Tax1099RegNum = @Tax1099RegNum,
					--DBA = @DBA,
					--CustAccount = @CustAccount,
					--Phone3 = @Phone3,
					--Email3 = @Email3,
					--BankCentralBankPurposeCode = @BankCentralBankPurposeCode,
					--ResidenceForeignCountryRegionId = @ResidenceForeignCountryRegionId,
					--IsPrimary7 = @IsPrimary7,
					--PartyId7 = @PartyId7,
					--RecId7 = @RecId7,
					--RecVersion7 = @RecVersion7,
					--Shared7 = @Shared7,
					--Status7 = @Status7,
					--ValidFromDateTime7 = @ValidFromDateTime7,
					--ValidToDateTime7 = @ValidToDateTime7,
					--AddressRecId8 = @AddressRecId8,
					--PartyAddressRelationshipRecId8 = @PartyAddressRelationshipRecId8,
					--RecId8 = @RecId8,
					--RecVersion8 = @RecVersion8,
					--RefCompanyId8 = @RefCompanyId8,
					--Address9 = @Address9,
					--AddressComplement9 = @AddressComplement9,
					--AddressNumber9 = @AddressNumber9,
					--AddrRecId9 = @AddrRecId9,
					--AddrTableId9 = @AddrTableId9,
					--City9 = @City9,
					--CountryRegionId9 = @CountryRegionId9,
					--DeliveryCustVendCategory9 = @DeliveryCustVendCategory9,
					--DistrictName9 = @DistrictName9,
					--ExciseType_IN9 = @ExciseType_IN9,
					--RecId9 = @RecId9,
					--RecVersion9 = @RecVersion9,
					--ShipCarrierBlindShipment9 = @ShipCarrierBlindShipment9,
					--ShipCarrierResidential9 = @ShipCarrierResidential9,
					--State9 = @State9,
					--Street9 = @Street9,
					--type9 = @type9,
					--ZipCode9 = @ZipCode9,
					--IsPrimary10 = @IsPrimary10,
					--PartyId10 = @PartyId10,
					--RecId10 = @RecId10,
					--RecVersion10 = @RecVersion10,
					--Shared10 = @Shared10,
					--Status10 = @Status10,
					--ValidFromDateTime10 = @ValidFromDateTime10,
					--ValidToDateTime10 = @ValidToDateTime10,
					--AddressRecId11 = @AddressRecId11,
					--PartyAddressRelationshipRecId11 = @PartyAddressRelationshipRecId11,
					--RecId11 = @RecId11,
					--RecVersion11 = @RecVersion11,
					--RefCompanyId11 = @RefCompanyId11,
					--Address12 = @Address12,
					--AddressComplement12 = @AddressComplement12,
					--AddressNumber12 = @AddressNumber12,
					--AddrRecId12 = @AddrRecId12,
					--AddrTableId12 = @AddrTableId12,
					--City12 = @City12,
					--CountryRegionId12 = @CountryRegionId12,
					--DeliveryCustVendCategory12 = @DeliveryCustVendCategory12,
					--DistrictName12 = @DistrictName12,
					--ExciseType_IN12 = @ExciseType_IN12,
					--RecId12 = @RecId12,
					--RecVersion12 = @RecVersion12,
					--ShipCarrierBlindShipment12 = @ShipCarrierBlindShipment12,
					--ShipCarrierResidential12 = @ShipCarrierResidential12,
					--State12 = @State12,
					--Street12 = @Street12,
					--type12 = @type12,
					--ZipCode12 = @ZipCode12,
					--IsPrimary13 = @IsPrimary13,
					--PartyId13 = @PartyId13,
					--RecId13 = @RecId13,
					--RecVersion13 = @RecVersion13,
					--Shared13 = @Shared13,
					--Status13 = @Status13,
					--ValidFromDateTime13 = @ValidFromDateTime13,
					--ValidToDateTime13 = @ValidToDateTime13,
					--AddressRecId14 = @AddressRecId14,
					--PartyAddressRelationshipRecId14 = @PartyAddressRelationshipRecId14,
					--RecId14 = @RecId14,
					--RecVersion14 = @RecVersion14,
					--RefCompanyId14 = @RefCompanyId14,
					--Address15 = @Address15,
					--AddressComplement15 = @AddressComplement15,
					--AddressNumber15 = @AddressNumber15,
					--AddrRecId15 = @AddrRecId15,
					--AddrTableId15 = @AddrTableId15,
					--City15 = @City15,
					--CountryRegionId15 = @CountryRegionId15,
					--DeliveryCustVendCategory15 = @DeliveryCustVendCategory15,
					--DistrictName15 = @DistrictName15,
					--ExciseType_IN15 = @ExciseType_IN15,
					--RecId15 = @RecId15,
					--RecVersion15 = @RecVersion15,
					--ShipCarrierBlindShipment15 = @ShipCarrierBlindShipment15,
					--ShipCarrierResidential15 = @ShipCarrierResidential15,
					--State15 = @State15,
					--Street15 = @Street15,
					--type15 = @type15,
					--ZipCode15 = @ZipCode15,
					--IsPrimary16 = @IsPrimary16,
					--PartyId16 = @PartyId16,
					--RecId16 = @RecId16,
					--RecVersion16 = @RecVersion16,
					--Shared16 = @Shared16,
					--Status16 = @Status16,
					--ValidFromDateTime16 = @ValidFromDateTime16,
					--ValidToDateTime16 = @ValidToDateTime16,
					--AddressRecId17 = @AddressRecId17,
					--PartyAddressRelationshipRecId17 = @PartyAddressRelationshipRecId17,
					--RecId17 = @RecId17,
					--RecVersion17 = @RecVersion17,
					--RefCompanyId17 = @RefCompanyId17,
					--Address18 = @Address18,
					--AddressComplement18 = @AddressComplement18,
					--AddressNumber18 = @AddressNumber18,
					--AddrRecId18 = @AddrRecId18,
					--AddrTableId18 = @AddrTableId18,
					--City18 = @City18,
					--CountryRegionId18 = @CountryRegionId18,
					--DeliveryCustVendCategory18 = @DeliveryCustVendCategory18,
					--DistrictName18 = @DistrictName18,
					--ExciseType_IN18 = @ExciseType_IN18,
					--RecId18 = @RecId18,
					--RecVersion18 = @RecVersion18,
					--ShipCarrierBlindShipment18 = @ShipCarrierBlindShipment18,
					--ShipCarrierResidential18 = @ShipCarrierResidential18,
					--State18 = @State18,
					--Street18 = @Street18,
					--type18 = @type18,
					--ZipCode18 = @ZipCode18,
					--IsPrimary19 = @IsPrimary19,
					--PartyId19 = @PartyId19,
					--RecId19 = @RecId19,
					--RecVersion19 = @RecVersion19,
					--Shared19 = @Shared19,
					--Status19 = @Status19,
					--ValidFromDateTime19 = @ValidFromDateTime19,
					--ValidToDateTime19 = @ValidToDateTime19,
					--AddressRecId20 = @AddressRecId20,
					--PartyAddressRelationshipRecId20 = @PartyAddressRelationshipRecId20,
					--RecId20 = @RecId20,
					--RecVersion20 = @RecVersion20,
					--RefCompanyId20 = @RefCompanyId20,
					--Address21 = @Address21,
					--AddressComplement21 = @AddressComplement21,
					--AddressNumber21 = @AddressNumber21,
					--AddrRecId21 = @AddrRecId21,
					--AddrTableId21 = @AddrTableId21,
					--City21 = @City21,
					--CountryRegionId21 = @CountryRegionId21,
					--DeliveryCustVendCategory21 = @DeliveryCustVendCategory21,
					--DistrictName21 = @DistrictName21,
					--ExciseType_IN21 = @ExciseType_IN21,
					--RecId21 = @RecId21,
					--RecVersion21 = @RecVersion21,
					--ShipCarrierBlindShipment21 = @ShipCarrierBlindShipment21,
					--ShipCarrierResidential21 = @ShipCarrierResidential21,
					--State21 = @State21,
					--Street21 = @Street21,
					--type21 = @type21,
					--ZipCode21 = @ZipCode21,
					--IsPrimary22 = @IsPrimary22,
					--PartyId22 = @PartyId22,
					--RecId22 = @RecId22,
					--RecVersion22 = @RecVersion22,
					--Shared22 = @Shared22,
					--Status22 = @Status22,
					--ValidFromDateTime22 = @ValidFromDateTime22,
					--ValidToDateTime22 = @ValidToDateTime22,
					--AddressRecId23 = @AddressRecId23,
					--PartyAddressRelationshipRecId23 = @PartyAddressRelationshipRecId23,
					--RecId23 = @RecId23,
					--RecVersion23 = @RecVersion23,
					--RefCompanyId23 = @RefCompanyId23,
					--Address24 = @Address24,
					--AddressComplement24 = @AddressComplement24,
					--AddressNumber24 = @AddressNumber24,
					--AddrRecId24 = @AddrRecId24,
					--AddrTableId24 = @AddrTableId24,
					--City24 = @City24,
					--CountryRegionId24 = @CountryRegionId24,
					--DeliveryCustVendCategory24 = @DeliveryCustVendCategory24,
					--DistrictName24 = @DistrictName24,
					--ExciseType_IN24 = @ExciseType_IN24,
					--RecId24 = @RecId24,
					--RecVersion24 = @RecVersion24,
					--ShipCarrierBlindShipment24 = @ShipCarrierBlindShipment24,
					--ShipCarrierResidential24 = @ShipCarrierResidential24,
					--State24 = @State24,
					--Street24 = @Street24,
					--type24 = @type24,
					--ZipCode24 = @ZipCode24,
					--IsPrimary25 = @IsPrimary25,
					--PartyId25 = @PartyId25,
					--RecId25 = @RecId25,
					--RecVersion25 = @RecVersion25,
					--Shared25 = @Shared25,
					--Status25 = @Status25,
					--ValidFromDateTime25 = @ValidFromDateTime25,
					--ValidToDateTime25 = @ValidToDateTime25,
					--AddressRecId26 = @AddressRecId26,
					--PartyAddressRelationshipRecId26 = @PartyAddressRelationshipRecId26,
					--RecId26 = @RecId26,
					--RecVersion26 = @RecVersion26,
					--RefCompanyId26 = @RefCompanyId26,
					--Address27 = @Address27,
					--AddressComplement27 = @AddressComplement27,
					--AddressNumber27 = @AddressNumber27,
					--AddrRecId27 = @AddrRecId27,
					--AddrTableId27 = @AddrTableId27,
					--City27 = @City27,
					--CountryRegionId27 = @CountryRegionId27,
					--DeliveryCustVendCategory27 = @DeliveryCustVendCategory27,
					--DistrictName27 = @DistrictName27,
					--ExciseType_IN27 = @ExciseType_IN27,
					--RecId27 = @RecId27,
					--RecVersion27 = @RecVersion27,
					--ShipCarrierBlindShipment27 = @ShipCarrierBlindShipment27,
					--ShipCarrierResidential27 = @ShipCarrierResidential27,
					--State27 = @State27,
					--Street27 = @Street27,
					--type27 = @type27,
					--ZipCode27 = @ZipCode27,
					--IsPrimary28 = @IsPrimary28,
					--PartyId28 = @PartyId28,
					--RecId28 = @RecId28,
					--RecVersion28 = @RecVersion28,
					--Shared28 = @Shared28,
					--Status28 = @Status28,
					--ValidFromDateTime28 = @ValidFromDateTime28,
					--ValidToDateTime28 = @ValidToDateTime28,
					--AddressRecId29 = @AddressRecId29,
					--PartyAddressRelationshipRecId29 = @PartyAddressRelationshipRecId29,
					--RecId29 = @RecId29,
					--RecVersion29 = @RecVersion29,
					--RefCompanyId29 = @RefCompanyId29,
					--Address30 = @Address30,
					--AddressComplement30 = @AddressComplement30,
					--AddressNumber30 = @AddressNumber30,
					--AddrRecId30 = @AddrRecId30,
					--AddrTableId30 = @AddrTableId30,
					--City30 = @City30,
					--CountryRegionId30 = @CountryRegionId30,
					--DeliveryCustVendCategory30 = @DeliveryCustVendCategory30,
					--DistrictName30 = @DistrictName30,
					--ExciseType_IN30 = @ExciseType_IN30,
					--RecId30 = @RecId30,
					--RecVersion30 = @RecVersion30,
					--ShipCarrierBlindShipment30 = @ShipCarrierBlindShipment30,
					--ShipCarrierResidential30 = @ShipCarrierResidential30,
					--State30 = @State30,
					--Street30 = @Street30,
					--type30 = @type30,
					--ZipCode30 = @ZipCode30,
					--IsPrimary31 = @IsPrimary31,
					--PartyId31 = @PartyId31,
					--RecId31 = @RecId31,
					--RecVersion31 = @RecVersion31,
					--Shared31 = @Shared31,
					--Status31 = @Status31,
					--ValidFromDateTime31 = @ValidFromDateTime31,
					--ValidToDateTime31 = @ValidToDateTime31,
					--AddressRecId32 = @AddressRecId32,
					--PartyAddressRelationshipRecId32 = @PartyAddressRelationshipRecId32,
					--RecId32 = @RecId32,
					--RecVersion32 = @RecVersion32,
					--RefCompanyId32 = @RefCompanyId32,
					--Address33 = @Address33,
					--AddressComplement33 = @AddressComplement33,
					--AddressNumber33 = @AddressNumber33,
					--AddrRecId33 = @AddrRecId33,
					--AddrTableId33 = @AddrTableId33,
					--City33 = @City33,
					--CountryRegionId33 = @CountryRegionId33,
					--DeliveryCustVendCategory33 = @DeliveryCustVendCategory33,
					--DistrictName33 = @DistrictName33,
					--ExciseType_IN33 = @ExciseType_IN33,
					--RecId33 = @RecId33,
					--RecVersion33 = @RecVersion33,
					--ShipCarrierBlindShipment33 = @ShipCarrierBlindShipment33,
					--ShipCarrierResidential33 = @ShipCarrierResidential33,
					--State33 = @State33,
					--Street33 = @Street33,
					--type33 = @type33,
					--ZipCode33 = @ZipCode33,
					--IsPrimary34 = @IsPrimary34,
					--PartyId34 = @PartyId34,
					--RecId34 = @RecId34,
					--RecVersion34 = @RecVersion34,
					--Shared34 = @Shared34,
					--Status34 = @Status34,
					--ValidFromDateTime34 = @ValidFromDateTime34,
					--ValidToDateTime34 = @ValidToDateTime34,
					--AddressRecId35 = @AddressRecId35,
					--PartyAddressRelationshipRecId35 = @PartyAddressRelationshipRecId35,
					--RecId35 = @RecId35,
					--RecVersion35 = @RecVersion35,
					--RefCompanyId35 = @RefCompanyId35,
					--Address36 = @Address36,
					--AddressComplement36 = @AddressComplement36,
					--AddressNumber36 = @AddressNumber36,
					--AddrRecId36 = @AddrRecId36,
					--AddrTableId36 = @AddrTableId36,
					--City36 = @City36,
					--CountryRegionId36 = @CountryRegionId36,
					--DeliveryCustVendCategory36 = @DeliveryCustVendCategory36,
					--DistrictName36 = @DistrictName36,
					--ExciseType_IN36 = @ExciseType_IN36,
					--RecId36 = @RecId36,
					--RecVersion36 = @RecVersion36,
					--ShipCarrierBlindShipment36 = @ShipCarrierBlindShipment36,
					--ShipCarrierResidential36 = @ShipCarrierResidential36,
					--State36 = @State36,
					--Street36 = @Street36,
					--type36 = @type36,
					--ZipCode36 = @ZipCode36,
					--IsPrimary37 = @IsPrimary37,
					--PartyId37 = @PartyId37,
					--RecId37 = @RecId37,
					--RecVersion37 = @RecVersion37,
					--Shared37 = @Shared37,
					--Status37 = @Status37,
					--ValidFromDateTime37 = @ValidFromDateTime37,
					--ValidToDateTime37 = @ValidToDateTime37,
					--AddressRecId38 = @AddressRecId38,
					--PartyAddressRelationshipRecId38 = @PartyAddressRelationshipRecId38,
					--RecId38 = @RecId38,
					--RecVersion38 = @RecVersion38,
					--RefCompanyId38 = @RefCompanyId38,
					--Address39 = @Address39,
					--AddressComplement39 = @AddressComplement39,
					--AddressNumber39 = @AddressNumber39,
					--AddrRecId39 = @AddrRecId39,
					--AddrTableId39 = @AddrTableId39,
					--City39 = @City39,
					--CountryRegionId39 = @CountryRegionId39,
					--DeliveryCustVendCategory39 = @DeliveryCustVendCategory39,
					--DistrictName39 = @DistrictName39,
					--ExciseType_IN39 = @ExciseType_IN39,
					--RecId39 = @RecId39,
					--RecVersion39 = @RecVersion39,
					--ShipCarrierBlindShipment39 = @ShipCarrierBlindShipment39,
					--ShipCarrierResidential39 = @ShipCarrierResidential39,
					--State39 = @State39,
					--Street39 = @Street39,
					--type39 = @type39,
					--ZipCode39 = @ZipCode39,
					--IsPrimary40 = @IsPrimary40,
					--PartyId40 = @PartyId40,
					--RecId40 = @RecId40,
					--RecVersion40 = @RecVersion40,
					--Shared40 = @Shared40,
					--Status40 = @Status40,
					--ValidFromDateTime40 = @ValidFromDateTime40,
					--ValidToDateTime40 = @ValidToDateTime40,
					--AddressRecId41 = @AddressRecId41,
					--PartyAddressRelationshipRecId41 = @PartyAddressRelationshipRecId41,
					--RecId41 = @RecId41,
					--RecVersion41 = @RecVersion41,
					--RefCompanyId41 = @RefCompanyId41,
					--Address42 = @Address42,
					--AddressComplement42 = @AddressComplement42,
					--AddressNumber42 = @AddressNumber42,
					--AddrRecId42 = @AddrRecId42,
					--AddrTableId42 = @AddrTableId42,
					--City42 = @City42,
					--CountryRegionId42 = @CountryRegionId42,
					--DeliveryCustVendCategory42 = @DeliveryCustVendCategory42,
					--DistrictName42 = @DistrictName42,
					--ExciseType_IN42 = @ExciseType_IN42,
					--RecId42 = @RecId42,
					--RecVersion42 = @RecVersion42,
					--ShipCarrierBlindShipment42 = @ShipCarrierBlindShipment42,
					--ShipCarrierResidential42 = @ShipCarrierResidential42,
					--State42 = @State42,
					--Street42 = @Street42,
					--type42 = @type42,
					--ZipCode42 = @ZipCode42,
					--IsPrimary43 = @IsPrimary43,
					--PartyId43 = @PartyId43,
					--RecId43 = @RecId43,
					--RecVersion43 = @RecVersion43,
					--Shared43 = @Shared43,
					--Status43 = @Status43,
					--ValidFromDateTime43 = @ValidFromDateTime43,
					--ValidToDateTime43 = @ValidToDateTime43,
					--AddressRecId44 = @AddressRecId44,
					--PartyAddressRelationshipRecId44 = @PartyAddressRelationshipRecId44,
					--RecId44 = @RecId44,
					--RecVersion44 = @RecVersion44,
					--RefCompanyId44 = @RefCompanyId44,
					--Address45 = @Address45,
					--AddressComplement45 = @AddressComplement45,
					--AddressNumber45 = @AddressNumber45,
					--AddrRecId45 = @AddrRecId45,
					--AddrTableId45 = @AddrTableId45,
					--City45 = @City45,
					--CountryRegionId45 = @CountryRegionId45,
					--DeliveryCustVendCategory45 = @DeliveryCustVendCategory45,
					--DistrictName45 = @DistrictName45,
					--ExciseType_IN45 = @ExciseType_IN45,
					--RecId45 = @RecId45,
					--RecVersion45 = @RecVersion45,
					--ShipCarrierBlindShipment45 = @ShipCarrierBlindShipment45,
					--ShipCarrierResidential45 = @ShipCarrierResidential45,
					--State45 = @State45,
					--Street45 = @Street45,
					--type45 = @type45,
					--ZipCode45 = @ZipCode45,
					--IsPrimary46 = @IsPrimary46,
					--PartyId46 = @PartyId46,
					--RecId46 = @RecId46,
					--RecVersion46 = @RecVersion46,
					--Shared46 = @Shared46,
					--Status46 = @Status46,
					--ValidFromDateTime46 = @ValidFromDateTime46,
					--ValidToDateTime46 = @ValidToDateTime46,
					--AddressRecId47 = @AddressRecId47,
					--PartyAddressRelationshipRecId47 = @PartyAddressRelationshipRecId47,
					--RecId47 = @RecId47,
					--RecVersion47 = @RecVersion47,
					--RefCompanyId47 = @RefCompanyId47,
					--Address48 = @Address48,
					--AddressComplement48 = @AddressComplement48,
					--AddressNumber48 = @AddressNumber48,
					--AddrRecId48 = @AddrRecId48,
					--AddrTableId48 = @AddrTableId48,
					--City48 = @City48,
					--CountryRegionId48 = @CountryRegionId48,
					--DeliveryCustVendCategory48 = @DeliveryCustVendCategory48,
					--DistrictName48 = @DistrictName48,
					--ExciseType_IN48 = @ExciseType_IN48,
					--RecId48 = @RecId48,
					--RecVersion48 = @RecVersion48,
					--ShipCarrierBlindShipment48 = @ShipCarrierBlindShipment48,
					--ShipCarrierResidential48 = @ShipCarrierResidential48,
					--State48 = @State48,
					--Street48 = @Street48,
					--type48 = @type48,
					--ZipCode48 = @ZipCode48,
					--IsPrimary49 = @IsPrimary49,
					--PartyId49 = @PartyId49,
					--RecId49 = @RecId49,
					--RecVersion49 = @RecVersion49,
					--Shared49 = @Shared49,
					--Status49 = @Status49,
					--ValidFromDateTime49 = @ValidFromDateTime49,
					--ValidToDateTime49 = @ValidToDateTime49,
					--AddressRecId50 = @AddressRecId50,
					--PartyAddressRelationshipRecId50 = @PartyAddressRelationshipRecId50,
					--RecId50 = @RecId50,
					--RecVersion50 = @RecVersion50,
					--RefCompanyId50 = @RefCompanyId50,
					VATNum = @VATNum                    
                WHERE
                    AccountNum = @AccountNum                  
                
            END
            ELSE
            BEGIN
                INSERT INTO AX_XML_Vendor_Recebido
                (
                    _DocumentHash,
					AccountNum,
				[File],
				[Created Date],
				BidOnly,
				Blocked,
				CNPJCPFNum,
				CompanyType_MX,
				CompositionScheme_IN,
				Currency,
				DeliveryVendCategory,
				Dimensao1,
				Dimensao2,
				Dimensao3,
				Dimensao4,
				Dimensao5,
				Dimensao6,
				Dimensao7,
				EletronicInvoice,
				EstablishmentType,
				FemaleOwned,
				ForeignEntityIndicator,
				ForeignVendor_IN,
				GTAVendor_IN,
				Heir_IT,
				ICMSContributor,
				IENum,
				InclTax,
				LanguageId,
				LocallyOwned,
				MinorityOwned,
				ModifiedDateTime,
				[Name],
				NameAlias,
				NatureOfAssessee_IN,
				NFSpecie_BR,
				NonTaxable_BR,
				OffsetAccountType,
				OneTimeVendor,
				PANStatus_IN,
				PartyId,
				PartyType,
				PaymMode,
				PaymTermId,
				PreferentialVendor_IN,
				PurchAmountPurchaseOrder,
				RecId,
				RecVersion,
				SecondTIN,
				ServiceCodeOnDlvAddress,
				SmallBusiness,
				SSIVendor_IN,
				SubContractor_SA,
				Tax1099NameChoice,
				Tax1099Reports,
				TaxGroup,
				TaxIDType,
				TaxWithholdCalculate,
				TKR_CreditCard,
				TKR_ElecInvoice,
				TKR_RetailAlcoholic,
				TKR_VATBizType,
				TKR_WholesaleAlcoholic,
				VendCategory,
				VendConsumption_BR,
				VendGroup,
				W9,
				YourAccountNum,
				IsPrimary1,
				PartyId1,
				RecId1,
				RecVersion1,
				Shared1,
				Status1,
				ValidFromDateTime1,
				ValidToDateTime1,
				AddressRecId2,
				PartyAddressRelationshipRecId2,
				RecId2,
				RecVersion2,
				RefCompanyId2,
				Address3,
				AddressComplement3,
				AddressNumber3,
				AddrRecId3,
				AddrTableId3,
				City3,
				CountryRegionId3,
				DeliveryCustVendCategory3,
				ExciseType_IN3,
				RecId3,
				RecVersion3,
				ShipCarrierBlindShipment3,
				ShipCarrierResidential3,
				State3,
				Street3,
				TimeZone3,
				type3,
				ZipCode3,
				DistrictName3,
				OffsetAccount,
				City4,
				CountryRegionId4,
				DeliveryCustVendCategory4,
				ExciseType_IN4,
				Name4,
				RecId4,
				RecVersion4,
				ShipCarrierBlindShipment4,
				State4,
				ShipCarrierResidential4,
				Street4,
				type4,
				ZipCode4,
				AddressRecId3,
				PartyAddressRelationshipRecId3,
				AddressComplement4,
				AddressNumber4,
				AddrRecId4,
				AddrTableId4,
				Address4,
				RefCompanyId3,
				ValidToDateTime2,
				ValidFromDateTime2,
				Status2,
				Shared2,
				AddressComplement,
				City,
				CountryRegionId,
				DeliveryVendCNPJCPFNum,
				DeliveryVendIENum,
				PANNumber_IN,
				PartyId2,
				IsPrimary2,
				ZipCode,
				TKR_Name,
				TKR_Address,
				Street,
				[Address],
				[State],
				AddressNumber,
				TimeZone4,
				BankAccount,
				DistrictName,
				TaxWithholdGroup,
				DistrictName4,
				DeliveryCustVendCNPJCPFNum4,
				DeliveryCustVendIENum4,
				County,
				County4,
				Dt_Envio_ATL,
				Dt_Atualiza_ATL,
				NameKana,
				ContactPersonId,
				Email,
				Phone,
				County3,
				Name3,
				CellularPhone,
				IsPrimary4,
				PartyId4,
				Shared4,
				Status4,
				ValidFromDateTime4,
				ValidToDateTime4,
				AddressRecId5,
				PartyAddressRelationshipRecId5,
				RecId5,
				RecVersion5,
				RefCompanyId5,
				Address6,
				AddressComplement6,
				AddressNumber6,
				AddrRecId6,
				AddrTableId6,
				City6,
				CountryRegionId6,
				DeliveryCustVendCategory6,
				ExciseType_IN6,
				RecId6,
				RecVersion6,
				ShipCarrierBlindShipment6,
				ShipCarrierResidential6,
				State6,
				Street6,
				TimeZone6,
				type6,
				ZipCode6,
				CustStatGroupId,
				InvoiceModel_BR,
				numberSequenceGroup,
				VendInvoiceType,
				CCMnUM,
				PhoneLocal,
				DistrictName6,
				TeleFax,
				Dimensao8,
				[URL],
				Pager,
				BirthDate,
				PaymSpec,
				OrgId,
				AccountStatement,
				CreatedDateTime,
				CustCategory,
				CustFinalUser,
				CustGroup,
				DeliveryCustCategory,
				ForeignCustomer_IN,
				GiroType,
				GiroTypeAccountStatement,
				GiroTypeCollectionletter,
				GiroTypeFreeTextInvoice,
				GiroTypeInterestNote,
				GiroTypeProjInvoice,
				InterCompanyAllowIndirectCreation,
				InterCompanyAutoCreateOrders,
				InterCompanyDirectDelivery,
				InvoiceAddress,
				MandatoryCreditLimit,
				OneTimeCustomer,
				PreferentialCustomer_IN,
				RFIDCaseTagging,
				RFIDItemTagging,
				RFIDPalletTagging,
				ShipCarrierBlindShipment,
				ShipCarrierFuelSurcharge,
				Suframa,
				SuframaPISCOFINS,
				TaxWithholdCalculate_IN,
				VendItemGroupId,
				Tax1099RegNum,
				DBA,
				CustAccount,
				Phone3,
				Email3,
				BankCentralBankPurposeCode,
				ResidenceForeignCountryRegionId,
				IsPrimary7,
				PartyId7,
				RecId7,
				RecVersion7,
				Shared7,
				Status7,
				ValidFromDateTime7,
				ValidToDateTime7,
				AddressRecId8,
				PartyAddressRelationshipRecId8,
				RecId8,
				RecVersion8,
				RefCompanyId8,
				Address9,
				AddressComplement9,
				AddressNumber9,
				AddrRecId9,
				AddrTableId9,
				City9,
				CountryRegionId9,
				DeliveryCustVendCategory9,
				DistrictName9,
				ExciseType_IN9,
				RecId9,
				RecVersion9,
				ShipCarrierBlindShipment9,
				ShipCarrierResidential9,
				State9,
				Street9,
				type9,
				ZipCode9,
				IsPrimary10,
				PartyId10,
				RecId10,
				RecVersion10,
				Shared10,
				Status10,
				ValidFromDateTime10,
				ValidToDateTime10,
				AddressRecId11,
				PartyAddressRelationshipRecId11,
				RecId11,
				RecVersion11,
				RefCompanyId11,
				Address12,
				AddressComplement12,
				AddressNumber12,
				AddrRecId12,
				AddrTableId12,
				City12,
				CountryRegionId12,
				DeliveryCustVendCategory12,
				DistrictName12,
				ExciseType_IN12,
				RecId12,
				RecVersion12,
				ShipCarrierBlindShipment12,
				ShipCarrierResidential12,
				State12,
				Street12,
				type12,
				ZipCode12,
				IsPrimary13,
				PartyId13,
				RecId13,
				RecVersion13,
				Shared13,
				Status13,
				ValidFromDateTime13,
				ValidToDateTime13,
				AddressRecId14,
				PartyAddressRelationshipRecId14,
				RecId14,
				RecVersion14,
				RefCompanyId14,
				Address15,
				AddressComplement15,
				AddressNumber15,
				AddrRecId15,
				AddrTableId15,
				City15,
				CountryRegionId15,
				DeliveryCustVendCategory15,
				DistrictName15,
				ExciseType_IN15,
				RecId15,
				RecVersion15,
				ShipCarrierBlindShipment15,
				ShipCarrierResidential15,
				State15,
				Street15,
				type15,
				ZipCode15,
				IsPrimary16,
				PartyId16,
				RecId16,
				RecVersion16,
				Shared16,
				Status16,
				ValidFromDateTime16,
				ValidToDateTime16,
				AddressRecId17,
				PartyAddressRelationshipRecId17,
				RecId17,
				RecVersion17,
				RefCompanyId17,
				Address18,
				AddressComplement18,
				AddressNumber18,
				AddrRecId18,
				AddrTableId18,
				City18,
				CountryRegionId18,
				DeliveryCustVendCategory18,
				DistrictName18,
				ExciseType_IN18,
				RecId18,
				RecVersion18,
				ShipCarrierBlindShipment18,
				ShipCarrierResidential18,
				State18,
				Street18,
				type18,
				ZipCode18,
				IsPrimary19,
				PartyId19,
				RecId19,
				RecVersion19,
				Shared19,
				Status19,
				ValidFromDateTime19,
				ValidToDateTime19,
				AddressRecId20,
				PartyAddressRelationshipRecId20,
				RecId20,
				RecVersion20,
				RefCompanyId20,
				Address21,
				AddressComplement21,
				AddressNumber21,
				AddrRecId21,
				AddrTableId21,
				City21,
				CountryRegionId21,
				DeliveryCustVendCategory21,
				DistrictName21,
				ExciseType_IN21,
				RecId21,
				RecVersion21,
				ShipCarrierBlindShipment21,
				ShipCarrierResidential21,
				State21,
				Street21,
				type21,
				ZipCode21,
				IsPrimary22,
				PartyId22,
				RecId22,
				RecVersion22,
				Shared22,
				Status22,
				ValidFromDateTime22,
				ValidToDateTime22,
				AddressRecId23,
				PartyAddressRelationshipRecId23,
				RecId23,
				RecVersion23,
				RefCompanyId23,
				Address24,
				AddressComplement24,
				AddressNumber24,
				AddrRecId24,
				AddrTableId24,
				City24,
				CountryRegionId24,
				DeliveryCustVendCategory24,
				DistrictName24,
				ExciseType_IN24,
				RecId24,
				RecVersion24,
				ShipCarrierBlindShipment24,
				ShipCarrierResidential24,
				State24,
				Street24,
				type24,
				ZipCode24,
				IsPrimary25,
				PartyId25,
				RecId25,
				RecVersion25,
				Shared25,
				Status25,
				ValidFromDateTime25,
				ValidToDateTime25,
				AddressRecId26,
				PartyAddressRelationshipRecId26,
				RecId26,
				RecVersion26,
				RefCompanyId26,
				Address27,
				AddressComplement27,
				AddressNumber27,
				AddrRecId27,
				AddrTableId27,
				City27,
				CountryRegionId27,
				DeliveryCustVendCategory27,
				DistrictName27,
				ExciseType_IN27,
				RecId27,
				RecVersion27,
				ShipCarrierBlindShipment27,
				ShipCarrierResidential27,
				State27,
				Street27,
				type27,
				ZipCode27,
				IsPrimary28,
				PartyId28,
				RecId28,
				RecVersion28,
				Shared28,
				Status28,
				ValidFromDateTime28,
				ValidToDateTime28,
				AddressRecId29,
				PartyAddressRelationshipRecId29,
				RecId29,
				RecVersion29,
				RefCompanyId29,
				Address30,
				AddressComplement30,
				AddressNumber30,
				AddrRecId30,
				AddrTableId30,
				City30,
				CountryRegionId30,
				DeliveryCustVendCategory30,
				DistrictName30,
				ExciseType_IN30,
				RecId30,
				RecVersion30,
				ShipCarrierBlindShipment30,
				ShipCarrierResidential30,
				State30,
				Street30,
				type30,
				ZipCode30,
				IsPrimary31,
				PartyId31,
				RecId31,
				RecVersion31,
				Shared31,
				Status31,
				ValidFromDateTime31,
				ValidToDateTime31,
				AddressRecId32,
				PartyAddressRelationshipRecId32,
				RecId32,
				RecVersion32,
				RefCompanyId32,
				Address33,
				AddressComplement33,
				AddressNumber33,
				AddrRecId33,
				AddrTableId33,
				City33,
				CountryRegionId33,
				DeliveryCustVendCategory33,
				DistrictName33,
				ExciseType_IN33,
				RecId33,
				RecVersion33,
				ShipCarrierBlindShipment33,
				ShipCarrierResidential33,
				State33,
				Street33,
				type33,
				ZipCode33,
				IsPrimary34,
				PartyId34,
				RecId34,
				RecVersion34,
				Shared34,
				Status34,
				ValidFromDateTime34,
				ValidToDateTime34,
				AddressRecId35,
				PartyAddressRelationshipRecId35,
				RecId35,
				RecVersion35,
				RefCompanyId35,
				Address36,
				AddressComplement36,
				AddressNumber36,
				AddrRecId36,
				AddrTableId36,
				City36,
				CountryRegionId36,
				DeliveryCustVendCategory36,
				DistrictName36,
				ExciseType_IN36,
				RecId36,
				RecVersion36,
				ShipCarrierBlindShipment36,
				ShipCarrierResidential36,
				State36,
				Street36,
				type36,
				ZipCode36,
				IsPrimary37,
				PartyId37,
				RecId37,
				RecVersion37,
				Shared37,
				Status37,
				ValidFromDateTime37,
				ValidToDateTime37,
				AddressRecId38,
				PartyAddressRelationshipRecId38,
				RecId38,
				RecVersion38,
				RefCompanyId38,
				Address39,
				AddressComplement39,
				AddressNumber39,
				AddrRecId39,
				AddrTableId39,
				City39,
				CountryRegionId39,
				DeliveryCustVendCategory39,
				DistrictName39,
				ExciseType_IN39,
				RecId39,
				RecVersion39,
				ShipCarrierBlindShipment39,
				ShipCarrierResidential39,
				State39,
				Street39,
				type39,
				ZipCode39,
				IsPrimary40,
				PartyId40,
				RecId40,
				RecVersion40,
				Shared40,
				Status40,
				ValidFromDateTime40,
				ValidToDateTime40,
				AddressRecId41,
				PartyAddressRelationshipRecId41,
				RecId41,
				RecVersion41,
				RefCompanyId41,
				Address42,
				AddressComplement42,
				AddressNumber42,
				AddrRecId42,
				AddrTableId42,
				City42,
				CountryRegionId42,
				DeliveryCustVendCategory42,
				DistrictName42,
				ExciseType_IN42,
				RecId42,
				RecVersion42,
				ShipCarrierBlindShipment42,
				ShipCarrierResidential42,
				State42,
				Street42,
				type42,
				ZipCode42,
				IsPrimary43,
				PartyId43,
				RecId43,
				RecVersion43,
				Shared43,
				Status43,
				ValidFromDateTime43,
				ValidToDateTime43,
				AddressRecId44,
				PartyAddressRelationshipRecId44,
				RecId44,
				RecVersion44,
				RefCompanyId44,
				Address45,
				AddressComplement45,
				AddressNumber45,
				AddrRecId45,
				AddrTableId45,
				City45,
				CountryRegionId45,
				DeliveryCustVendCategory45,
				DistrictName45,
				ExciseType_IN45,
				RecId45,
				RecVersion45,
				ShipCarrierBlindShipment45,
				ShipCarrierResidential45,
				State45,
				Street45,
				type45,
				ZipCode45,
				IsPrimary46,
				PartyId46,
				RecId46,
				RecVersion46,
				Shared46,
				Status46,
				ValidFromDateTime46,
				ValidToDateTime46,
				AddressRecId47,
				PartyAddressRelationshipRecId47,
				RecId47,
				RecVersion47,
				RefCompanyId47,
				Address48,
				AddressComplement48,
				AddressNumber48,
				AddrRecId48,
				AddrTableId48,
				City48,
				CountryRegionId48,
				DeliveryCustVendCategory48,
				DistrictName48,
				ExciseType_IN48,
				RecId48,
				RecVersion48,
				ShipCarrierBlindShipment48,
				ShipCarrierResidential48,
				State48,
				Street48,
				type48,
				ZipCode48,
				IsPrimary49,
				PartyId49,
				RecId49,
				RecVersion49,
				Shared49,
				Status49,
				ValidFromDateTime49,
				ValidToDateTime49,
				AddressRecId50,
				PartyAddressRelationshipRecId50,
				RecId50,
				RecVersion50,
				RefCompanyId50,
				VATNum
                )
                VALUES
                (
                    @_DocumentHash,
				@AccountNum,
				@File,
				@Created_Date,
				@BidOnly,
				@Blocked,
				@CNPJCPFNum,
				@CompanyType_MX,
				@CompositionScheme_IN,
				@Currency,
				@DeliveryVendCategory,
				@Dimensao1,
				@Dimensao2,
				@Dimensao3,
				@Dimensao4,
				@Dimensao5,
				@Dimensao6,
				@Dimensao7,
				@EletronicInvoice,
				@EstablishmentType,
				@FemaleOwned,
				@ForeignEntityIndicator,
				@ForeignVendor_IN,
				@GTAVendor_IN,
				@Heir_IT,
				@ICMSContributor,
				@IENum,
				@InclTax,
				@LanguageId,
				@LocallyOwned,
				@MinorityOwned,
				@ModifiedDateTime,
				@Name,
				@NameAlias,
				@NatureOfAssessee_IN,
				@NFSpecie_BR,
				@NonTaxable_BR,
				@OffsetAccountType,
				@OneTimeVendor,
				@PANStatus_IN,
				@PartyId,
				@PartyType,
				@PaymMode,
				@PaymTermId,
				@PreferentialVendor_IN,
				@PurchAmountPurchaseOrder,
				@RecId,
				@RecVersion,
				@SecondTIN,
				@ServiceCodeOnDlvAddress,
				@SmallBusiness,
				@SSIVendor_IN,
				@SubContractor_SA,
				@Tax1099NameChoice,
				@Tax1099Reports,
				@TaxGroup,
				@TaxIDType,
				@TaxWithholdCalculate,
				@TKR_CreditCard,
				@TKR_ElecInvoice,
				@TKR_RetailAlcoholic,
				@TKR_VATBizType,
				@TKR_WholesaleAlcoholic,
				@VendCategory,
				@VendConsumption_BR,
				@VendGroup,
				@W9,
				@YourAccountNum,
				@IsPrimary1,
				@PartyId1,
				@RecId1,
				@RecVersion1,
				@Shared1,
				@Status1,
				@ValidFromDateTime1,
				@ValidToDateTime1,
				@AddressRecId2,
				@PartyAddressRelationshipRecId2,
				@RecId2,
				@RecVersion2,
				@RefCompanyId2,
				@Address3,
				@AddressComplement3,
				@AddressNumber3,
				@AddrRecId3,
				@AddrTableId3,
				@City3,
				@CountryRegionId3,
				@DeliveryCustVendCategory3,
				@ExciseType_IN3,
				@RecId3,
				@RecVersion3,
				@ShipCarrierBlindShipment3,
				@ShipCarrierResidential3,
				@State3,
				@Street3,
				@TimeZone3,
				@type3,
				@ZipCode3,
				@DistrictName3,
				@OffsetAccount,
				@City4,
				@CountryRegionId4,
				@DeliveryCustVendCategory4,
				@ExciseType_IN4,
				@Name4,
				@RecId4,
				@RecVersion4,
				@ShipCarrierBlindShipment4,
				@State4,
				@ShipCarrierResidential4,
				@Street4,
				@type4,
				@ZipCode4,
				@AddressRecId3,
				@PartyAddressRelationshipRecId3,
				@AddressComplement4,
				@AddressNumber4,
				@AddrRecId4,
				@AddrTableId4,
				@Address4,
				@RefCompanyId3,
				@ValidToDateTime2,
				@ValidFromDateTime2,
				@Status2,
				@Shared2,
				@AddressComplement,
				@City,
				@CountryRegionId,
				@DeliveryVendCNPJCPFNum,
				@DeliveryVendIENum,
				@PANNumber_IN,
				@PartyId2,
				@IsPrimary2,
				@ZipCode,
				@TKR_Name,
				@TKR_Address,
				@Street,
				@Address,
				@State,
				@AddressNumber,
				@TimeZone4,
				@BankAccount,
				@DistrictName,
				@TaxWithholdGroup,
				@DistrictName4,
				@DeliveryCustVendCNPJCPFNum4,
				@DeliveryCustVendIENum4,
				@County,
				@County4,
				@Dt_Envio_ATL,
				@Dt_Atualiza_ATL,
				@NameKana,
				@ContactPersonId,
				@Email,
				@Phone,
				@County3,
				@Name3,
				@CellularPhone,
				@IsPrimary4,
				@PartyId4,
				@Shared4,
				@Status4,
				@ValidFromDateTime4,
				@ValidToDateTime4,
				@AddressRecId5,
				@PartyAddressRelationshipRecId5,
				@RecId5,
				@RecVersion5,
				@RefCompanyId5,
				@Address6,
				@AddressComplement6,
				@AddressNumber6,
				@AddrRecId6,
				@AddrTableId6,
				@City6,
				@CountryRegionId6,
				@DeliveryCustVendCategory6,
				@ExciseType_IN6,
				@RecId6,
				@RecVersion6,
				@ShipCarrierBlindShipment6,
				@ShipCarrierResidential6,
				@State6,
				@Street6,
				@TimeZone6,
				@type6,
				@ZipCode6,
				@CustStatGroupId,
				@InvoiceModel_BR,
				@numberSequenceGroup,
				@VendInvoiceType,
				@CCMnUM,
				@PhoneLocal,
				@DistrictName6,
				@TeleFax,
				@Dimensao8,
				@URL,
				@Pager,
				@BirthDate,
				@PaymSpec,
				@OrgId,
				@AccountStatement,
				@CreatedDateTime,
				@CustCategory,
				@CustFinalUser,
				@CustGroup,
				@DeliveryCustCategory,
				@ForeignCustomer_IN,
				@GiroType,
				@GiroTypeAccountStatement,
				@GiroTypeCollectionletter,
				@GiroTypeFreeTextInvoice,
				@GiroTypeInterestNote,
				@GiroTypeProjInvoice,
				@InterCompanyAllowIndirectCreation,
				@InterCompanyAutoCreateOrders,
				@InterCompanyDirectDelivery,
				@InvoiceAddress,
				@MandatoryCreditLimit,
				@OneTimeCustomer,
				@PreferentialCustomer_IN,
				@RFIDCaseTagging,
				@RFIDItemTagging,
				@RFIDPalletTagging,
				@ShipCarrierBlindShipment,
				@ShipCarrierFuelSurcharge,
				@Suframa,
				@SuframaPISCOFINS,
				@TaxWithholdCalculate_IN,
				@VendItemGroupId,
				@Tax1099RegNum,
				@DBA,
				@CustAccount,
				@Phone3,
				@Email3,
				@BankCentralBankPurposeCode,
				@ResidenceForeignCountryRegionId,
				@IsPrimary7,
				@PartyId7,
				@RecId7,
				@RecVersion7,
				@Shared7,
				@Status7,
				@ValidFromDateTime7,
				@ValidToDateTime7,
				@AddressRecId8,
				@PartyAddressRelationshipRecId8,
				@RecId8,
				@RecVersion8,
				@RefCompanyId8,
				@Address9,
				@AddressComplement9,
				@AddressNumber9,
				@AddrRecId9,
				@AddrTableId9,
				@City9,
				@CountryRegionId9,
				@DeliveryCustVendCategory9,
				@DistrictName9,
				@ExciseType_IN9,
				@RecId9,
				@RecVersion9,
				@ShipCarrierBlindShipment9,
				@ShipCarrierResidential9,
				@State9,
				@Street9,
				@type9,
				@ZipCode9,
				@IsPrimary10,
				@PartyId10,
				@RecId10,
				@RecVersion10,
				@Shared10,
				@Status10,
				@ValidFromDateTime10,
				@ValidToDateTime10,
				@AddressRecId11,
				@PartyAddressRelationshipRecId11,
				@RecId11,
				@RecVersion11,
				@RefCompanyId11,
				@Address12,
				@AddressComplement12,
				@AddressNumber12,
				@AddrRecId12,
				@AddrTableId12,
				@City12,
				@CountryRegionId12,
				@DeliveryCustVendCategory12,
				@DistrictName12,
				@ExciseType_IN12,
				@RecId12,
				@RecVersion12,
				@ShipCarrierBlindShipment12,
				@ShipCarrierResidential12,
				@State12,
				@Street12,
				@type12,
				@ZipCode12,
				@IsPrimary13,
				@PartyId13,
				@RecId13,
				@RecVersion13,
				@Shared13,
				@Status13,
				@ValidFromDateTime13,
				@ValidToDateTime13,
				@AddressRecId14,
				@PartyAddressRelationshipRecId14,
				@RecId14,
				@RecVersion14,
				@RefCompanyId14,
				@Address15,
				@AddressComplement15,
				@AddressNumber15,
				@AddrRecId15,
				@AddrTableId15,
				@City15,
				@CountryRegionId15,
				@DeliveryCustVendCategory15,
				@DistrictName15,
				@ExciseType_IN15,
				@RecId15,
				@RecVersion15,
				@ShipCarrierBlindShipment15,
				@ShipCarrierResidential15,
				@State15,
				@Street15,
				@type15,
				@ZipCode15,
				@IsPrimary16,
				@PartyId16,
				@RecId16,
				@RecVersion16,
				@Shared16,
				@Status16,
				@ValidFromDateTime16,
				@ValidToDateTime16,
				@AddressRecId17,
				@PartyAddressRelationshipRecId17,
				@RecId17,
				@RecVersion17,
				@RefCompanyId17,
				@Address18,
				@AddressComplement18,
				@AddressNumber18,
				@AddrRecId18,
				@AddrTableId18,
				@City18,
				@CountryRegionId18,
				@DeliveryCustVendCategory18,
				@DistrictName18,
				@ExciseType_IN18,
				@RecId18,
				@RecVersion18,
				@ShipCarrierBlindShipment18,
				@ShipCarrierResidential18,
				@State18,
				@Street18,
				@type18,
				@ZipCode18,
				@IsPrimary19,
				@PartyId19,
				@RecId19,
				@RecVersion19,
				@Shared19,
				@Status19,
				@ValidFromDateTime19,
				@ValidToDateTime19,
				@AddressRecId20,
				@PartyAddressRelationshipRecId20,
				@RecId20,
				@RecVersion20,
				@RefCompanyId20,
				@Address21,
				@AddressComplement21,
				@AddressNumber21,
				@AddrRecId21,
				@AddrTableId21,
				@City21,
				@CountryRegionId21,
				@DeliveryCustVendCategory21,
				@DistrictName21,
				@ExciseType_IN21,
				@RecId21,
				@RecVersion21,
				@ShipCarrierBlindShipment21,
				@ShipCarrierResidential21,
				@State21,
				@Street21,
				@type21,
				@ZipCode21,
				@IsPrimary22,
				@PartyId22,
				@RecId22,
				@RecVersion22,
				@Shared22,
				@Status22,
				@ValidFromDateTime22,
				@ValidToDateTime22,
				@AddressRecId23,
				@PartyAddressRelationshipRecId23,
				@RecId23,
				@RecVersion23,
				@RefCompanyId23,
				@Address24,
				@AddressComplement24,
				@AddressNumber24,
				@AddrRecId24,
				@AddrTableId24,
				@City24,
				@CountryRegionId24,
				@DeliveryCustVendCategory24,
				@DistrictName24,
				@ExciseType_IN24,
				@RecId24,
				@RecVersion24,
				@ShipCarrierBlindShipment24,
				@ShipCarrierResidential24,
				@State24,
				@Street24,
				@type24,
				@ZipCode24,
				@IsPrimary25,
				@PartyId25,
				@RecId25,
				@RecVersion25,
				@Shared25,
				@Status25,
				@ValidFromDateTime25,
				@ValidToDateTime25,
				@AddressRecId26,
				@PartyAddressRelationshipRecId26,
				@RecId26,
				@RecVersion26,
				@RefCompanyId26,
				@Address27,
				@AddressComplement27,
				@AddressNumber27,
				@AddrRecId27,
				@AddrTableId27,
				@City27,
				@CountryRegionId27,
				@DeliveryCustVendCategory27,
				@DistrictName27,
				@ExciseType_IN27,
				@RecId27,
				@RecVersion27,
				@ShipCarrierBlindShipment27,
				@ShipCarrierResidential27,
				@State27,
				@Street27,
				@type27,
				@ZipCode27,
				@IsPrimary28,
				@PartyId28,
				@RecId28,
				@RecVersion28,
				@Shared28,
				@Status28,
				@ValidFromDateTime28,
				@ValidToDateTime28,
				@AddressRecId29,
				@PartyAddressRelationshipRecId29,
				@RecId29,
				@RecVersion29,
				@RefCompanyId29,
				@Address30,
				@AddressComplement30,
				@AddressNumber30,
				@AddrRecId30,
				@AddrTableId30,
				@City30,
				@CountryRegionId30,
				@DeliveryCustVendCategory30,
				@DistrictName30,
				@ExciseType_IN30,
				@RecId30,
				@RecVersion30,
				@ShipCarrierBlindShipment30,
				@ShipCarrierResidential30,
				@State30,
				@Street30,
				@type30,
				@ZipCode30,
				@IsPrimary31,
				@PartyId31,
				@RecId31,
				@RecVersion31,
				@Shared31,
				@Status31,
				@ValidFromDateTime31,
				@ValidToDateTime31,
				@AddressRecId32,
				@PartyAddressRelationshipRecId32,
				@RecId32,
				@RecVersion32,
				@RefCompanyId32,
				@Address33,
				@AddressComplement33,
				@AddressNumber33,
				@AddrRecId33,
				@AddrTableId33,
				@City33,
				@CountryRegionId33,
				@DeliveryCustVendCategory33,
				@DistrictName33,
				@ExciseType_IN33,
				@RecId33,
				@RecVersion33,
				@ShipCarrierBlindShipment33,
				@ShipCarrierResidential33,
				@State33,
				@Street33,
				@type33,
				@ZipCode33,
				@IsPrimary34,
				@PartyId34,
				@RecId34,
				@RecVersion34,
				@Shared34,
				@Status34,
				@ValidFromDateTime34,
				@ValidToDateTime34,
				@AddressRecId35,
				@PartyAddressRelationshipRecId35,
				@RecId35,
				@RecVersion35,
				@RefCompanyId35,
				@Address36,
				@AddressComplement36,
				@AddressNumber36,
				@AddrRecId36,
				@AddrTableId36,
				@City36,
				@CountryRegionId36,
				@DeliveryCustVendCategory36,
				@DistrictName36,
				@ExciseType_IN36,
				@RecId36,
				@RecVersion36,
				@ShipCarrierBlindShipment36,
				@ShipCarrierResidential36,
				@State36,
				@Street36,
				@type36,
				@ZipCode36,
				@IsPrimary37,
				@PartyId37,
				@RecId37,
				@RecVersion37,
				@Shared37,
				@Status37,
				@ValidFromDateTime37,
				@ValidToDateTime37,
				@AddressRecId38,
				@PartyAddressRelationshipRecId38,
				@RecId38,
				@RecVersion38,
				@RefCompanyId38,
				@Address39,
				@AddressComplement39,
				@AddressNumber39,
				@AddrRecId39,
				@AddrTableId39,
				@City39,
				@CountryRegionId39,
				@DeliveryCustVendCategory39,
				@DistrictName39,
				@ExciseType_IN39,
				@RecId39,
				@RecVersion39,
				@ShipCarrierBlindShipment39,
				@ShipCarrierResidential39,
				@State39,
				@Street39,
				@type39,
				@ZipCode39,
				@IsPrimary40,
				@PartyId40,
				@RecId40,
				@RecVersion40,
				@Shared40,
				@Status40,
				@ValidFromDateTime40,
				@ValidToDateTime40,
				@AddressRecId41,
				@PartyAddressRelationshipRecId41,
				@RecId41,
				@RecVersion41,
				@RefCompanyId41,
				@Address42,
				@AddressComplement42,
				@AddressNumber42,
				@AddrRecId42,
				@AddrTableId42,
				@City42,
				@CountryRegionId42,
				@DeliveryCustVendCategory42,
				@DistrictName42,
				@ExciseType_IN42,
				@RecId42,
				@RecVersion42,
				@ShipCarrierBlindShipment42,
				@ShipCarrierResidential42,
				@State42,
				@Street42,
				@type42,
				@ZipCode42,
				@IsPrimary43,
				@PartyId43,
				@RecId43,
				@RecVersion43,
				@Shared43,
				@Status43,
				@ValidFromDateTime43,
				@ValidToDateTime43,
				@AddressRecId44,
				@PartyAddressRelationshipRecId44,
				@RecId44,
				@RecVersion44,
				@RefCompanyId44,
				@Address45,
				@AddressComplement45,
				@AddressNumber45,
				@AddrRecId45,
				@AddrTableId45,
				@City45,
				@CountryRegionId45,
				@DeliveryCustVendCategory45,
				@DistrictName45,
				@ExciseType_IN45,
				@RecId45,
				@RecVersion45,
				@ShipCarrierBlindShipment45,
				@ShipCarrierResidential45,
				@State45,
				@Street45,
				@type45,
				@ZipCode45,
				@IsPrimary46,
				@PartyId46,
				@RecId46,
				@RecVersion46,
				@Shared46,
				@Status46,
				@ValidFromDateTime46,
				@ValidToDateTime46,
				@AddressRecId47,
				@PartyAddressRelationshipRecId47,
				@RecId47,
				@RecVersion47,
				@RefCompanyId47,
				@Address48,
				@AddressComplement48,
				@AddressNumber48,
				@AddrRecId48,
				@AddrTableId48,
				@City48,
				@CountryRegionId48,
				@DeliveryCustVendCategory48,
				@DistrictName48,
				@ExciseType_IN48,
				@RecId48,
				@RecVersion48,
				@ShipCarrierBlindShipment48,
				@ShipCarrierResidential48,
				@State48,
				@Street48,
				@type48,
				@ZipCode48,
				@IsPrimary49,
				@PartyId49,
				@RecId49,
				@RecVersion49,
				@Shared49,
				@Status49,
				@ValidFromDateTime49,
				@ValidToDateTime49,
				@AddressRecId50,
				@PartyAddressRelationshipRecId50,
				@RecId50,
				@RecVersion50,
				@RefCompanyId50,
				@VATNum
                )
               
            END
            
            SELECT @AccountNum AS ReturnValue;
        
        COMMIT TRAN
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN
        SELECT ERROR_MESSAGE() AS ReturnValue;
    END CATCH
END
GO
