SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--sp_help AX_XML_Customer_Recebido
CREATE PROCEDURE [dbo].[pAX_XML_Customer_Recebido_InsUpd]
(
    @_DocumentHash VARCHAR(200),
    @AccountNum VARCHAR(200),
    @File VARCHAR(200),
    @Created_Date VARCHAR(200),
    @AccountStatement VARCHAR(200),
    @Address VARCHAR(200),
    @AddressComplement VARCHAR(200),
    @AddressNumber VARCHAR(200),
    @Blocked VARCHAR(200),
    @CitCustClientCode VARCHAR(200),
    @City VARCHAR(200),
    @CNPJCPFNum VARCHAR(200),
    @CompanyType_MX VARCHAR(200),
    @CountryRegionId VARCHAR(200),
    @CreatedDateTime VARCHAR(200),
    @Currency VARCHAR(200),
    @CustCategory VARCHAR(200),
    @CustFinalUser VARCHAR(200),
    @CustGroup VARCHAR(200),
    @DeliveryCustCategory VARCHAR(200),
    @DeliveryCustCNPJCPFNum VARCHAR(200),
    @DeliveryCustIENum VARCHAR(200),
    @Dimensao1 VARCHAR(200),
    @Dimensao2 VARCHAR(200),
    @Dimensao3 VARCHAR(200),
    @Dimensao4 VARCHAR(200),
    @Dimensao5 VARCHAR(200),
    @Dimensao6 VARCHAR(200),
    @Dimensao7 VARCHAR(200),
    @DistrictName VARCHAR(200),
    @EstablishmentType VARCHAR(200),
    @ForeignCustomer_IN VARCHAR(200),
    @GiroType VARCHAR(200),
    @GiroTypeAccountStatement VARCHAR(200),
    @GiroTypeCollectionletter VARCHAR(200),
    @GiroTypeFreeTextInvoice VARCHAR(200),
    @GiroTypeInterestNote VARCHAR(200),
    @GiroTypeProjInvoice VARCHAR(200),
    @ICMSContributor VARCHAR(200),
    @IENum VARCHAR(200),
    @InclTax VARCHAR(200),
    @InterCompanyAllowIndirectCreation VARCHAR(200),
    @InterCompanyAutoCreateOrders VARCHAR(200),
    @InterCompanyDirectDelivery VARCHAR(200),
    @InvoiceAddress VARCHAR(200),
    @LanguageId VARCHAR(200),
    @MandatoryCreditLimit VARCHAR(200),
    @ModifiedDateTime VARCHAR(200),
    @Name VARCHAR(200),
    @NameAlias VARCHAR(200),
    @NatureOfAssessee_IN VARCHAR(200),
    @OneTimeCustomer VARCHAR(200),
    @OurAccountNum VARCHAR(200),
    @PANNumber_IN VARCHAR(200),
    @PANStatus_IN VARCHAR(200),
    @PartyCountry VARCHAR(200),
    @PartyId VARCHAR(200),
    @PartyState VARCHAR(200),
    @PartyType VARCHAR(200),
    @PaymMode VARCHAR(200),
    @PaymTermId VARCHAR(200),
    @PreferentialCustomer_IN VARCHAR(200),
    @RecId VARCHAR(200),
    @RecVersion VARCHAR(200),
    @RFIDCaseTagging VARCHAR(200),
    @RFIDItemTagging VARCHAR(200),
    @RFIDPalletTagging VARCHAR(200),
    @ServiceCodeOnDlvAddress VARCHAR(200),
    @ShipCarrierBlindShipment VARCHAR(200),
    @ShipCarrierFuelSurcharge VARCHAR(200),
    @State VARCHAR(200),
    @Street VARCHAR(500),
    @Suframa VARCHAR(200),
    @SuframaPISCOFINS VARCHAR(200),
    @TaxGroup VARCHAR(200),
    @TaxWithholdCalculate_IN VARCHAR(200),
    @TKR_Address VARCHAR(200),
    @TKR_ElecInvoice VARCHAR(200),
    @TKR_Name VARCHAR(200),
    @TKR_RetailAlcoholic VARCHAR(200),
    @TKR_VATBizType VARCHAR(200),
    @TKR_VATPrintType VARCHAR(200),
    @TKR_WholesaleAlcoholic VARCHAR(200),
    @ZipCode VARCHAR(200),
    @IsPrimary1 VARCHAR(200),
    @PartyId1 VARCHAR(200),
    @RecId1 VARCHAR(200),
    @RecVersion1 VARCHAR(200),
    @Shared1 VARCHAR(200),
    @Status1 VARCHAR(200),
    @ValidFromDateTime1 VARCHAR(200),
    @ValidToDateTime1 VARCHAR(200),
    @IsPrimary2 VARCHAR(200),
    @PartyId2 VARCHAR(200),
    @RecId2 VARCHAR(200),
    @RecVersion2 VARCHAR(200),
    @Shared2 VARCHAR(200),
    @Status2 VARCHAR(200),
    @ValidFromDateTime2 VARCHAR(200),
    @ValidToDateTime2 VARCHAR(200),
    @AddressRecId3 VARCHAR(200),
    @PartyAddressRelationshipRecId3 VARCHAR(200),
    @RecId3 VARCHAR(200),
    @RecVersion3 VARCHAR(200),
    @RefCompanyId3 VARCHAR(200),
    @Address4 VARCHAR(200),
    @AddressComplement4 VARCHAR(200),
    @AddressNumber4 VARCHAR(200),
    @AddrRecId4 VARCHAR(200),
    @AddrTableId4 VARCHAR(200),
    @City4 VARCHAR(200),
    @CountryRegionId4 VARCHAR(200),
    @DeliveryCustVendCategory4 VARCHAR(200),
    @DistrictName4 VARCHAR(200),
    @ExciseType_IN4 VARCHAR(200),
    @Name4 VARCHAR(200),
    @RecId4 VARCHAR(200),
    @RecVersion4 VARCHAR(200),
    @ShipCarrierBlindShipment4 VARCHAR(200),
    @ShipCarrierResidential4 VARCHAR(200),
    @State4 VARCHAR(200),
    @Street4 VARCHAR(500),
    @TimeZone4 VARCHAR(200),
    @type4 VARCHAR(200),
    @ZipCode4 VARCHAR(200),
    @County VARCHAR(200),
    @County4 VARCHAR(200),
    @BankAccount VARCHAR(200),
    @ZipCode3 VARCHAR(200),
    @type3 VARCHAR(200),
    @Street3 VARCHAR(500),
    @State3 VARCHAR(200),
    @ShipCarrierResidential3 VARCHAR(200),
    @ShipCarrierBlindShipment3 VARCHAR(200),
    @ExciseType_IN3 VARCHAR(200),
    @DistrictName3 VARCHAR(200),
    @DeliveryCustVendCategory3 VARCHAR(200),
    @County3 VARCHAR(200),
    @CountryRegionId3 VARCHAR(200),
    @City3 VARCHAR(200),
    @AddrTableId3 VARCHAR(200),
    @AddressComplement3 VARCHAR(200),
    @AddrRecId3 VARCHAR(200),
    @AddressNumber3 VARCHAR(200),
    @Address3 VARCHAR(max),
    @RefCompanyId2 VARCHAR(200),
    @PartyAddressRelationshipRecId2 VARCHAR(200),
    @AddressRecId2 VARCHAR(200),
    @TimeZone3 VARCHAR(200),
    @Name3 VARCHAR(200),
    @ZipCode5 VARCHAR(200),
    @type5 VARCHAR(200),
    @Street5 VARCHAR(500),
    @State5 VARCHAR(200),
    @ShipCarrierResidential5 VARCHAR(200),
    @RecId5 VARCHAR(200),
    @Name5 VARCHAR(200),
    @ExciseType_IN5 VARCHAR(200),
    @RecVersion5 VARCHAR(200),
    @ShipCarrierBlindShipment5 VARCHAR(200),
    @DistrictName5 VARCHAR(200),
    @DeliveryCustVendCategory5 VARCHAR(200),
    @CountryRegionId5 VARCHAR(200),
    @City5 VARCHAR(200),
    @AddrTableId5 VARCHAR(200),
    @AddrRecId5 VARCHAR(200),
    @AddressNumber5 VARCHAR(200),
    @AddressComplement5 VARCHAR(200),
    @Address5 VARCHAR(200),
    @RefCompanyId4 VARCHAR(200),
    @PartyAddressRelationshipRecId4 VARCHAR(200),
    @AddressRecId4 VARCHAR(200),
    @ValidToDateTime3 VARCHAR(200),
    @ValidFromDateTime3 VARCHAR(200),
    @Shared3 VARCHAR(200),
    @IsPrimary3 VARCHAR(200),
    @PartyId3 VARCHAR(200),
    @Status3 VARCHAR(200),
    @IsPrimary4 VARCHAR(200),
    @PartyId4 VARCHAR(200),
    @Shared4 VARCHAR(200),
    @Status4 VARCHAR(200),
    @ValidFromDateTime4 VARCHAR(200),
    @ValidToDateTime4 VARCHAR(200),
    @IsPrimary5 VARCHAR(200),
    @PartyId5 VARCHAR(200),
    @Shared5 VARCHAR(200),
    @Status5 VARCHAR(200),
    @ValidFromDateTime5 VARCHAR(200),
    @ValidToDateTime5 VARCHAR(200),
    @AddressRecId6 VARCHAR(200),
    @PartyAddressRelationshipRecId6 VARCHAR(200),
    @RecId6 VARCHAR(200),
    @RecVersion6RecId6 VARCHAR(200),
    @RefCompanyId6 VARCHAR(200),
    @Address7 VARCHAR(200),
    @AddressComplement7 VARCHAR(200),
    @AddressNumber7 VARCHAR(200),
    @AddrRecId7 VARCHAR(200),
    @AddrTableId7 VARCHAR(200),
    @City7 VARCHAR(200),
    @CountryRegionId7 VARCHAR(200),
    @DeliveryCustVendCategory7 VARCHAR(200),
    @DistrictName7 VARCHAR(200),
    @ExciseType_IN7 VARCHAR(200),
    @Name7 VARCHAR(200),
    @RecId7 VARCHAR(200),
    @RecVersion7 VARCHAR(200),
    @ShipCarrierResidential7 VARCHAR(200),
    @State7 VARCHAR(200),
    @Street7 VARCHAR(500),
    @type7 VARCHAR(200),
    @ZipCode7 VARCHAR(200),
    @RecVersion6 VARCHAR(200),
    @ShipCarrierBlindShipment7 VARCHAR(200),
    @Dt_Envio_ATL DATETIME,
    @Phone VARCHAR(200),
    @Dt_Atualiza_ATL DATETIME,
    @ContactPersonId VARCHAR(200),
    @Email VARCHAR(200),
    @AddressRecId5 VARCHAR(200),
    @PartyAddressRelationshipRecId5 VARCHAR(200),
    @RefCompanyId5 VARCHAR(200),
    @Address6 VARCHAR(200),
    @AddressComplement6 VARCHAR(200),
    @AddressNumber6 VARCHAR(200),
    @AddrRecId6 VARCHAR(200),
    @AddrTableId6 VARCHAR(200),
    @City6 VARCHAR(200),
    @CountryRegionId6 VARCHAR(200),
    @DeliveryCustVendCategory6 VARCHAR(200),
    @DistrictName6 VARCHAR(200),
    @ExciseType_IN6 VARCHAR(200),
    @type6 VARCHAR(200),
    @State6 VARCHAR(200),
    @Street6 VARCHAR(200),
    @TimeZone6 VARCHAR(200),
    @ZipCode6 VARCHAR(200),
    @ShipCarrierBlindShipment6 VARCHAR(200),
    @ShipCarrierResidential6 VARCHAR(200),
    @CellularPhone VARCHAR(200),
    @PhoneLocal VARCHAR(200),
    @DeliveryCustVendCNPJCPFNum3 VARCHAR(200),
    @DeliveryCustVendIENum3 VARCHAR(200),
    @CCMNum VARCHAR(200),
    @SMS VARCHAR(200),
    @TeleFax VARCHAR(200),
    @Phone3 VARCHAR(200),
    @Dimensao8 VARCHAR(200),
    @NameKana VARCHAR(200),
    @URL VARCHAR(200),
    @Memo VARCHAR(200),
    @Pager VARCHAR(200),
    @CreditMax VARCHAR(200),
    @CustItemGroupId VARCHAR(200),
    @TIN_IN VARCHAR(200),
    @IdentificationNumber VARCHAR(200),
    @TeleFax3 VARCHAR(200),
    @Email3 VARCHAR(200),
    @OrgId VARCHAR(200),
    @VendAccount VARCHAR(200),
    @County6 VARCHAR(200),
    @Name6 VARCHAR(200),
    @Phone6 VARCHAR(200),
    @PhoneLocal6 VARCHAR(200),
    @Telex6 VARCHAR(200),
    @IsPrimary7 VARCHAR(200),
    @PartyId7 VARCHAR(200),
    @Shared7 VARCHAR(200),
    @Status7 VARCHAR(200),
    @ValidFromDateTime7 VARCHAR(200),
    @ValidToDateTime7 VARCHAR(200),
    @AddressRecId8 VARCHAR(200),
    @PartyAddressRelationshipRecId8 VARCHAR(200),
    @RecId8 VARCHAR(200),
    @RecVersion8 VARCHAR(200),
    @RefCompanyId8 VARCHAR(200),
    @Address9 VARCHAR(200),
    @AddrRecId9 VARCHAR(200),
    @AddrTableId9 VARCHAR(200),
    @City9 VARCHAR(200),
    @CountryRegionId9 VARCHAR(200),
    @County9 VARCHAR(200),
    @DeliveryCustVendCategory9 VARCHAR(200),
    @ExciseType_IN9 VARCHAR(200),
    @Name9 VARCHAR(200),
    @RecId9 VARCHAR(200),
    @RecVersion9 VARCHAR(200),
    @ShipCarrierBlindShipment9 VARCHAR(200),
    @ShipCarrierResidential9 VARCHAR(200),
    @State9 VARCHAR(200),
    @Street9 VARCHAR(200),
    @type9 VARCHAR(200),
    @ZipCode9 VARCHAR(200),
    @InvoiceAccount VARCHAR(200),
    @CommissionGroup VARCHAR(200),
    @CreditRating VARCHAR(200),
    @IsPrimary10 VARCHAR(200),
    @PartyId10 VARCHAR(200),
    @RecId10 VARCHAR(200),
    @RecVersion10 VARCHAR(200),
    @Shared10 VARCHAR(200),
    @Status10 VARCHAR(200),
    @ValidFromDateTime10 VARCHAR(200),
    @ValidToDateTime10 VARCHAR(200),
    @AddressRecId11 VARCHAR(200),
    @PartyAddressRelationshipRecId11 VARCHAR(200),
    @RecId11 VARCHAR(200),
    @RecVersion11 VARCHAR(200),
    @RefCompanyId11 VARCHAR(200),
    @Address12 VARCHAR(200),
    @AddrRecId12 VARCHAR(200),
    @AddrTableId12 VARCHAR(200),
    @CountryRegionId12 VARCHAR(200),
    @DeliveryCustVendCategory12 VARCHAR(200),
    @ExciseType_IN12 VARCHAR(200),
    @RecId12 VARCHAR(200),
    @RecVersion12 VARCHAR(200),
    @ShipCarrierBlindShipment12 VARCHAR(200),
    @ShipCarrierResidential12 VARCHAR(200),
    @type1 VARCHAR(200),
    @VATNum VARCHAR(200),
    @SalesGroup VARCHAR(200),
    @AddressComplement9 VARCHAR(200),
    @AddressNumber9 VARCHAR(200),
    @DistrictName9 VARCHAR(200),
    @type12 VARCHAR(200),
    @City12 VARCHAR(200),
    @State12 VARCHAR(200),
    @Street12 VARCHAR(200),
    @ZipCode12 VARCHAR(200)
)
AS
BEGIN
    BEGIN TRY
        BEGIN TRAN            

            IF EXISTS(SELECT AccountNum FROM AX_XML_Customer_Recebido WHERE AccountNum = @AccountNum)
            BEGIN
                UPDATE 
                    AX_XML_Customer_Recebido
                SET
     --               _DocumentHash = @_DocumentHash,
					--[File] = @File,
					--[Created Date] = @Created_Date,
					--AccountStatement = @AccountStatement,
					--[Address] = @Address,
					--AddressComplement = @AddressComplement,
					--AddressNumber = @AddressNumber,
					Blocked = @Blocked,
					CitCustClientCode = @CitCustClientCode,
					--City = @City,
					CNPJCPFNum = @CNPJCPFNum,
					--CompanyType_MX = @CompanyType_MX,
					--CountryRegionId = @CountryRegionId,
					--CreatedDateTime = @CreatedDateTime,
					--Currency = @Currency,
					--CustCategory = @CustCategory,
					--CustFinalUser = @CustFinalUser,
					CustGroup = @CustGroup,
					--DeliveryCustCategory = @DeliveryCustCategory,
					--DeliveryCustCNPJCPFNum = @DeliveryCustCNPJCPFNum,
					--DeliveryCustIENum = @DeliveryCustIENum,
					Dimensao1 = @Dimensao1,
					Dimensao2 = @Dimensao2,
					Dimensao3 = @Dimensao3,
					Dimensao4 = @Dimensao4,
					Dimensao5 = @Dimensao5,
					Dimensao6 = @Dimensao6,
					Dimensao7 = @Dimensao7,
					--DistrictName = @DistrictName,
					--EstablishmentType = @EstablishmentType,
					--ForeignCustomer_IN = @ForeignCustomer_IN,
					--GiroType = @GiroType,
					--GiroTypeAccountStatement = @GiroTypeAccountStatement,
					--GiroTypeCollectionletter = @GiroTypeCollectionletter,
					--GiroTypeFreeTextInvoice = @GiroTypeFreeTextInvoice,
					--GiroTypeInterestNote = @GiroTypeInterestNote,
					--GiroTypeProjInvoice = @GiroTypeProjInvoice,
					--ICMSContributor = @ICMSContributor,
					IENum = @IENum,
					--InclTax = @InclTax,
					--InterCompanyAllowIndirectCreation = @InterCompanyAllowIndirectCreation,
					--InterCompanyAutoCreateOrders = @InterCompanyAutoCreateOrders,
					--InterCompanyDirectDelivery = @InterCompanyDirectDelivery,
					--InvoiceAddress = @InvoiceAddress,
					--LanguageId = @LanguageId,
					--MandatoryCreditLimit = @MandatoryCreditLimit,
					--ModifiedDateTime = @ModifiedDateTime,
					[Name] = @Name,
					NameAlias = @NameAlias,
					--NatureOfAssessee_IN = @NatureOfAssessee_IN,
					--OneTimeCustomer = @OneTimeCustomer,
					OurAccountNum = @OurAccountNum,
					--PANNumber_IN = @PANNumber_IN,
					--PANStatus_IN = @PANStatus_IN,
					--PartyCountry = @PartyCountry,
					--PartyId = @PartyId,
					--PartyState = @PartyState,
					--PartyType = @PartyType,
					--PaymMode = @PaymMode,
					--PaymTermId = @PaymTermId,
					--PreferentialCustomer_IN = @PreferentialCustomer_IN,
					--RecId = @RecId,
					--RecVersion = @RecVersion,
					--RFIDCaseTagging = @RFIDCaseTagging,
					--RFIDItemTagging = @RFIDItemTagging,
					--RFIDPalletTagging = @RFIDPalletTagging,
					--ServiceCodeOnDlvAddress = @ServiceCodeOnDlvAddress,
					--ShipCarrierBlindShipment = @ShipCarrierBlindShipment,
					--ShipCarrierFuelSurcharge = @ShipCarrierFuelSurcharge,
					--[State] = @State,
					--Street = @Street,
					--Suframa = @Suframa,
					--SuframaPISCOFINS = @SuframaPISCOFINS,
					TaxGroup = @TaxGroup,
					--TaxWithholdCalculate_IN = @TaxWithholdCalculate_IN,
					--TKR_Address = @TKR_Address,
					--TKR_ElecInvoice = @TKR_ElecInvoice,
					--TKR_Name = @TKR_Name,
					--TKR_RetailAlcoholic = @TKR_RetailAlcoholic,
					--TKR_VATBizType = @TKR_VATBizType,
					--TKR_VATPrintType = @TKR_VATPrintType,
					--TKR_WholesaleAlcoholic = @TKR_WholesaleAlcoholic,
					--ZipCode = @ZipCode,
					--IsPrimary1 = @IsPrimary1,
					--PartyId1 = @PartyId1,
					--RecId1 = @RecId1,
					--RecVersion1 = @RecVersion1,
					--Shared1 = @Shared1,
					--Status1 = @Status1,
					--ValidFromDateTime1 = @ValidFromDateTime1,
					--ValidToDateTime1 = @ValidToDateTime1,
					--IsPrimary2 = @IsPrimary2,
					--PartyId2 = @PartyId2,
					--RecId2 = @RecId2,
					--RecVersion2 = @RecVersion2,
					--Shared2 = @Shared2,
					--Status2 = @Status2,
					--ValidFromDateTime2 = @ValidFromDateTime2,
					--ValidToDateTime2 = @ValidToDateTime2,
					--AddressRecId3 = @AddressRecId3,
					--PartyAddressRelationshipRecId3 = @PartyAddressRelationshipRecId3,
					--RecId3 = @RecId3,
					--RecVersion3 = @RecVersion3,
					--RefCompanyId3 = @RefCompanyId3,
					--Address4 = @Address4,
					--AddressComplement4 = @AddressComplement4,
					--AddressNumber4 = @AddressNumber4,
					--AddrRecId4 = @AddrRecId4,
					--AddrTableId4 = @AddrTableId4,
					--City4 = @City4,
					--CountryRegionId4 = @CountryRegionId4,
					--DeliveryCustVendCategory4 = @DeliveryCustVendCategory4,
					--DistrictName4 = @DistrictName4,
					--ExciseType_IN4 = @ExciseType_IN4,
					--Name4 = @Name4,
					--RecId4 = @RecId4,
					--RecVersion4 = @RecVersion4,
					--ShipCarrierBlindShipment4 = @ShipCarrierBlindShipment4,
					--ShipCarrierResidential4 = @ShipCarrierResidential4,
					--State4 = @State4,
					--Street4 = @Street4,
					--TimeZone4 = @TimeZone4,
					--type4 = @type4,
					--ZipCode4 = @ZipCode4,
					--County = @County,
					--County4 = @County4,
					--BankAccount = @BankAccount,
					--ZipCode3 = @ZipCode3,
					--type3 = @type3,
					--Street3 = @Street3,
					--State3 = @State3,
					--ShipCarrierResidential3 = @ShipCarrierResidential3,
					--ShipCarrierBlindShipment3 = @ShipCarrierBlindShipment3,
					--ExciseType_IN3 = @ExciseType_IN3,
					--DistrictName3 = @DistrictName3,
					--DeliveryCustVendCategory3 = @DeliveryCustVendCategory3,
					--County3 = @County3,
					--CountryRegionId3 = @CountryRegionId3,
					--City3 = @City3,
					--AddrTableId3 = @AddrTableId3,
					--AddressComplement3 = @AddressComplement3,
					--AddrRecId3 = @AddrRecId3,
					--AddressNumber3 = @AddressNumber3,
					--Address3 = @Address3,
					--RefCompanyId2 = @RefCompanyId2,
					--PartyAddressRelationshipRecId2 = @PartyAddressRelationshipRecId2,
					--AddressRecId2 = @AddressRecId2,
					--TimeZone3 = @TimeZone3,
					--Name3 = @Name3,
					--ZipCode5 = @ZipCode5,
					--type5 = @type5,
					--Street5 = @Street5,
					--State5 = @State5,
					--ShipCarrierResidential5 = @ShipCarrierResidential5,
					--RecId5 = @RecId5,
					--Name5 = @Name5,
					--ExciseType_IN5 = @ExciseType_IN5,
					--RecVersion5 = @RecVersion5,
					--ShipCarrierBlindShipment5 = @ShipCarrierBlindShipment5,
					--DistrictName5 = @DistrictName5,
					--DeliveryCustVendCategory5 = @DeliveryCustVendCategory5,
					--CountryRegionId5 = @CountryRegionId5,
					--City5 = @City5,
					--AddrTableId5 = @AddrTableId5,
					--AddrRecId5 = @AddrRecId5,
					--AddressNumber5 = @AddressNumber5,
					--AddressComplement5 = @AddressComplement5,
					--Address5 = @Address5,
					--RefCompanyId4 = @RefCompanyId4,
					--PartyAddressRelationshipRecId4 = @PartyAddressRelationshipRecId4,
					--AddressRecId4 = @AddressRecId4,
					--ValidToDateTime3 = @ValidToDateTime3,
					--ValidFromDateTime3 = @ValidFromDateTime3,
					--Shared3 = @Shared3,
					--IsPrimary3 = @IsPrimary3,
					--PartyId3 = @PartyId3,
					--Status3 = @Status3,
					--IsPrimary4 = @IsPrimary4,
					--PartyId4 = @PartyId4,
					--Shared4 = @Shared4,
					--Status4 = @Status4,
					--ValidFromDateTime4 = @ValidFromDateTime4,
					--ValidToDateTime4 = @ValidToDateTime4,
					--IsPrimary5 = @IsPrimary5,
					--PartyId5 = @PartyId5,
					--Shared5 = @Shared5,
					--Status5 = @Status5,
					--ValidFromDateTime5 = @ValidFromDateTime5,
					--ValidToDateTime5 = @ValidToDateTime5,
					--AddressRecId6 = @AddressRecId6,
					--PartyAddressRelationshipRecId6 = @PartyAddressRelationshipRecId6,
					--RecId6 = @RecId6,
					--RecVersion6RecId6 = @RecVersion6RecId6,
					--RefCompanyId6 = @RefCompanyId6,
					--Address7 = @Address7,
					--AddressComplement7 = @AddressComplement7,
					--AddressNumber7 = @AddressNumber7,
					--AddrRecId7 = @AddrRecId7,
					--AddrTableId7 = @AddrTableId7,
					--City7 = @City7,
					--CountryRegionId7 = @CountryRegionId7,
					--DeliveryCustVendCategory7 = @DeliveryCustVendCategory7,
					--DistrictName7 = @DistrictName7,
					--ExciseType_IN7 = @ExciseType_IN7,
					--Name7 = @Name7,
					--RecId7 = @RecId7,
					--RecVersion7 = @RecVersion7,
					--ShipCarrierResidential7 = @ShipCarrierResidential7,
					--State7 = @State7,
					--Street7 = @Street7,
					--type7 = @type7,
					--ZipCode7 = @ZipCode7,
					--RecVersion6 = @RecVersion6,
					--ShipCarrierBlindShipment7 = @ShipCarrierBlindShipment7,
					Dt_Envio_ATL = @Dt_Envio_ATL,
					--Phone = @Phone,
					Dt_Atualiza_ATL = @Dt_Atualiza_ATL,
					--ContactPersonId = @ContactPersonId,
					--Email = @Email,
					--AddressRecId5 = @AddressRecId5,
					--PartyAddressRelationshipRecId5 = @PartyAddressRelationshipRecId5,
					--RefCompanyId5 = @RefCompanyId5,
					--Address6 = @Address6,
					--AddressComplement6 = @AddressComplement6,
					--AddressNumber6 = @AddressNumber6,
					--AddrRecId6 = @AddrRecId6,
					--AddrTableId6 = @AddrTableId6,
					--City6 = @City6,
					--CountryRegionId6 = @CountryRegionId6,
					--DeliveryCustVendCategory6 = @DeliveryCustVendCategory6,
					--DistrictName6 = @DistrictName6,
					--ExciseType_IN6 = @ExciseType_IN6,
					--type6 = @type6,
					--State6 = @State6,
					--Street6 = @Street6,
					--TimeZone6 = @TimeZone6,
					--ZipCode6 = @ZipCode6,
					--ShipCarrierBlindShipment6 = @ShipCarrierBlindShipment6,
					--ShipCarrierResidential6 = @ShipCarrierResidential6,
					--CellularPhone = @CellularPhone,
					--PhoneLocal = @PhoneLocal,
					--DeliveryCustVendCNPJCPFNum3 = @DeliveryCustVendCNPJCPFNum3,
					--DeliveryCustVendIENum3 = @DeliveryCustVendIENum3,
					--CCMNum = @CCMNum,
					--SMS = @SMS,
					--TeleFax = @TeleFax,
					--Phone3 = @Phone3,
					Dimensao8 = @Dimensao8,
					--NameKana = @NameKana,
					--[URL] = @URL,
					--Memo = @Memo,
					--Pager = @Pager,
					--CreditMax = @CreditMax,
					--CustItemGroupId = @CustItemGroupId,
					--TIN_IN = @TIN_IN,
					IdentificationNumber = @IdentificationNumber,
					--TeleFax3 = @TeleFax3,
					--Email3 = @Email3,
					--OrgId = @OrgId,
					--VendAccount = @VendAccount,
					--County6 = @County6,
					--Name6 = @Name6,
					--Phone6 = @Phone6,
					--PhoneLocal6 = @PhoneLocal6,
					--Telex6 = @Telex6,
					--IsPrimary7 = @IsPrimary7,
					--PartyId7 = @PartyId7,
					--Shared7 = @Shared7,
					--Status7 = @Status7,
					--ValidFromDateTime7 = @ValidFromDateTime7,
					--ValidToDateTime7 = @ValidToDateTime7,
					--AddressRecId8 = @AddressRecId8,
					--PartyAddressRelationshipRecId8 = @PartyAddressRelationshipRecId8,
					--RecId8 = @RecId8,
					--RecVersion8 = @RecVersion8,
					--RefCompanyId8 = @RefCompanyId8,
					--Address9 = @Address9,
					--AddrRecId9 = @AddrRecId9,
					--AddrTableId9 = @AddrTableId9,
					--City9 = @City9,
					--CountryRegionId9 = @CountryRegionId9,
					--County9 = @County9,
					--DeliveryCustVendCategory9 = @DeliveryCustVendCategory9,
					--ExciseType_IN9 = @ExciseType_IN9,
					--Name9 = @Name9,
					--RecId9 = @RecId9,
					--RecVersion9 = @RecVersion9,
					--ShipCarrierBlindShipment9 = @ShipCarrierBlindShipment9,
					--ShipCarrierResidential9 = @ShipCarrierResidential9,
					--State9 = @State9,
					--Street9 = @Street9,
					--type9 = @type9,
					--ZipCode9 = @ZipCode9,
					--InvoiceAccount = @InvoiceAccount,
					--CommissionGroup = @CommissionGroup,
					--CreditRating = @CreditRating,
					--IsPrimary10 = @IsPrimary10,
					--PartyId10 = @PartyId10,
					--RecId10 = @RecId10,
					--RecVersion10 = @RecVersion10,
					--Shared10 = @Shared10,
					--Status10 = @Status10,
					--ValidFromDateTime10 = @ValidFromDateTime10,
					--ValidToDateTime10 = @ValidToDateTime10,
					--AddressRecId11 = @AddressRecId11,
					--PartyAddressRelationshipRecId11 = @PartyAddressRelationshipRecId11,
					--RecId11 = @RecId11,
					--RecVersion11 = @RecVersion11,
					--RefCompanyId11 = @RefCompanyId11,
					--Address12 = @Address12,
					--AddrRecId12 = @AddrRecId12,
					--AddrTableId12 = @AddrTableId12,
					--CountryRegionId12 = @CountryRegionId12,
					--DeliveryCustVendCategory12 = @DeliveryCustVendCategory12,
					--ExciseType_IN12 = @ExciseType_IN12,
					--RecId12 = @RecId12,
					--RecVersion12 = @RecVersion12,
					--ShipCarrierBlindShipment12 = @ShipCarrierBlindShipment12,
					--ShipCarrierResidential12 = @ShipCarrierResidential12,
					--type1 = @type1,
					VATNum = @VATNum,
					SalesGroup = @SalesGroup
					--AddressComplement9 = @AddressComplement9,
					--AddressNumber9 = @AddressNumber9,
					--DistrictName9 = @DistrictName9,
					--type12 = @type12,
					--City12 = @City12,
					--State12 = @State12,
					--Street12 = @Street12,
					--ZipCode12 = @ZipCode12                    
                WHERE
                   AccountNum = @AccountNum                  
                
            END
            ELSE
            BEGIN
                INSERT INTO AX_XML_Customer_Recebido
                (
                    _DocumentHash,
    AccountNum,
    [File],
    [Created Date],
    AccountStatement,
    [Address],
    AddressComplement,
    AddressNumber,
    Blocked,
    CitCustClientCode,
    City,
    CNPJCPFNum,
    CompanyType_MX,
    CountryRegionId,
    CreatedDateTime,
    Currency,
    CustCategory,
    CustFinalUser,
    CustGroup,
    DeliveryCustCategory,
    DeliveryCustCNPJCPFNum,
    DeliveryCustIENum,
    Dimensao1,
    Dimensao2,
    Dimensao3,
    Dimensao4,
    Dimensao5,
    Dimensao6,
    Dimensao7,
    DistrictName,
    EstablishmentType,
    ForeignCustomer_IN,
    GiroType,
    GiroTypeAccountStatement,
    GiroTypeCollectionletter,
    GiroTypeFreeTextInvoice,
    GiroTypeInterestNote,
    GiroTypeProjInvoice,
    ICMSContributor,
    IENum,
    InclTax,
    InterCompanyAllowIndirectCreation,
    InterCompanyAutoCreateOrders,
    InterCompanyDirectDelivery,
    InvoiceAddress,
    LanguageId,
    MandatoryCreditLimit,
    ModifiedDateTime,
    [Name],
    NameAlias,
    NatureOfAssessee_IN,
    OneTimeCustomer,
    OurAccountNum,
    PANNumber_IN,
    PANStatus_IN,
    PartyCountry,
    PartyId,
    PartyState,
    PartyType,
    PaymMode,
    PaymTermId,
    PreferentialCustomer_IN,
    RecId,
    RecVersion,
    RFIDCaseTagging,
    RFIDItemTagging,
    RFIDPalletTagging,
    ServiceCodeOnDlvAddress,
    ShipCarrierBlindShipment,
    ShipCarrierFuelSurcharge,
    [State],
    Street,
    Suframa,
    SuframaPISCOFINS,
    TaxGroup,
    TaxWithholdCalculate_IN,
    TKR_Address,
    TKR_ElecInvoice,
    TKR_Name,
    TKR_RetailAlcoholic,
    TKR_VATBizType,
    TKR_VATPrintType,
    TKR_WholesaleAlcoholic,
    ZipCode,
    IsPrimary1,
    PartyId1,
    RecId1,
    RecVersion1,
    Shared1,
    Status1,
    ValidFromDateTime1,
    ValidToDateTime1,
    IsPrimary2,
    PartyId2,
    RecId2,
    RecVersion2,
    Shared2,
    Status2,
    ValidFromDateTime2,
    ValidToDateTime2,
    AddressRecId3,
    PartyAddressRelationshipRecId3,
    RecId3,
    RecVersion3,
    RefCompanyId3,
    Address4,
    AddressComplement4,
    AddressNumber4,
    AddrRecId4,
    AddrTableId4,
    City4,
    CountryRegionId4,
    DeliveryCustVendCategory4,
    DistrictName4,
    ExciseType_IN4,
    Name4,
    RecId4,
    RecVersion4,
    ShipCarrierBlindShipment4,
    ShipCarrierResidential4,
    State4,
    Street4,
    TimeZone4,
    type4,
    ZipCode4,
    County,
    County4,
    BankAccount,
    ZipCode3,
    type3,
    Street3,
    State3,
    ShipCarrierResidential3,
    ShipCarrierBlindShipment3,
    ExciseType_IN3,
    DistrictName3,
    DeliveryCustVendCategory3,
    County3,
    CountryRegionId3,
    City3,
    AddrTableId3,
    AddressComplement3,
    AddrRecId3,
    AddressNumber3,
    Address3,
    RefCompanyId2,
    PartyAddressRelationshipRecId2,
    AddressRecId2,
    TimeZone3,
    Name3,
    ZipCode5,
    type5,
    Street5,
    State5,
    ShipCarrierResidential5,
    RecId5,
    Name5,
    ExciseType_IN5,
    RecVersion5,
    ShipCarrierBlindShipment5,
    DistrictName5,
    DeliveryCustVendCategory5,
    CountryRegionId5,
    City5,
    AddrTableId5,
    AddrRecId5,
    AddressNumber5,
    AddressComplement5,
    Address5,
    RefCompanyId4,
    PartyAddressRelationshipRecId4,
    AddressRecId4,
    ValidToDateTime3,
    ValidFromDateTime3,
    Shared3,
    IsPrimary3,
    PartyId3,
    Status3,
    IsPrimary4,
    PartyId4,
    Shared4,
    Status4,
    ValidFromDateTime4,
    ValidToDateTime4,
    IsPrimary5,
    PartyId5,
    Shared5,
    Status5,
    ValidFromDateTime5,
    ValidToDateTime5,
    AddressRecId6,
    PartyAddressRelationshipRecId6,
    RecId6,
    RecVersion6RecId6,
    RefCompanyId6,
    Address7,
    AddressComplement7,
    AddressNumber7,
    AddrRecId7,
    AddrTableId7,
    City7,
    CountryRegionId7,
    DeliveryCustVendCategory7,
    DistrictName7,
    ExciseType_IN7,
    Name7,
    RecId7,
    RecVersion7,
    ShipCarrierResidential7,
    State7,
    Street7,
    type7,
    ZipCode7,
    RecVersion6,
    ShipCarrierBlindShipment7,
    Dt_Envio_ATL,
    Phone,
    Dt_Atualiza_ATL,
    ContactPersonId,
    Email,
    AddressRecId5,
    PartyAddressRelationshipRecId5,
    RefCompanyId5,
    Address6,
    AddressComplement6,
    AddressNumber6,
    AddrRecId6,
    AddrTableId6,
    City6,
    CountryRegionId6,
    DeliveryCustVendCategory6,
    DistrictName6,
    ExciseType_IN6,
    type6,
    State6,
    Street6,
    TimeZone6,
    ZipCode6,
    ShipCarrierBlindShipment6,
    ShipCarrierResidential6,
    CellularPhone,
    PhoneLocal,
    DeliveryCustVendCNPJCPFNum3,
    DeliveryCustVendIENum3,
    CCMNum,
    SMS,
    TeleFax,
    Phone3,
    Dimensao8,
    NameKana,
    [URL],
    Memo,
    Pager,
    CreditMax,
    CustItemGroupId,
    TIN_IN,
    IdentificationNumber,
    TeleFax3,
    Email3,
    OrgId,
    VendAccount,
    County6,
    Name6,
    Phone6,
    PhoneLocal6,
    Telex6,
    IsPrimary7,
    PartyId7,
    Shared7,
    Status7,
    ValidFromDateTime7,
    ValidToDateTime7,
    AddressRecId8,
    PartyAddressRelationshipRecId8,
    RecId8,
    RecVersion8,
    RefCompanyId8,
    Address9,
    AddrRecId9,
    AddrTableId9,
    City9,
    CountryRegionId9,
    County9,
    DeliveryCustVendCategory9,
    ExciseType_IN9,
    Name9,
    RecId9,
    RecVersion9,
    ShipCarrierBlindShipment9,
    ShipCarrierResidential9,
    State9,
    Street9,
    type9,
    ZipCode9,
    InvoiceAccount,
    CommissionGroup,
    CreditRating,
    IsPrimary10,
    PartyId10,
    RecId10,
    RecVersion10,
    Shared10,
    Status10,
    ValidFromDateTime10,
    ValidToDateTime10,
    AddressRecId11,
    PartyAddressRelationshipRecId11,
    RecId11,
    RecVersion11,
    RefCompanyId11,
    Address12,
    AddrRecId12,
    AddrTableId12,
    CountryRegionId12,
    DeliveryCustVendCategory12,
    ExciseType_IN12,
    RecId12,
    RecVersion12,
    ShipCarrierBlindShipment12,
    ShipCarrierResidential12,
    type1,
    VATNum,
    SalesGroup,
    AddressComplement9,
    AddressNumber9,
    DistrictName9,
    type12,
    City12,
    State12,
    Street12,
    ZipCode12
                )
                VALUES
                (
                    @_DocumentHash,
    @AccountNum,
    @File,
    @Created_Date,
    @AccountStatement,
    @Address,
    @AddressComplement,
    @AddressNumber,
    @Blocked,
    @CitCustClientCode,
    @City,
    @CNPJCPFNum,
    @CompanyType_MX,
    @CountryRegionId,
    @CreatedDateTime,
    @Currency,
    @CustCategory,
    @CustFinalUser,
    @CustGroup,
    @DeliveryCustCategory,
    @DeliveryCustCNPJCPFNum,
    @DeliveryCustIENum,
    @Dimensao1,
    @Dimensao2,
    @Dimensao3,
    @Dimensao4,
    @Dimensao5,
    @Dimensao6,
    @Dimensao7,
    @DistrictName,
    @EstablishmentType,
    @ForeignCustomer_IN,
    @GiroType,
    @GiroTypeAccountStatement,
    @GiroTypeCollectionletter,
    @GiroTypeFreeTextInvoice,
    @GiroTypeInterestNote,
    @GiroTypeProjInvoice,
    @ICMSContributor,
    @IENum,
    @InclTax,
    @InterCompanyAllowIndirectCreation,
    @InterCompanyAutoCreateOrders,
    @InterCompanyDirectDelivery,
    @InvoiceAddress,
    @LanguageId,
    @MandatoryCreditLimit,
    @ModifiedDateTime,
    @Name,
    @NameAlias,
    @NatureOfAssessee_IN,
    @OneTimeCustomer,
    @OurAccountNum,
    @PANNumber_IN,
    @PANStatus_IN,
    @PartyCountry,
    @PartyId,
    @PartyState,
    @PartyType,
    @PaymMode,
    @PaymTermId,
    @PreferentialCustomer_IN,
    @RecId,
    @RecVersion,
    @RFIDCaseTagging,
    @RFIDItemTagging,
    @RFIDPalletTagging,
    @ServiceCodeOnDlvAddress,
    @ShipCarrierBlindShipment,
    @ShipCarrierFuelSurcharge,
    @State,
    @Street,
    @Suframa,
    @SuframaPISCOFINS,
    @TaxGroup,
    @TaxWithholdCalculate_IN,
    @TKR_Address,
    @TKR_ElecInvoice,
    @TKR_Name,
    @TKR_RetailAlcoholic,
    @TKR_VATBizType,
    @TKR_VATPrintType,
    @TKR_WholesaleAlcoholic,
    @ZipCode,
    @IsPrimary1,
    @PartyId1,
    @RecId1,
    @RecVersion1,
    @Shared1,
    @Status1,
    @ValidFromDateTime1,
    @ValidToDateTime1,
    @IsPrimary2,
    @PartyId2,
    @RecId2,
    @RecVersion2,
    @Shared2,
    @Status2,
    @ValidFromDateTime2,
    @ValidToDateTime2,
    @AddressRecId3,
    @PartyAddressRelationshipRecId3,
    @RecId3,
    @RecVersion3,
    @RefCompanyId3,
    @Address4,
    @AddressComplement4,
    @AddressNumber4,
    @AddrRecId4,
    @AddrTableId4,
    @City4,
    @CountryRegionId4,
    @DeliveryCustVendCategory4,
    @DistrictName4,
    @ExciseType_IN4,
    @Name4,
    @RecId4,
    @RecVersion4,
    @ShipCarrierBlindShipment4,
    @ShipCarrierResidential4,
    @State4,
    @Street4,
    @TimeZone4,
    @type4,
    @ZipCode4,
    @County,
    @County4,
    @BankAccount,
    @ZipCode3,
    @type3,
    @Street3,
    @State3,
    @ShipCarrierResidential3,
    @ShipCarrierBlindShipment3,
    @ExciseType_IN3,
    @DistrictName3,
    @DeliveryCustVendCategory3,
    @County3,
    @CountryRegionId3,
    @City3,
    @AddrTableId3,
    @AddressComplement3,
    @AddrRecId3,
    @AddressNumber3,
    @Address3,
    @RefCompanyId2,
    @PartyAddressRelationshipRecId2,
    @AddressRecId2,
    @TimeZone3,
    @Name3,
    @ZipCode5,
    @type5,
    @Street5,
    @State5,
    @ShipCarrierResidential5,
    @RecId5,
    @Name5,
    @ExciseType_IN5,
    @RecVersion5,
    @ShipCarrierBlindShipment5,
    @DistrictName5,
    @DeliveryCustVendCategory5,
    @CountryRegionId5,
    @City5,
    @AddrTableId5,
    @AddrRecId5,
    @AddressNumber5,
    @AddressComplement5,
    @Address5,
    @RefCompanyId4,
    @PartyAddressRelationshipRecId4,
    @AddressRecId4,
    @ValidToDateTime3,
    @ValidFromDateTime3,
    @Shared3,
    @IsPrimary3,
    @PartyId3,
    @Status3,
    @IsPrimary4,
    @PartyId4,
    @Shared4,
    @Status4,
    @ValidFromDateTime4,
    @ValidToDateTime4,
    @IsPrimary5,
    @PartyId5,
    @Shared5,
    @Status5,
    @ValidFromDateTime5,
    @ValidToDateTime5,
    @AddressRecId6,
    @PartyAddressRelationshipRecId6,
    @RecId6,
    @RecVersion6RecId6,
    @RefCompanyId6,
    @Address7,
    @AddressComplement7,
    @AddressNumber7,
    @AddrRecId7,
    @AddrTableId7,
    @City7,
    @CountryRegionId7,
    @DeliveryCustVendCategory7,
    @DistrictName7,
    @ExciseType_IN7,
    @Name7,
    @RecId7,
    @RecVersion7,
    @ShipCarrierResidential7,
    @State7,
    @Street7,
    @type7,
    @ZipCode7,
    @RecVersion6,
    @ShipCarrierBlindShipment7,
    @Dt_Envio_ATL,
    @Phone,
    @Dt_Atualiza_ATL,
    @ContactPersonId,
    @Email,
    @AddressRecId5,
    @PartyAddressRelationshipRecId5,
    @RefCompanyId5,
    @Address6,
    @AddressComplement6,
    @AddressNumber6,
    @AddrRecId6,
    @AddrTableId6,
    @City6,
    @CountryRegionId6,
    @DeliveryCustVendCategory6,
    @DistrictName6,
    @ExciseType_IN6,
    @type6,
    @State6,
    @Street6,
    @TimeZone6,
    @ZipCode6,
    @ShipCarrierBlindShipment6,
    @ShipCarrierResidential6,
    @CellularPhone,
    @PhoneLocal,
    @DeliveryCustVendCNPJCPFNum3,
    @DeliveryCustVendIENum3,
    @CCMNum,
    @SMS,
    @TeleFax,
    @Phone3,
    @Dimensao8,
    @NameKana,
    @URL,
    @Memo,
    @Pager,
    @CreditMax,
    @CustItemGroupId,
    @TIN_IN,
    @IdentificationNumber,
    @TeleFax3,
    @Email3,
    @OrgId,
    @VendAccount,
    @County6,
    @Name6,
    @Phone6,
    @PhoneLocal6,
    @Telex6,
    @IsPrimary7,
    @PartyId7,
    @Shared7,
    @Status7,
    @ValidFromDateTime7,
    @ValidToDateTime7,
    @AddressRecId8,
    @PartyAddressRelationshipRecId8,
    @RecId8,
    @RecVersion8,
    @RefCompanyId8,
    @Address9,
    @AddrRecId9,
    @AddrTableId9,
    @City9,
    @CountryRegionId9,
    @County9,
    @DeliveryCustVendCategory9,
    @ExciseType_IN9,
    @Name9,
    @RecId9,
    @RecVersion9,
    @ShipCarrierBlindShipment9,
    @ShipCarrierResidential9,
    @State9,
    @Street9,
    @type9,
    @ZipCode9,
    @InvoiceAccount,
    @CommissionGroup,
    @CreditRating,
    @IsPrimary10,
    @PartyId10,
    @RecId10,
    @RecVersion10,
    @Shared10,
    @Status10,
    @ValidFromDateTime10,
    @ValidToDateTime10,
    @AddressRecId11,
    @PartyAddressRelationshipRecId11,
    @RecId11,
    @RecVersion11,
    @RefCompanyId11,
    @Address12,
    @AddrRecId12,
    @AddrTableId12,
    @CountryRegionId12,
    @DeliveryCustVendCategory12,
    @ExciseType_IN12,
    @RecId12,
    @RecVersion12,
    @ShipCarrierBlindShipment12,
    @ShipCarrierResidential12,
    @type1,
    @VATNum,
    @SalesGroup,
    @AddressComplement9,
    @AddressNumber9,
    @DistrictName9,
    @type12,
    @City12,
    @State12,
    @Street12,
    @ZipCode12
                )
               
            END
            
            SELECT @AccountNum AS ReturnValue;
        
        COMMIT TRAN
    END TRY
    BEGIN CATCH
        ROLLBACK TRAN
        SELECT ERROR_MESSAGE() AS ReturnValue;
    END CATCH
END
GO
