SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[spATL_INT_AIFMESSAGELOG_InsUpd]
(
	@ID							BigInt,
	@SOURCEENDPOINTID			nvarchar(60),
	@DESTINATIONENDPOINTID		nvarchar(60),
	@ACTIONID					nvarchar(510),
	@EXTERNALACTION				nvarchar(510),
	@DIRECTION					int,
	@TRANSPORTNAME				nvarchar(120),
	@ADDRESS					nvarchar(520),
	@SOURCEENDPOINTUSERID		nvarchar(242),
	@SUBMITTINGUSERID			nvarchar(242),
	@CHANNELID					nvarchar(60),
	@PIPELINEID					nvarchar(60),
	@MESSAGEID					uniqueidentifier,
	@REQUESTMESSAGEID			uniqueidentifier,
	@STATUS						int,
	@CREATEDDATETIME			datetime,
	@DEL_CREATEDTIME			int,
	@DATAAREAID					nvarchar(8),
	@RECVERSION					int,
	@RECID						bigint,
	@COMPANY					nvarchar(8)
)

AS
BEGIN
--Exceção(try/CATCH)
--Transação
--sp_help AIFMESSAGELOG
	BEGIN TRY	
		Declare @ID_New as bigint;

		SET @ID_New	=(SELECT ID FROM ATL_INT.dbo.AIFMESSAGELOG where MESSAGEID = @MESSAGEID)
			
		IF @ID_New IS NOT NULL
			Begin
				Update
					ATL_INT.dbo.AIFMESSAGELOG
				Set
					SOURCEENDPOINTID=@SOURCEENDPOINTID,
					DESTINATIONENDPOINTID=@DESTINATIONENDPOINTID,
					ACTIONID=@ACTIONID,
					EXTERNALACTION=@EXTERNALACTION,
					DIRECTION=@DIRECTION,
					TRANSPORTNAME=@TRANSPORTNAME,
					ADDRESS=@ADDRESS,
					SOURCEENDPOINTUSERID=@SOURCEENDPOINTUSERID,
					SUBMITTINGUSERID=@SUBMITTINGUSERID,
					CHANNELID=@CHANNELID,
					PIPELINEID=@PIPELINEID,
					MESSAGEID=@MESSAGEID,
					REQUESTMESSAGEID=@REQUESTMESSAGEID,
					STATUS=@STATUS,
					CREATEDDATETIME=@CREATEDDATETIME,
					DEL_CREATEDTIME=@DEL_CREATEDTIME,
					DATAAREAID=@DATAAREAID,
					RECVERSION=@RECVERSION,
					RECID=@RECID,
					COMPANY=@COMPANY					
				Where
					ID = @ID_New			
			End
		Else
			BEGIN
				Insert ATL_INT.dbo.AIFMESSAGELOG
				(
					SOURCEENDPOINTID,DESTINATIONENDPOINTID,ACTIONID,EXTERNALACTION,DIRECTION,TRANSPORTNAME,ADDRESS,
					SOURCEENDPOINTUSERID,SUBMITTINGUSERID,CHANNELID,PIPELINEID,MESSAGEID,REQUESTMESSAGEID,STATUS,
					CREATEDDATETIME,DEL_CREATEDTIME,DATAAREAID,RECVERSION,RECID,COMPANY
				)
				Values
				(
					@SOURCEENDPOINTID,@DESTINATIONENDPOINTID,@ACTIONID,@EXTERNALACTION,@DIRECTION,@TRANSPORTNAME,@ADDRESS,
					@SOURCEENDPOINTUSERID,@SUBMITTINGUSERID,@CHANNELID,@PIPELINEID,@MESSAGEID,@REQUESTMESSAGEID,@STATUS,
					@CREATEDDATETIME,@DEL_CREATEDTIME,@DATAAREAID,@RECVERSION,@RECID,@COMPANY
				)

				set @ID_New = @@IDENTITY;
			END	

		
		Select @ID_New as Retorno;
		
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() as Retorno;

	END CATCH	

END

GO
