SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[spBDPINT_Localidade_InsUpd]
(
	@UN_LOCTN_CHNG_CD			[varchar](1),
	@ISO_2_LTR_CNTRY_CD			[varchar](2),
	@UN_LOCTN_CD				[varchar](6),
	@UN_LOCTN_NM				[varchar](100),
	@UN_LOCTN_WO_DIACRITICS_NM	[varchar](100),
	@UN_LOCTN_SUBDIV_CD			[varchar](10),
	@UN_LOCTN_STATUS_CD			[varchar](3),
	@UN_LOCTN_FNCTN_POS_1_CD	[varchar](1),
	@UN_LOCTN_FNCTN_POS_2_CD	[varchar](1),
	@UN_LOCTN_FNCTN_POS_3_CD	[varchar](1),
	@UN_LOCTN_FNCTN_POS_4_CD	[varchar](1),
	@UN_LOCTN_FNCTN_POS_5_CD	[varchar](1),
	@UN_LOCTN_FNCTN_POS_6_CD	[varchar](1),
	@UN_LOCTN_FNCTN_POS_7_CD	[varchar](1),
	@UN_LOCTN_FNCTN_POS_8_CD	[varchar](1),
	@UN_LOCTN_LAST_MODFD_DT		[varchar](4),
	@UN_LOCTN_IATA_CD			[varchar](3),
	@UN_LOCTN_LATITUDE_CD		[varchar](10),
	@UN_LOCTN_LONGITUDE_CD		[varchar](10),
	@IATA_3_LTR_CITY_CD			[varchar](3),
	@IATA_3_LTR_AIRPORT_CD		[varchar](3),
	@SCHED_D_K_CD				[varchar](5),
	@CREATED_BY					[varchar](50),
	@CREATED_ON					datetime,
	@LAST_MODFD_BY				[varchar](50),
	@LAST_MODFD_DT				datetime,
	@TEMP_CD_IND				[varchar](1),
	@LGCLLY_DELTD_IND			[varchar](1),
	@BDP_SMART_AIRPORT_NM		[varchar](100),
	@BDP_SMART_CITY_NM			[varchar](250),
	@CMNT_TXT					[varchar](1000),
	@GIF_CNTRY_UNLOC_CD			[varchar](4),
	@CNTRY_NM					[varchar](50),
	@RGN_CD						[varchar](6),
	@RGN_NM						[varchar](150),
	@UN_LOCTN_LATITUDE_DEC_CD	float,
	@UN_LOCTN_LONGITUDE_DEC_CD	float
)

AS

	
BEGIN
--Exceção(try/CATCH)
--Transação
--sp_help BDPINT_Localidade
	BEGIN TRY
	
	Declare @ID_New as bigint;
	
	if not exists(select UN_LOCTN_SUBDIV_CD from BDPINT_Localidade where ISO_2_LTR_CNTRY_CD = @ISO_2_LTR_CNTRY_CD AND UN_LOCTN_CD = @UN_LOCTN_CD)
		BEGIN
			Insert into BDPINT_Localidade 
			(
				UN_LOCTN_CHNG_CD,ISO_2_LTR_CNTRY_CD,UN_LOCTN_CD,UN_LOCTN_NM,UN_LOCTN_WO_DIACRITICS_NM,UN_LOCTN_SUBDIV_CD,UN_LOCTN_STATUS_CD,
				UN_LOCTN_FNCTN_POS_1_CD,UN_LOCTN_FNCTN_POS_2_CD,UN_LOCTN_FNCTN_POS_3_CD,UN_LOCTN_FNCTN_POS_4_CD,UN_LOCTN_FNCTN_POS_5_CD,
				UN_LOCTN_FNCTN_POS_6_CD,UN_LOCTN_FNCTN_POS_7_CD,UN_LOCTN_FNCTN_POS_8_CD,UN_LOCTN_LAST_MODFD_DT,UN_LOCTN_IATA_CD,UN_LOCTN_LATITUDE_CD,
				UN_LOCTN_LONGITUDE_CD,IATA_3_LTR_CITY_CD,IATA_3_LTR_AIRPORT_CD,SCHED_D_K_CD,CREATED_BY,CREATED_ON,LAST_MODFD_BY,LAST_MODFD_DT,
				TEMP_CD_IND,LGCLLY_DELTD_IND,BDP_SMART_AIRPORT_NM,BDP_SMART_CITY_NM,CMNT_TXT
				,GIF_CNTRY_UNLOC_CD,CNTRY_NM,RGN_CD,RGN_NM,UN_LOCTN_LATITUDE_DEC_CD,UN_LOCTN_LONGITUDE_DEC_CD
			)
			Values
			(
				@UN_LOCTN_CHNG_CD,@ISO_2_LTR_CNTRY_CD,@UN_LOCTN_CD,@UN_LOCTN_NM,@UN_LOCTN_WO_DIACRITICS_NM,@UN_LOCTN_SUBDIV_CD,@UN_LOCTN_STATUS_CD,
				@UN_LOCTN_FNCTN_POS_1_CD,@UN_LOCTN_FNCTN_POS_2_CD,@UN_LOCTN_FNCTN_POS_3_CD,@UN_LOCTN_FNCTN_POS_4_CD,@UN_LOCTN_FNCTN_POS_5_CD,
				@UN_LOCTN_FNCTN_POS_6_CD,@UN_LOCTN_FNCTN_POS_7_CD,@UN_LOCTN_FNCTN_POS_8_CD,@UN_LOCTN_LAST_MODFD_DT,@UN_LOCTN_IATA_CD,@UN_LOCTN_LATITUDE_CD,
				@UN_LOCTN_LONGITUDE_CD,@IATA_3_LTR_CITY_CD,@IATA_3_LTR_AIRPORT_CD,@SCHED_D_K_CD,@CREATED_BY,@CREATED_ON,@LAST_MODFD_BY,@LAST_MODFD_DT,
				@TEMP_CD_IND,@LGCLLY_DELTD_IND,@BDP_SMART_AIRPORT_NM,@BDP_SMART_CITY_NM,@CMNT_TXT
				,@GIF_CNTRY_UNLOC_CD,@CNTRY_NM,@RGN_CD,@RGN_NM,@UN_LOCTN_LATITUDE_DEC_CD,@UN_LOCTN_LONGITUDE_DEC_CD
			)			
			
		END
	else
		BEGIN
			update
				BDPINT_Localidade
			set
				UN_LOCTN_CHNG_CD=@UN_LOCTN_CHNG_CD,
				ISO_2_LTR_CNTRY_CD=@ISO_2_LTR_CNTRY_CD,
				UN_LOCTN_CD=@UN_LOCTN_CD,
				UN_LOCTN_NM=@UN_LOCTN_NM,
				UN_LOCTN_WO_DIACRITICS_NM=@UN_LOCTN_WO_DIACRITICS_NM,
				UN_LOCTN_SUBDIV_CD=@UN_LOCTN_SUBDIV_CD,
				UN_LOCTN_STATUS_CD=@UN_LOCTN_STATUS_CD,
				UN_LOCTN_FNCTN_POS_1_CD=@UN_LOCTN_FNCTN_POS_1_CD,
				UN_LOCTN_FNCTN_POS_2_CD=@UN_LOCTN_FNCTN_POS_2_CD,
				UN_LOCTN_FNCTN_POS_3_CD=@UN_LOCTN_FNCTN_POS_3_CD,
				UN_LOCTN_FNCTN_POS_4_CD=@UN_LOCTN_FNCTN_POS_4_CD,
				UN_LOCTN_FNCTN_POS_5_CD=@UN_LOCTN_FNCTN_POS_5_CD,
				UN_LOCTN_FNCTN_POS_6_CD=@UN_LOCTN_FNCTN_POS_6_CD,
				UN_LOCTN_FNCTN_POS_7_CD=@UN_LOCTN_FNCTN_POS_7_CD,
				UN_LOCTN_FNCTN_POS_8_CD=@UN_LOCTN_FNCTN_POS_8_CD,
				UN_LOCTN_LAST_MODFD_DT=@UN_LOCTN_LAST_MODFD_DT,
				UN_LOCTN_IATA_CD=@UN_LOCTN_IATA_CD,
				UN_LOCTN_LATITUDE_CD=@UN_LOCTN_LATITUDE_CD,
				UN_LOCTN_LONGITUDE_CD=@UN_LOCTN_LONGITUDE_CD,
				IATA_3_LTR_CITY_CD=@IATA_3_LTR_CITY_CD,
				IATA_3_LTR_AIRPORT_CD=@IATA_3_LTR_AIRPORT_CD,
				SCHED_D_K_CD=@SCHED_D_K_CD,
				CREATED_BY=@CREATED_BY,
				CREATED_ON=@CREATED_ON,
				LAST_MODFD_BY=@LAST_MODFD_BY,
				LAST_MODFD_DT=@LAST_MODFD_DT,
				TEMP_CD_IND=@TEMP_CD_IND,
				LGCLLY_DELTD_IND=@LGCLLY_DELTD_IND,
				BDP_SMART_AIRPORT_NM=@BDP_SMART_AIRPORT_NM,
				BDP_SMART_CITY_NM=@BDP_SMART_CITY_NM,
				CMNT_TXT=@CMNT_TXT,

				GIF_CNTRY_UNLOC_CD=@GIF_CNTRY_UNLOC_CD,
				CNTRY_NM=@CNTRY_NM,
				RGN_CD=@RGN_CD,
				RGN_NM=@RGN_NM,
				UN_LOCTN_LATITUDE_DEC_CD=@UN_LOCTN_LATITUDE_DEC_CD,
				UN_LOCTN_LONGITUDE_DEC_CD=@UN_LOCTN_LONGITUDE_DEC_CD
			where
				ISO_2_LTR_CNTRY_CD = @ISO_2_LTR_CNTRY_CD AND UN_LOCTN_CD = @UN_LOCTN_CD
		
		END

	SET @ID_New = 1						
	Select @ID_New as Retorno;

		
		COMMIT TRAN
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN
		SELECT ERROR_MESSAGE() as Retorno;

	END CATCH	

END



GO
