SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Create  PROCEDURE [dbo].[spATL_Altera_BL_InsUpd]
	@num_proc	varchar(16),
	@cmbShipper	varchar(20),
	@txtShipper	varchar(200),
	@cmbConsignee	varchar(20),
	@txtConsignee	varchar(200),
	@cmbNotify	varchar(20),
	@txtNotify	varchar(200),
	@cmbOrigin	varchar(100),
	@cmbLoading	varchar(100),
	@cmbDelivery	varchar(100),
	@cmbFinalDestination	varchar(100),
	@cmbCarrier	varchar(50),
	@cmbVoyage	varchar(50),
	@txtVessel	varchar(100),
	@cd_usuario	varchar(6),
	@status	numeric(1),
--	@dt_ins	datetime(8),
	@cmbCiaAerea	varchar(30),
	@txtVoo	varchar(13),
	@txtVoyage	varchar(25),
	@cmbVessel	varchar(50),
	@cmbIssuing	varchar(20),
	@txtIssuing	varchar(200),
	@txtCarriage	varchar(50),
	@txtCustoms	varchar(50),
	@txtAmount	varchar(50),
	@txtSignatureShipper	varchar(50),
	@txtSignatureCarrier	varchar(50),
	@txtShipperPostcodeCode	varchar(200),
	@txtShipperStreetName	varchar(200),
	@txtShipperCityName	varchar(200),
	@txtShipperCountryID	varchar(200),
	@txtShipperCountryName	varchar(200),
	@txtShipperPersonName	varchar(200),
	@txtShipperDepartmentName	varchar(200),
	@txtShipperDirectTelephoneCommunication	varchar(200),
	@txtShipperFaxCommunication	varchar(200),
	@txtShipperURIEmailCommunication	varchar(200),
	@txtConsigneePostcodeCode	varchar(200),
	@txtConsigneeStreetName	varchar(200),
	@txtConsigneeCityName	varchar(200),
	@txtConsigneeCountryID	varchar(200),
	@txtConsigneeCountryName	varchar(200),
	@txtConsigneePersonName	varchar(200),
	@txtConsigneeDepartmentName	varchar(200),
	@txtConsigneeDirectTelephoneCommunication	varchar(200),
	@txtConsigneeFaxCommunication	varchar(200),
	@txtConsigneeURIEmailCommunication	varchar(200),
	@txtNotifyPostcodeCode	varchar(200),
	@txtNotifyStreetName	varchar(200),
	@txtNotifyCityName	varchar(200),
	@txtNotifyCountryID	varchar(200),
	@txtNotifyCountryName	varchar(200),
	@txtNotifyPersonName	varchar(200),
	@txtNotifyDepartmentName	varchar(200),
	@txtNotifyDirectTelephoneCommunication	varchar(200),
	@txtNotifyFaxCommunication	varchar(200),
	@txtNotifyURIEmailCommunication	varchar(200),
	@txtIssuingPostcodeCode	varchar(200),
	@txtIssuingStreetName	varchar(200),
	@txtIssuingCityName	varchar(200),
	@txtIssuingCountryID	varchar(200),
	@txtIssuingCountryName	varchar(200),
	@txtIssuingPersonName	varchar(200),
	@txtIssuingDepartmentName	varchar(200),
	@txtIssuingDirectTelephoneCommunication	varchar(200),
	@txtIssuingFaxCommunication	varchar(200),
	@txtIssuingURIEmailCommunication	varchar(200)
AS

Begin Transaction

	if not exists( select * from altera_bl where num_proc = @num_proc)
		Begin
			Insert Into 
				Altera_Bl
					(
						num_proc,
						cmbShipper,
						txtShipper,
						cmbConsignee,
						txtConsignee,
						cmbNotify,
						txtNotify,
						cmbOrigin,
						cmbLoading,
						cmbDelivery,
						cmbFinalDestination,
						cmbCarrier,
						cmbVoyage,
						txtVessel,
						cd_usuario,
						status,
						dt_ins,
						cmbCiaAerea,
						txtVoo,
						txtVoyage,
						cmbVessel,
						cmbIssuing,
						txtIssuing,
						txtCarriage,
						txtCustoms,
						txtAmount,
						txtSignatureShipper,
						txtSignatureCarrier,
						txtShipperPostcodeCode,
						txtShipperStreetName,
						txtShipperCityName,
						txtShipperCountryID,
						txtShipperCountryName,
						txtShipperPersonName,
						txtShipperDepartmentName,
						txtShipperDirectTelephoneCommunication,
						txtShipperFaxCommunication,
						txtShipperURIEmailCommunication,
						txtConsigneePostcodeCode,
						txtConsigneeStreetName,
						txtConsigneeCityName,
						txtConsigneeCountryID,
						txtConsigneeCountryName,
						txtConsigneePersonName,
						txtConsigneeDepartmentName,
						txtConsigneeDirectTelephoneCommunication,
						txtConsigneeFaxCommunication,
						txtConsigneeURIEmailCommunication,
						txtNotifyPostcodeCode,
						txtNotifyStreetName,
						txtNotifyCityName,
						txtNotifyCountryID,
						txtNotifyCountryName,
						txtNotifyPersonName,
						txtNotifyDepartmentName,
						txtNotifyDirectTelephoneCommunication,
						txtNotifyFaxCommunication,
						txtNotifyURIEmailCommunication,
						txtIssuingPostcodeCode,
						txtIssuingStreetName,
						txtIssuingCityName,
						txtIssuingCountryID,
						txtIssuingCountryName,
						txtIssuingPersonName,
						txtIssuingDepartmentName,
						txtIssuingDirectTelephoneCommunication,
						txtIssuingFaxCommunication,
						txtIssuingURIEmailCommunication					
				)
			Values
				(
					@num_proc,
					@cmbShipper,
					@txtShipper,
					@cmbConsignee,
					@txtConsignee,
					@cmbNotify,
					@txtNotify,
					@cmbOrigin,
					@cmbLoading,
					@cmbDelivery,
					@cmbFinalDestination,
					@cmbCarrier,
					@cmbVoyage,
					@txtVessel,
					@cd_usuario,
					@status,
					getdate(),
					@cmbCiaAerea,
					@txtVoo,
					@txtVoyage,
					@cmbVessel,
					@cmbIssuing,
					@txtIssuing,
					@txtCarriage,
					@txtCustoms,
					@txtAmount,
					@txtSignatureShipper,
					@txtSignatureCarrier,
					@txtShipperPostcodeCode,
					@txtShipperStreetName,
					@txtShipperCityName,
					@txtShipperCountryID,
					@txtShipperCountryName,
					@txtShipperPersonName,
					@txtShipperDepartmentName,
					@txtShipperDirectTelephoneCommunication,
					@txtShipperFaxCommunication,
					@txtShipperURIEmailCommunication,
					@txtConsigneePostcodeCode,
					@txtConsigneeStreetName,
					@txtConsigneeCityName,
					@txtConsigneeCountryID,
					@txtConsigneeCountryName,
					@txtConsigneePersonName,
					@txtConsigneeDepartmentName,
					@txtConsigneeDirectTelephoneCommunication,
					@txtConsigneeFaxCommunication,
					@txtConsigneeURIEmailCommunication,
					@txtNotifyPostcodeCode,
					@txtNotifyStreetName,
					@txtNotifyCityName,
					@txtNotifyCountryID,
					@txtNotifyCountryName,
					@txtNotifyPersonName,
					@txtNotifyDepartmentName,
					@txtNotifyDirectTelephoneCommunication,
					@txtNotifyFaxCommunication,
					@txtNotifyURIEmailCommunication,
					@txtIssuingPostcodeCode,
					@txtIssuingStreetName,
					@txtIssuingCityName,
					@txtIssuingCountryID,
					@txtIssuingCountryName,
					@txtIssuingPersonName,
					@txtIssuingDepartmentName,
					@txtIssuingDirectTelephoneCommunication,
					@txtIssuingFaxCommunication,
					@txtIssuingURIEmailCommunication				
				)		
		End
	Else
		Begin
			Update
				Altera_Bl
				SET
						num_proc = @num_proc,
						cmbShipper = @cmbShipper,
						txtShipper = @txtShipper,
						cmbConsignee = @cmbConsignee,
						txtConsignee = @txtConsignee,
						cmbNotify =	@cmbNotify,
						txtNotify =	@txtNotify,
						cmbOrigin =	@cmbOrigin,
						cmbLoading = @cmbLoading,
						cmbDelivery = @cmbDelivery,
						cmbFinalDestination = @cmbFinalDestination,
						cmbCarrier = @cmbCarrier,
						cmbVoyage =	@cmbVoyage,
						txtVessel =	@txtVessel,
						cd_usuario = @cd_usuario,
						status = @status,
						dt_ins = getdate(),
						cmbCiaAerea = @cmbCiaAerea,
						txtVoo = @txtVoo,
						txtVoyage = @txtVoyage,
						cmbVessel =	@cmbVessel,
						cmbIssuing = @cmbIssuing,
						txtIssuing = @txtIssuing,
						txtCarriage = @txtCarriage,
						txtCustoms = @txtCustoms,
						txtAmount =	@txtAmount,
						txtSignatureShipper = @txtSignatureShipper,
						txtSignatureCarrier = @txtSignatureCarrier,
						txtShipperPostcodeCode = @txtShipperPostcodeCode,
						txtShipperStreetName =	@txtShipperStreetName,
						txtShipperCityName = @txtShipperCityName,
						txtShipperCountryID = @txtShipperCountryID,
						txtShipperCountryName = @txtShipperCountryName,
						txtShipperPersonName = @txtShipperPersonName,
						txtShipperDepartmentName = @txtShipperDepartmentName,
						txtShipperDirectTelephoneCommunication = @txtShipperDirectTelephoneCommunication,
						txtShipperFaxCommunication = @txtShipperFaxCommunication,
						txtShipperURIEmailCommunication = @txtShipperURIEmailCommunication,
						txtConsigneePostcodeCode = @txtConsigneePostcodeCode,
						txtConsigneeStreetName = @txtConsigneeStreetName,
						txtConsigneeCityName = @txtConsigneeCityName,
						txtConsigneeCountryID = @txtConsigneeCountryID,
						txtConsigneeCountryName = @txtConsigneeCountryName,
						txtConsigneePersonName = @txtConsigneePersonName,
						txtConsigneeDepartmentName = @txtConsigneeDepartmentName,
						txtConsigneeDirectTelephoneCommunication = @txtConsigneeDirectTelephoneCommunication,
						txtConsigneeFaxCommunication = @txtConsigneeFaxCommunication,
						txtConsigneeURIEmailCommunication = @txtConsigneeURIEmailCommunication,
						txtNotifyPostcodeCode = @txtNotifyPostcodeCode,
						txtNotifyStreetName = @txtNotifyStreetName,
						txtNotifyCityName =	@txtNotifyCityName,
						txtNotifyCountryID = @txtNotifyCountryID,
						txtNotifyCountryName = @txtNotifyCountryName,
						txtNotifyPersonName = @txtNotifyPersonName,
						txtNotifyDepartmentName = @txtNotifyDepartmentName,
						txtNotifyDirectTelephoneCommunication = @txtNotifyDirectTelephoneCommunication,
						txtNotifyFaxCommunication = @txtNotifyFaxCommunication,
						txtNotifyURIEmailCommunication = @txtNotifyURIEmailCommunication,
						txtIssuingPostcodeCode = @txtIssuingPostcodeCode,
						txtIssuingStreetName = @txtIssuingStreetName,
						txtIssuingCityName = @txtIssuingCityName,
						txtIssuingCountryID = @txtIssuingCountryID,
						txtIssuingCountryName =	@txtIssuingCountryName,
						txtIssuingPersonName = @txtIssuingPersonName,
						txtIssuingDepartmentName = @txtIssuingDepartmentName,
						txtIssuingDirectTelephoneCommunication = @txtIssuingDirectTelephoneCommunication,
						txtIssuingFaxCommunication = @txtIssuingFaxCommunication,
						txtIssuingURIEmailCommunication = @txtIssuingURIEmailCommunication
			Where
				Num_Proc = @num_proc
		End

		IF @@Error <> 0
			BEGIN
				ROLLBACK TRANSACTION
				RETURN -1
			END

Commit Transaction 

GO
