SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE spSchneiderCASS_Rel
(
 @FatCod varchar(20),  
 @DtInicial datetime,  
 @DtFinal datetime
)
AS

SET NOCOUNT ON


/* -------------------------------------------------------------------------------------------------------------------------
HISTORY CHANGE
. Date:
. Applicant: 
. Developer: Alessandra Suzuki Mariano
. Request:	
-------------------------------------------------------------------------------------------------------------------------
EXECUTION
exec  spSchneiderCASS_Rel 'IMSCH202010037BRA',null,null
exec  spSchneiderCASS_Rel null,'2021-01-19','2021-01-19'

exec  spSchneiderCASS_Rel 'IMSCH202010037BRA','',''
exec  spSchneiderCASS_Rel '','2021-01-19','2021-01-19'

exec  spSchneiderCASS_Rel 'IMSCH202010037BRA','2021-01-19','2021-01-19'


exec  spSchneiderCASS_Rel 'EMSCH202007013BRA',null,null
exec  spSchneiderCASS_Rel null,'2021-01-19','2021-01-19'

exec  spSchneiderCASS_Rel 'EMSCH202007013BRA','',''
exec  spSchneiderCASS_Rel '','2021-01-19','2021-01-19'

exec  spSchneiderCASS_Rel 'EMSCH202007013BRA','2021-01-19','2021-01-19'
-------------------------------------------------------------------------------------------------------------------------

*/


IF OBJECT_ID('dbo.tmp_Schneider_CASS', 'u') IS NOT NULL 
	DROP TABLE tmp_Schneider_CASS

IF OBJECT_ID('dbo.tmp_Rel_SCHCASS_INVOICE', 'u') IS NOT NULL 
	DROP TABLE tmp_Rel_SCHCASS_INVOICE

IF OBJECT_ID('dbo.tmp_Rel_SCHCASS_INVOICE_TRATADO', 'u') IS NOT NULL 
	DROP TABLE tmp_Rel_SCHCASS_INVOICE_TRATADO

IF OBJECT_ID('dbo.tmp_Rel_SCHCASS_INVOICE_PARIDADES', 'u') IS NOT NULL 
	DROP TABLE tmp_Rel_SCHCASS_INVOICE_PARIDADES

IF OBJECT_ID('dbo.tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS', 'u') IS NOT NULL 
	DROP TABLE tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS

IF OBJECT_ID('dbo.tmp_Rel_SCHCASS_JOB_AUX', 'u') IS NOT NULL 
	DROP TABLE tmp_Rel_SCHCASS_JOB_AUX

IF OBJECT_ID('dbo.tmp_Rel_SCHCASS_JOB_ITINERARY_ID', 'u') IS NOT NULL 
	DROP TABLE tmp_Rel_SCHCASS_JOB_ITINERARY_ID
-------------------------------------------------------------------------------------------------------------------------
-- TRATAMENTOS CAMPOS DE FILTRO
-------------------------------------------------------------------------------------------------------------------------
if isnull(@FatCod,'') = ''
begin
	set @FatCod = '%'
end
ELSE 
BEGIN
	set @FatCod = '%' + @FatCod + '%'
END

if (@DtInicial is null) or (@DtInicial = '1900-01-01 00:00:00.000')
begin
	set @DtInicial = '1900-01-01'
end

if (@DtFinal is null) or (@DtFinal = '1900-01-01 00:00:00.000')
begin
	set @DtFinal = '9999-12-31'
end

-------------------------------------------------------------------------------------------------------------------------
-- TABELAS TEMPORÁRIAS UTILIZADAS NO RELATORIO
-------------------------------------------------------------------------------------------------------------------------
		
	CREATE TABLE [dbo].[tmp_Schneider_CASS](
	[CARRIER_ID]			VARCHAR(12)
	,[SHIPPER_ID]			VARCHAR(6)

	,[SHIPPER_ACCOUNT]		VARCHAR(30)

	,[MODE]					CHAR(1)
	,[MOVEMENT]				CHAR(1)

	,[BILLING_NUMBER]		VARCHAR(22)
	,[BILLING_DATE]			VARCHAR(10)

	,[SHIPPER_SID_1]		VARCHAR(22)
	,[SHIPPER_SID_2]		VARCHAR(22)
	,[SHIPPER_SID_3]		VARCHAR(22)

	,[CARRIER_PRO_1]		VARCHAR(22)
	,[CARRIER_PRO_2]		VARCHAR(22)
	,[CARRIER_PRO_3]		CHAR(1)			--VARCHAR(22)

	,[SHIPPER_NAME]			VARCHAR(60)
	,[SHIPPER_ZIP]			VARCHAR(15)
	,[SHIPPER_CITY]			VARCHAR(30)
	,[SHIPPER_STATE]		VARCHAR(15)
	,[SHIPPER_STREET]		VARCHAR(60)
	,[SHIPPER_CTRY]			VARCHAR(2)

	,[CONSIGNEE_NAME]		VARCHAR(60)
	,[CONSIGNEE_ZIP]		VARCHAR(15)
	,[CONSIGNEE_CITY]		VARCHAR(30)
	,[CONSIGNEE_STATE]		VARCHAR(15)
	,[CONSIGNEE_STREET]		VARCHAR(60)
	,[CONSIGNEE_CTRY]		VARCHAR(2)

	,[STOPOFF_1_NAME]		CHAR(1)
	,[STOPOFF_1_ZIP]		CHAR(1)
	,[STOPOFF_1_CITY]		CHAR(1)
	,[STOPOFF_1_STATE]		CHAR(1)
	,[STOPOFF_1_STREET]		CHAR(1)
	,[STOPOFF_1_CTRY]		CHAR(1)
	,[STOPOFF_1_LOC]		CHAR(1)
	,[STOPOFF_2_NAME]		CHAR(1)
	,[STOPOFF_2_ZIP]		CHAR(1)
	,[STOPOFF_2_CITY]		CHAR(1)
	,[STOPOFF_2_STATE]		CHAR(1)
	,[STOPOFF_2_STREET]		CHAR(1)
	,[STOPOFF_2_CTRY]		CHAR(1)
	,[STOPOFF_2_LOC]		CHAR(1)
	,[STOPOFF_3_NAME]		CHAR(1)
	,[STOPOFF_3_ZIP]		CHAR(1)
	,[STOPOFF_3_CITY]		CHAR(1)
	,[STOPOFF_3_STATE]		CHAR(1)
	,[STOPOFF_3_STREET]		CHAR(1)
	,[STOPOFF_3_CTRY]		CHAR(1)
	,[STOPOFF_3_LOC]		CHAR(1)
	,[STOPOFF_4_NAME]		CHAR(1)
	,[STOPOFF_4_ZIP]		CHAR(1)
	,[STOPOFF_4_CITY]		CHAR(1)
	,[STOPOFF_4_STATE]		CHAR(1)
	,[STOPOFF_4_STREET]		CHAR(1)
	,[STOPOFF_4_CTRY]		CHAR(1)
	,[STOPOFF_4_LOC]		CHAR(1)
	,[STOPOFF_5_NAME]		CHAR(1)
	,[STOPOFF_5_ZIP]		CHAR(1)
	,[STOPOFF_5_CITY]		CHAR(1)
	,[STOPOFF_5_STATE]		CHAR(1)
	,[STOPOFF_5_STREET]		CHAR(1)
	,[STOPOFF_5_CTRY]		CHAR(1)
	,[STOPOFF_5_LOC]		CHAR(1)

	,[DISTANCE_KM]			CHAR(1)			--VARCHAR(15)
	,[INCO_TERMS]			VARCHAR(3)
	,[SHIP_DATE]			VARCHAR(10)
	,[DEPART_DATE]			VARCHAR(10)
	,[ARRIVAL_DATE]			VARCHAR(10)
	,[DELIVERY_DATE]		VARCHAR(10)

	,[SERVICE]				VARCHAR(2)
	,[SERVICE_DESC]			VARCHAR(80)

	,[EQUIPMENT]			VARCHAR(2)
	,[EQUIPMENT_REF]		VARCHAR(30)
	,[SHIPPING_LINE]		VARCHAR(30)

	,[GROSS_WEIGHT]			VARCHAR(15)
	,[VOLUME]				VARCHAR(15)
	,[DIM_WEIGHT]			CHAR(1)			--VARCHAR(15)
	,[CHARGE_WEIGHT]		VARCHAR(15)

	,[LOADING_METERS]		VARCHAR(15)

	,[UOM_CODE_1]			VARCHAR(3)
	,[UOM_QTY_1]			VARCHAR(15)

	,[UOM_CODE_2]			CHAR(1)			--VARCHAR(3)
	,[UOM_QTY_2]			CHAR(1)			--VARCHAR(15)
	,[UOM_CODE_3]			CHAR(1)			--VARCHAR(3)
	,[UOM_QTY_3]			CHAR(1)			--VARCHAR(15)

	,[CHRG_CODE_1]			VARCHAR(30)
	,[CHRG_DESC_1]			VARCHAR(20)
	,[CHRG_CURR_1]			VARCHAR(3)
	,[CHRG_AMNT_1]			VARCHAR(15)

	,[CHRG_CODE_2]			VARCHAR(30)
	,[CHRG_DESC_2]			VARCHAR(20)
	,[CHRG_CURR_2]			VARCHAR(3)
	,[CHRG_AMNT_2]			VARCHAR(15)

	,[CHRG_CODE_3]			VARCHAR(30)
	,[CHRG_DESC_3]			VARCHAR(20)
	,[CHRG_CURR_3]			VARCHAR(3)
	,[CHRG_AMNT_3]			VARCHAR(15)

	,[CHRG_CODE_4]			VARCHAR(30)
	,[CHRG_DESC_4]			VARCHAR(20)
	,[CHRG_CURR_4]			VARCHAR(3)
	,[CHRG_AMNT_4]			VARCHAR(15)

	,[CHRG_CODE_5]			VARCHAR(30)
	,[CHRG_DESC_5]			VARCHAR(20)
	,[CHRG_CURR_5]			VARCHAR(3)
	,[CHRG_AMNT_5]			VARCHAR(15)

	,[CHRG_CODE_6]			VARCHAR(30)
	,[CHRG_DESC_6]			VARCHAR(20)
	,[CHRG_CURR_6]			VARCHAR(3)
	,[CHRG_AMNT_6]			VARCHAR(15)

	,[CHRG_CODE_7]			VARCHAR(30)
	,[CHRG_DESC_7]			VARCHAR(20)
	,[CHRG_CURR_7]			VARCHAR(3)
	,[CHRG_AMNT_7]			VARCHAR(15)

	,[CHRG_CODE_8]			VARCHAR(30)
	,[CHRG_DESC_8]			VARCHAR(02)
	,[CHRG_CURR_8]			VARCHAR(3)
	,[CHRG_AMNT_8]			VARCHAR(15)

	,[CHRG_CODE_9]			VARCHAR(30)
	,[CHRG_DESC_9]			VARCHAR(20)
	,[CHRG_CURR_9]			VARCHAR(3)
	,[CHRG_AMNT_9]			VARCHAR(15)

	,[CHRG_CODE_10]			VARCHAR(30)
	,[CHRG_DESC_10]			VARCHAR(20)
	,[CHRG_CURR_10]			VARCHAR(3)
	,[CHRG_AMNT_10]			VARCHAR(15)

	,[CHRG_CODE_11]			VARCHAR(30)
	,[CHRG_DESC_11]			VARCHAR(20)
	,[CHRG_CURR_11]			VARCHAR(3)
	,[CHRG_AMNT_11]			VARCHAR(15)
	
	,[CHRG_CODE_12]			VARCHAR(30)
	,[CHRG_DESC_12]			VARCHAR(20)
	,[CHRG_CURR_12]			VARCHAR(3)
	,[CHRG_AMNT_12]			VARCHAR(15)

	,[CHRG_CODE_13]			VARCHAR(30)
	,[CHRG_DESC_13]			VARCHAR(20)
	,[CHRG_CURR_13]			VARCHAR(3)
	,[CHRG_AMNT_13]			VARCHAR(15)

	,[CHRG_CODE_14]			VARCHAR(30)
	,[CHRG_DESC_14]			VARCHAR(20)
	,[CHRG_CURR_14]			VARCHAR(3)
	,[CHRG_AMNT_14]			VARCHAR(15)

	,[CHRG_CODE_15]			VARCHAR(30)
	,[CHRG_DESC_15]			VARCHAR(20)
	,[CHRG_CURR_15]			VARCHAR(3)
	,[CHRG_AMNT_15]			VARCHAR(15)

	,[VAT_CODE]				CHAR(1)			--VARCHAR(3)
	,[VAT_CURR]				CHAR(1)			--VARCHAR(3)
	,[VAT_AMNT]				CHAR(1)			--VARCHAR(15)
	,[CURR_CONVERT_1]		VARCHAR(3)
	,[CURR_EXCHANGE_1]		VARCHAR(15)
	,[CURR_CONVERT_2]		VARCHAR(3)
	,[CURR_EXCHANGE_2]		VARCHAR(15)
	,[CURR_PAYMENT]			VARCHAR(3)
	,[TOTAL_EXCL_VAT]		CHAR(1)			--VARCHAR(15)
	,[TOTAL_INCL_VAT]		CHAR(1)			--VARCHAR(15)

	) ON [PRIMARY]
-------------------------------------------------------------------------------------------------------------------------
	CREATE TABLE tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS
(
	[BILLING_NUMBER]		VARCHAR(22)
	,[CHRG_CODE_1]			VARCHAR(30)
	,[CHRG_DESC_1]			VARCHAR(20)
	,[CHRG_CURR_1]			VARCHAR(3)
	,[CHRG_AMNT_1]			VARCHAR(15)

	,[CHRG_CODE_2]			VARCHAR(30)
	,[CHRG_DESC_2]			VARCHAR(20)
	,[CHRG_CURR_2]			VARCHAR(3)
	,[CHRG_AMNT_2]			VARCHAR(15)

	,[CHRG_CODE_3]			VARCHAR(30)
	,[CHRG_DESC_3]			VARCHAR(20)
	,[CHRG_CURR_3]			VARCHAR(3)
	,[CHRG_AMNT_3]			VARCHAR(15)

	,[CHRG_CODE_4]			VARCHAR(30)
	,[CHRG_DESC_4]			VARCHAR(20)
	,[CHRG_CURR_4]			VARCHAR(3)
	,[CHRG_AMNT_4]			VARCHAR(15)

	,[CHRG_CODE_5]			VARCHAR(30)
	,[CHRG_DESC_5]			VARCHAR(20)
	,[CHRG_CURR_5]			VARCHAR(3)
	,[CHRG_AMNT_5]			VARCHAR(15)

	,[CHRG_CODE_6]			VARCHAR(30)
	,[CHRG_DESC_6]			VARCHAR(20)
	,[CHRG_CURR_6]			VARCHAR(3)
	,[CHRG_AMNT_6]			VARCHAR(15)

	,[CHRG_CODE_7]			VARCHAR(30)
	,[CHRG_DESC_7]			VARCHAR(20)
	,[CHRG_CURR_7]			VARCHAR(3)
	,[CHRG_AMNT_7]			VARCHAR(15)

	,[CHRG_CODE_8]			VARCHAR(30)
	,[CHRG_DESC_8]			VARCHAR(02)
	,[CHRG_CURR_8]			VARCHAR(3)
	,[CHRG_AMNT_8]			VARCHAR(15)

	,[CHRG_CODE_9]			VARCHAR(30)
	,[CHRG_DESC_9]			VARCHAR(20)
	,[CHRG_CURR_9]			VARCHAR(3)
	,[CHRG_AMNT_9]			VARCHAR(15)

	,[CHRG_CODE_10]			VARCHAR(30)
	,[CHRG_DESC_10]			VARCHAR(20)
	,[CHRG_CURR_10]			VARCHAR(3)
	,[CHRG_AMNT_10]			VARCHAR(15)

	,[CHRG_CODE_11]			VARCHAR(30)
	,[CHRG_DESC_11]			VARCHAR(20)
	,[CHRG_CURR_11]			VARCHAR(3)
	,[CHRG_AMNT_11]			VARCHAR(15)
	
	,[CHRG_CODE_12]			VARCHAR(30)
	,[CHRG_DESC_12]			VARCHAR(20)
	,[CHRG_CURR_12]			VARCHAR(3)
	,[CHRG_AMNT_12]			VARCHAR(15)

	,[CHRG_CODE_13]			VARCHAR(30)
	,[CHRG_DESC_13]			VARCHAR(20)
	,[CHRG_CURR_13]			VARCHAR(3)
	,[CHRG_AMNT_13]			VARCHAR(15)

	,[CHRG_CODE_14]			VARCHAR(30)
	,[CHRG_DESC_14]			VARCHAR(20)
	,[CHRG_CURR_14]			VARCHAR(3)
	,[CHRG_AMNT_14]			VARCHAR(15)

	,[CHRG_CODE_15]			VARCHAR(30)
	,[CHRG_DESC_15]			VARCHAR(20)
	,[CHRG_CURR_15]			VARCHAR(3)
	,[CHRG_AMNT_15]			VARCHAR(15)

	,[VAT_CODE]				CHAR(1)			--VARCHAR(3)
	,[VAT_CURR]				CHAR(1)			--VARCHAR(3)
	,[VAT_AMNT]				CHAR(1)			--VARCHAR(15)
	,[CURR_CONVERT_1]		VARCHAR(3)
	,[CURR_EXCHANGE_1]		VARCHAR(15)
	,[CURR_CONVERT_2]		VARCHAR(3)
	,[CURR_EXCHANGE_2]		VARCHAR(15)
	,[CURR_PAYMENT]			VARCHAR(3)
	,[TOTAL_EXCL_VAT]		CHAR(1)			--VARCHAR(15)
	,[TOTAL_INCL_VAT]		CHAR(1)			--VARCHAR(15)
)

-------------------------------------------------------------------------------------------------------------------------
-- POPULANDO TABELAS
-------------------------------------------------------------------------------------------------------------------------

-- TABELA BASE - INVOICE
	SELECT 
	null Invoice_Seq
	,FAT.fatCod
	,FAT.cd_pes
	,FAT.fatdtvenc
	,FAT.fatStatus
	,FAT.FatDTEmissao
	,ITF.Num_Proc
	,ITF.IDItemFat
	,ITF.CD_tp_tx
	,ITF.dc
	,ITF.CD_TP_MOEDA
	,ITF.VLR_ORG
	,ITF.VLR_RS
	,ITF.PARIDADE
	into tmp_Rel_SCHCASS_INVOICE
	FROM Fatura FAT (NOLOCK)
	INNER JOIN Item_fat ITF (nolock)
		ON FAT.FatCod = ITF.FatCod
	WHERE num_proc like '%SCH%'
	and FAT.fatstatus <> 0 -- Não envia as canceladas
	and FAT.FatDtEmissao between @DtInicial and @DtFinal
	and FAT.FatCod like @FatCod

	
-- TABELA DETALHE - INVOICE
	SELECT DISTINCT
	NUM_PROC
	,FATCOD
	,convert(varchar, FATDTEMISSAO, 112)	AS FATDTEMISSAO
	,convert(varchar, fatdtvenc, 112)		AS FATDTVENC
	,CONVERT(VARCHAR(3),NULL)				AS CURR_CONVERT_1
	,CONVERT(FLOAT,NULL)					AS CURR_EXCHANGE_1
	,CONVERT(VARCHAR(3),NULL)				AS CURR_CONVERT_2
	,CONVERT(FLOAT,NULL)					AS CURR_EXCHANGE_2
	INTO tmp_Rel_SCHCASS_INVOICE_TRATADO
	FROM tmp_Rel_SCHCASS_INVOICE

	SELECT 
	FATCOD
	,MIN(PARIDADE)				AS PARIDADE_01
	,CONVERT(VARCHAR(3),NULL)	AS MOEDA_PARIDADE_01
	,MAX(PARIDADE)				AS PARIDADE_02
	,CONVERT(VARCHAR(3),NULL)	AS MOEDA_PARIDADE_02
	,	(SELECT COUNT(DISTINCT CD_TP_MOEDA)
		FROM tmp_Rel_SCHCASS_INVOICE TMP2
		WHERE TMP1.FATCOD = TMP2.FATCOD
		) AS QTD_PARIDADE
	into tmp_Rel_SCHCASS_INVOICE_PARIDADES
	FROM tmp_Rel_SCHCASS_INVOICE TMP1
	--WHERE FATCOD = 'IASCH202010001BRA'
	GROUP BY FATCOD

	UPDATE tmp_Rel_SCHCASS_INVOICE_PARIDADES
	SET 
	MOEDA_PARIDADE_01 = 
							(SELECT TOP 1 CD_TP_MOEDA 
							FROM tmp_Rel_SCHCASS_INVOICE P2 
							WHERE P2.FATCOD = P.FATCOD 
							AND P2.PARIDADE = PARIDADE_01) 
	,MOEDA_PARIDADE_02 = 
							(SELECT TOP 1 CD_TP_MOEDA 
							FROM tmp_Rel_SCHCASS_INVOICE P3
							WHERE P3.FATCOD = P.FATCOD 
							AND P3.PARIDADE = PARIDADE_02) 
	FROM tmp_Rel_SCHCASS_INVOICE_PARIDADES P



	UPDATE tmp_Rel_SCHCASS_INVOICE_TRATADO
	SET CURR_CONVERT_1 = MOEDA_PARIDADE_01
	,CURR_EXCHANGE_1 = PARIDADE_01
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO T
	INNER JOIN tmp_Rel_SCHCASS_INVOICE_PARIDADES P
		ON T.FATCOD = P.FATCOD
	WHERE QTD_PARIDADE = 1

	UPDATE tmp_Rel_SCHCASS_INVOICE_TRATADO
	SET CURR_CONVERT_1 = MOEDA_PARIDADE_01
	,CURR_EXCHANGE_1 = PARIDADE_01 
	,CURR_CONVERT_2 = MOEDA_PARIDADE_02
	,CURR_EXCHANGE_2 = PARIDADE_02
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO T
	INNER JOIN tmp_Rel_SCHCASS_INVOICE_PARIDADES P
		ON T.FATCOD = P.FATCOD
	WHERE QTD_PARIDADE = 2




	
	Declare @Tab_Invoice_Seq table (FATCOD varchar(17),idItemFat bigint)
	
	insert into @Tab_Invoice_Seq
	select FATCOD,idItemFat from tmp_Rel_SCHCASS_INVOICE with(nolock) 

	declare @HSGSeq  int=null
	Declare @FATCOD_CUR	varchar(17) 
	declare @idItemFat bigint


	Declare Cur_invoice_seq cursor for 
	select FATCOD, idItemFat from @Tab_Invoice_Seq
	
	open Cur_invoice_seq
		Fetch Next From Cur_invoice_seq Into @FATCOD_CUR,@idItemFat
		While @@FETCH_STATUS = 0
		Begin
			Set @HSGSeq = IsNull((Select Max(Invoice_Seq) From tmp_Rel_SCHCASS_INVOICE Where fatCod = @FATCOD_CUR),0) + 1 
			
			update tmp_Rel_SCHCASS_INVOICE set Invoice_Seq = @HSGSeq
			where FATCOD= @FATCOD_CUR
			and	idItemFat=@idItemFat
			
			Fetch Next From Cur_invoice_seq Into @FATCOD_CUR,@idItemFat
		end
	close Cur_invoice_seq
	deallocate Cur_invoice_seq 

	DELETE from @Tab_Invoice_Seq

	INSERT tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS(BILLING_NUMBER)
	SELECT DISTINCT fatCod FROM  tmp_Rel_SCHCASS_INVOICE

	UPDATE final
	SET CHRG_CODE_1 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_1 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_1 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_1 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 1
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_2 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_2 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_2 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_2 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 2
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_3 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_3 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_3 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_3 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 3
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_4 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_4 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_4 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_4 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 4
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_5 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_5 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_5 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_5 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 5
	AND TMP.CD_TP_TX IS NOT NULL
	
	UPDATE final
	SET CHRG_CODE_6 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_6 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_6 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_6 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 6
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_7 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_7 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_7 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_7 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 7
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_8 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_8 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_8 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_8 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 8
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_9 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_9 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_9 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_9 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 9
	AND TMP.CD_TP_TX IS NOT NULL
	
	UPDATE final
	SET CHRG_CODE_10 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_10 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_10 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_10 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 10
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_11 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_11 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_11 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_11 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 11
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_12 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_12 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_12 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_12 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 12
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_13 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_13 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_13 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_13 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 13
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_14 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_14 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_14 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_14 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 14
	AND TMP.CD_TP_TX IS NOT NULL

	UPDATE final
	SET CHRG_CODE_15 = ISNULL(CONVERT(VARCHAR(10),SCH.CD_TP_TX_SCH),'NOMAP_'+TMP.CD_TP_TX)
	,CHRG_DESC_15 = replace(LEFT(TT.NOME_TP_TX,20),',','.')
	,CHRG_CURR_15 = TMP.CD_TP_MOEDA
	,CHRG_AMNT_15 = VLR_RS
	FROM tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS FINAL
	INNER JOIN tmp_Rel_SCHCASS_INVOICE TMP
		ON BILLING_NUMBER = TMP.fatCod
	INNER JOIN TIPO_TAXA TT
		ON TT.CD_TP_TX = TMP.CD_TP_TX
	LEFT JOIN TIPO_TAXA_CASS_SCH SCH 
		ON TMP.CD_TP_TX = SCH.CD_TP_TX
	WHERE Invoice_Seq = 15
	AND TMP.CD_TP_TX IS NOT NULL
	
-- TABELA DETALHE - JOB IMPORTAÇÃO
	select distinct 
	HOU.num_proc
	,TMP.FATCOD
	--,''															AS CARRIER_ID
	--,ISNULL(SHP.GLOBAL_ENTITY_ID,'')							AS SHIPPER_ID --ISNULL(SHP.Cd_Pes ,SHP.GLOBAL_ENTITY_ID)
	,'124567'													AS SHIPPER_ID
	,'000000000000000000000000000000'							AS SHIPPER_ACCOUNT
	,CASE
			WHEN SUBSTRING(HOU.num_proc,2,1) = 'M' THEN 'O'
			WHEN SUBSTRING(HOU.num_proc,2,1) = 'A' THEN 'A'
			ELSE NULL --ELSE 'J'
		END														AS MODE
	,CASE
			WHEN SUBSTRING(HOU.num_proc,1,1) = 'I' THEN '1'
			WHEN SUBSTRING(HOU.num_proc,1,1) = 'E' THEN '2'
			ELSE NULL --ELSE 'J'
		END														AS MOVEMENT
	,SHP.Cd_Pes													AS SHIPPER_SID_1
	,convert(varchar(22),null)									AS SHIPPER_SID_3
	,HOU.HAWB													AS CARRIER_PRO_1
	,HOU.MAWB													AS CARRIER_PRO_2
	
	,REPLACE(SHP.Nome_Raz_Soc,',','.')							AS SHIPPER_NAME
	,SHPEND.CEP													AS SHIPPER_ZIP
	,REPLACE(SHPEND.Cidade,',','.')								AS SHIPPER_CITY
	,SHPEND.UF													AS SHIPPER_STATE
	,REPLACE(SHPEND.RUA + ' ' + SHPEND.NUMERO,',','.')			AS SHIPPER_STREET
	,SHPEND.CD_pais												AS SHIPPER_CTRY

	,REPLACE(CON.Nome_Raz_Soc,',','.')							AS CONSIGNEE_NAME
	,CONEND.CEP													AS CONSIGNEE_ZIP
	,REPLACE(CONEND.Cidade,',','.')								AS CONSIGNEE_CITY
	,CONEND.UF													AS CONSIGNEE_STATE
	,REPLACE(CONEND.RUA + ' ' + CONEND.NUMERO,',','.')			AS CONSIGNEE_STREET
	,CONEND.CD_pais												AS CONSIGNEE_CTRY

	,HOU.Cd_Tp_Oper												AS INCO_TERMS

	,convert(varchar, HOU.ATD, 112)								AS SHIP_DATE
	,convert(varchar, HOU.ATD, 112)								AS DEPART_DATE
	,convert(varchar, HOU.ATA, 112)								AS ARRIVAL_DATE
	,convert(varchar, TASK.DT_CONCLUSAO, 112)					AS DELIVERY_DATE

	,CASE 
		WHEN ISNULL(TC.Nome_Tp_Carga,'')='FCL' THEN 'CF'
		WHEN ISNULL(TC.Nome_Tp_Carga,'')='LCL' THEN 'CL'
		WHEN ISNULL(CP206.Campo_Dados,'')<>'' THEN CP206.Campo_Dados
		ELSE ''
	END															AS SERVICE

	,CASE 
		WHEN ISNULL(TC.Nome_Tp_Carga,'')<>'' THEN TC.Nome_Tp_Carga
		WHEN ISNULL(CP206.Campo_Dados,'')<>'' THEN TSSCH.Descr_Servico
		ELSE ''
	END															AS SERVICE_DESC

	,CarrierName												AS SHIPPING_LINE
	,Peso_Bruto													AS GROSS_WEIGHT
	,CONVERT(VARCHAR(17),Qtd_Vol)								AS VOLUME
	,CONVERT(VARCHAR(17),Peso_Cubado)							AS CHARGE_WEIGHT
	INTO tmp_Rel_SCHCASS_JOB_AUX
	FROM tmp_Rel_SCHCASS_INVOICE tmp (nolock)
	INNER JOIN vwHouse_Imp hou
		ON tmp.Num_Proc = hou.num_proc

	--SHIPPER
	INNER JOIN Pessoa SHP (nolock)  
		ON HOU.Cd_Export  = SHP.Cd_Pes  
	LEFT JOIN Endereco SHPEND (nolock) 
		ON SHPEND.cd_pes=SHP.cd_pes AND SHPEND.cd_tp_end='COM'  

	--CONSIGNEE
	INNER JOIN Pessoa CON (nolock)  
		ON HOU.Cd_Consig  = CON.Cd_Pes
	LEFT JOIN Endereco CONEND (nolock) 
		ON CONEND.cd_pes=CON.cd_pes AND CONEND.cd_tp_end='COM' 

	-- TASKS / TAREFAS
	LEFT JOIN TAREFAS_PROCESSOS TASK
	ON HOU.num_proc = TASK.num_proc and TASK.ID_TASK = 13

	--ADDITIONAL FIELDS / CAMPOS ADICIONAIS
	LEFT JOIN Campo_Processo CP206 (nolock)  
		ON HOU.Num_Proc = CP206.Num_Proc 
		AND CP206.Id_Campo = 206 
	LEFT JOIN tipo_servico_SCH TSSCH (nolock) 
		ON CP206.Campo_Dados = TSSCH.CD_TIPO_SERVICO
	--LCL/FCL
	LEFT JOIN Tipo_Carga  TC (NOLOCK)   
		ON HOU.Tp_Carga = TC.Cd_Tp_Carga 

-- TABELA DETALHE - JOB EXMPORTAÇÃO
	insert into tmp_Rel_SCHCASS_JOB_AUX
	select distinct 
	HOU.num_proc
	,TMP.FATCOD
	--,''															AS CARRIER_ID
	--,ISNULL(SHP.GLOBAL_ENTITY_ID,'')							AS SHIPPER_ID --ISNULL(SHP.Cd_Pes ,SHP.GLOBAL_ENTITY_ID)
	,'124567'													AS SHIPPER_ID
	,'000000000000000000000000000000'							AS SHIPPER_ACCOUNT
	,CASE
			WHEN SUBSTRING(HOU.num_proc,2,1) = 'M' THEN 'O'
			WHEN SUBSTRING(HOU.num_proc,2,1) = 'A' THEN 'A'
			ELSE NULL --ELSE 'J'
		END														AS MODE
	,CASE
			WHEN SUBSTRING(HOU.num_proc,1,1) = 'I' THEN '1'
			WHEN SUBSTRING(HOU.num_proc,1,1) = 'E' THEN '2'
			ELSE NULL --ELSE 'J'
		END														AS MOVEMENT
	,SHP.Cd_Pes													AS SHIPPER_SID_1
	,convert(varchar(22),null)									AS SHIPPER_SID_3
	,HOU.HAWB													AS CARRIER_PRO_1
	,HOU.MAWB													AS CARRIER_PRO_2
	
	,REPLACE(SHP.Nome_Raz_Soc,',','.')							AS SHIPPER_NAME
	,SHPEND.CEP													AS SHIPPER_ZIP
	,REPLACE(SHPEND.Cidade,',','.')								AS SHIPPER_CITY
	,SHPEND.UF													AS SHIPPER_STATE
	,REPLACE(SHPEND.RUA + ' ' + SHPEND.NUMERO,',','.')			AS SHIPPER_STREET
	,SHPEND.CD_pais												AS SHIPPER_CTRY

	,REPLACE(CON.Nome_Raz_Soc,',','.')							AS CONSIGNEE_NAME
	,CONEND.CEP													AS CONSIGNEE_ZIP
	,REPLACE(CONEND.Cidade,',','.')								AS CONSIGNEE_CITY
	,CONEND.UF													AS CONSIGNEE_STATE
	,REPLACE(CONEND.RUA + ' ' + CONEND.NUMERO,',','.')			AS CONSIGNEE_STREET
	,CONEND.CD_pais												AS CONSIGNEE_CTRY

	,HOU.Cd_Tp_Oper												AS INCO_TERMS

	,convert(varchar, HOU.ATD, 112)								AS SHIP_DATE
	,convert(varchar, HOU.ATD, 112)								AS DEPART_DATE
	,convert(varchar, HOU.ATA, 112)								AS ARRIVAL_DATE
	,convert(varchar, TASK.DT_CONCLUSAO, 112)					AS DELIVERY_DATE

	,CASE 
		WHEN ISNULL(TC.Nome_Tp_Carga,'')='FCL' THEN 'CF'
		WHEN ISNULL(TC.Nome_Tp_Carga,'')='LCL' THEN 'CL'
		WHEN ISNULL(CP206.Campo_Dados,'')<>'' THEN CP206.Campo_Dados
		ELSE ''
	END															AS SERVICE

	,CASE 
		WHEN ISNULL(TC.Nome_Tp_Carga,'')<>'' THEN TC.Nome_Tp_Carga
		WHEN ISNULL(CP206.Campo_Dados,'')<>'' THEN TSSCH.Descr_Servico
		ELSE ''
	END															AS SERVICE_DESC

	,Vessel														AS SHIPPING_LINE
	,Peso_Bruto													AS GROSS_WEIGHT
	,CONVERT(VARCHAR(17),Qtd_Vol)								AS VOLUME
	,CONVERT(VARCHAR(17),Peso_Cubado)							AS CHARGE_WEIGHT
	FROM tmp_Rel_SCHCASS_INVOICE tmp (nolock)
	INNER JOIN vwHouse_Exp hou
		ON tmp.Num_Proc = hou.num_proc

	--SHIPPER
	INNER JOIN Pessoa SHP (nolock)  
		ON HOU.Cd_Export  = SHP.Cd_Pes  
	LEFT JOIN Endereco SHPEND (nolock) 
		ON SHPEND.cd_pes=SHP.cd_pes AND SHPEND.cd_tp_end='COM'  

	--CONSIGNEE
	INNER JOIN Pessoa CON (nolock)  
		ON HOU.Cd_Consig  = CON.Cd_Pes
	LEFT JOIN Endereco CONEND (nolock) 
		ON CONEND.cd_pes=CON.cd_pes AND CONEND.cd_tp_end='COM' 

	-- TASKS / TAREFAS
	LEFT JOIN TAREFAS_PROCESSOS TASK
	ON HOU.num_proc = TASK.num_proc and TASK.ID_TASK = 13

	--ADDITIONAL FIELDS / CAMPOS ADICIONAIS
	LEFT JOIN Campo_Processo CP206 (nolock)  
		ON HOU.Num_Proc = CP206.Num_Proc 
		AND CP206.Id_Campo = 206 
	LEFT JOIN tipo_servico_SCH TSSCH (nolock) 
		ON CP206.Campo_Dados = TSSCH.CD_TIPO_SERVICO
	--LCL/FCL
	LEFT JOIN Tipo_Carga  TC (NOLOCK)   
		ON HOU.Cd_Tp_Carga = TC.Cd_Tp_Carga 



	SELECT 
	DISTINCT
	HOU.NUM_PROC
	,ISNULL(CONTHAI.Itinerary_ID,CP202.Campo_Dados)	ITINERARY_ID
	INTO tmp_Rel_SCHCASS_JOB_ITINERARY_ID
	FROM tmp_Rel_SCHCASS_JOB_AUX HOU
	LEFT JOIN Container_Hou_Imp_Mar CONTH (nolock) 
		ON HOU.NUM_PROC = CONTH.num_proc_him

	LEFT JOIN container_mas_imp_mar CONTM (nolock) 
		ON CONTH.item_cont_im = CONTM.item_cont_im AND CONTH.Num_Proc_MIM = CONTM.Num_Proc_MIM

	LEFT JOIN container_additional_info CONTHAI (NOLOCK)
		ON CONTH.num_proc_him = CONTHAI.NUM_PROC
		AND REPLACE(CONTM.Num_Cont_IM ,'-','') = REPLACE(CONTHAI.num_cont,'-','')
	LEFT JOIN Campo_Processo CP202 (nolock)  
		ON HOU.Num_Proc collate SQL_Latin1_General_CP1_CI_AS = CP202.Num_Proc collate SQL_Latin1_General_CP1_CI_AS  AND CP202.Id_Campo = 202 
	WHERE ISNULL(CONTHAI.Itinerary_ID,CP202.Campo_Dados) IS NOT NULL

	update tmp_Rel_SCHCASS_JOB_AUX
	set SHIPPER_SID_3 = dbo.fBusca_SCH_Itinarary_ID(num_proc)

	TRUNCATE TABLE tmp_Schneider_CASS

	INSERT INTO tmp_Schneider_CASS
	(
	[CARRIER_ID] 
	,[SHIPPER_ID]		
	,[SHIPPER_ACCOUNT]	
	,[MODE]			
	,[MOVEMENT]		
	,[BILLING_NUMBER]	
	,[BILLING_DATE]		
	,[SHIPPER_SID_1]	
	,[SHIPPER_SID_2]	
	,[SHIPPER_SID_3]	
	,[CARRIER_PRO_1]	
	,[CARRIER_PRO_2]	
	,[CARRIER_PRO_3]	
	,[SHIPPER_NAME]		
	,[SHIPPER_ZIP]		
	,[SHIPPER_CITY]		
	,[SHIPPER_STATE]	
	,[SHIPPER_STREET]	
	,[SHIPPER_CTRY]		
	,[CONSIGNEE_NAME]	
	,[CONSIGNEE_ZIP]	
	,[CONSIGNEE_CITY]	
	,[CONSIGNEE_STATE]	
	,[CONSIGNEE_STREET]	
	,[CONSIGNEE_CTRY]	
	,[STOPOFF_1_NAME]	
	,[STOPOFF_1_ZIP]	
	,[STOPOFF_1_CITY]	
	,[STOPOFF_1_STATE]	
	,[STOPOFF_1_STREET]	
	,[STOPOFF_1_CTRY]	
	,[STOPOFF_1_LOC]	
	,[STOPOFF_2_NAME]	
	,[STOPOFF_2_ZIP]	
	,[STOPOFF_2_CITY]	
	,[STOPOFF_2_STATE]	
	,[STOPOFF_2_STREET]	
	,[STOPOFF_2_CTRY]	
	,[STOPOFF_2_LOC]	
	,[STOPOFF_3_NAME]	
	,[STOPOFF_3_ZIP]	
	,[STOPOFF_3_CITY]	
	,[STOPOFF_3_STATE]	
	,[STOPOFF_3_STREET]	
	,[STOPOFF_3_CTRY]	
	,[STOPOFF_3_LOC]	
	,[STOPOFF_4_NAME]	
	,[STOPOFF_4_ZIP]	
	,[STOPOFF_4_CITY]	
	,[STOPOFF_4_STATE]	
	,[STOPOFF_4_STREET]	
	,[STOPOFF_4_CTRY]	
	,[STOPOFF_4_LOC]	
	,[STOPOFF_5_NAME]	
	,[STOPOFF_5_ZIP]	
	,[STOPOFF_5_CITY]	
	,[STOPOFF_5_STATE]	
	,[STOPOFF_5_STREET]	
	,[STOPOFF_5_CTRY]	
	,[STOPOFF_5_LOC]	
	,[DISTANCE_KM]		
	,[INCO_TERMS]		
	,[SHIP_DATE]		
	,[DEPART_DATE]		
	,[ARRIVAL_DATE]		
	,[DELIVERY_DATE]	
	,[SERVICE]		
	,[SERVICE_DESC]		
	,[EQUIPMENT]		
	,[EQUIPMENT_REF]	
	,[SHIPPING_LINE]	
	,[GROSS_WEIGHT]		
	,[VOLUME]		
	,[DIM_WEIGHT]		
	,[CHARGE_WEIGHT]	
	,[LOADING_METERS]	
	,[UOM_CODE_1]		
	,[UOM_QTY_1]		
	,[UOM_CODE_2]		
	,[UOM_QTY_2]		
	,[UOM_CODE_3]		
	,[UOM_QTY_3]		
	
	,[CHRG_CODE_1]		
	,[CHRG_DESC_1]		
	,[CHRG_CURR_1]		
	,[CHRG_AMNT_1]		
	,[CHRG_CODE_2]		
	,[CHRG_DESC_2]		
	,[CHRG_CURR_2]		
	,[CHRG_AMNT_2]		
	,[CHRG_CODE_3]		
	,[CHRG_DESC_3]		
	,[CHRG_CURR_3]		
	,[CHRG_AMNT_3]		
	,[CHRG_CODE_4]		
	,[CHRG_DESC_4]		
	,[CHRG_CURR_4]		
	,[CHRG_AMNT_4]		
	,[CHRG_CODE_5]		
	,[CHRG_DESC_5]		
	,[CHRG_CURR_5]		
	,[CHRG_AMNT_5]		
	,[CHRG_CODE_6]		
	,[CHRG_DESC_6]		
	,[CHRG_CURR_6]		
	,[CHRG_AMNT_6]		
	,[CHRG_CODE_7]		
	,[CHRG_DESC_7]		
	,[CHRG_CURR_7]		
	,[CHRG_AMNT_7]		
	,[CHRG_CODE_8]		
	,[CHRG_DESC_8]		
	,[CHRG_CURR_8]		
	,[CHRG_AMNT_8]		
	,[CHRG_CODE_9]		
	,[CHRG_DESC_9]		
	,[CHRG_CURR_9]		
	,[CHRG_AMNT_9]		
	,[CHRG_CODE_10]		
	,[CHRG_DESC_10]		
	,[CHRG_CURR_10]		
	,[CHRG_AMNT_10]		
	,[CHRG_CODE_11]		
	,[CHRG_DESC_11]		
	,[CHRG_CURR_11]		
	,[CHRG_AMNT_11]		
	,[CHRG_CODE_12]		
	,[CHRG_DESC_12]		
	,[CHRG_CURR_12]		
	,[CHRG_AMNT_12]		
	,[CHRG_CODE_13]		
	,[CHRG_DESC_13]		
	,[CHRG_CURR_13]		
	,[CHRG_AMNT_13]		
	,[CHRG_CODE_14]		
	,[CHRG_DESC_14]		
	,[CHRG_CURR_14]		
	,[CHRG_AMNT_14]		
	,[CHRG_CODE_15]		
	,[CHRG_DESC_15]		
	,[CHRG_CURR_15]		
	,[CHRG_AMNT_15]		
	,[VAT_CODE]		
	,[VAT_CURR]		
	,[VAT_AMNT]		
	,[CURR_CONVERT_1]	
	,[CURR_EXCHANGE_1]	
	,[CURR_CONVERT_2]	
	,[CURR_EXCHANGE_2]	
	,[CURR_PAYMENT]		
	,[TOTAL_EXCL_VAT]	
	,[TOTAL_INCL_VAT]
	)
	SELECT 
	'BDPBR00000N'						AS [CARRIER_ID] -- PENDENTE
	,AUX.SHIPPER_ID						AS [SHIPPER_ID]	-- PENDENTE	
	,AUX.SHIPPER_ACCOUNT				AS [SHIPPER_ACCOUNT] -- PENDENTE		

	,AUX.MODE							AS [MODE]					
	,AUX.MOVEMENT						AS [MOVEMENT]		
	,INV.FATCOD							AS [BILLING_NUMBER]	
	,INV.FATDTVENC						AS [BILLING_DATE]	
	
	,AUX.SHIPPER_SID_1					AS [SHIPPER_SID_1]	-- PENDENTE
	,''									AS [SHIPPER_SID_2]	
	,isnull(SHIPPER_SID_3,'')			AS [SHIPPER_SID_3]	-- PENDENTE	
	,AUX.CARRIER_PRO_1					AS [CARRIER_PRO_1]	
	,AUX.CARRIER_PRO_2					AS [CARRIER_PRO_2]	
	,''									AS [CARRIER_PRO_3]	
	,AUX.SHIPPER_NAME					AS [SHIPPER_NAME]	
	,AUX.SHIPPER_ZIP					AS [SHIPPER_ZIP]		
	,AUX.SHIPPER_CITY					AS [SHIPPER_CITY]		
	,AUX.SHIPPER_STATE					AS [SHIPPER_STATE]	
	,AUX.SHIPPER_STREET					AS [SHIPPER_STREET]	
	,ISNULL(AUX.SHIPPER_CTRY,'')		AS [SHIPPER_CTRY]		
	,AUX.CONSIGNEE_NAME					AS [CONSIGNEE_NAME]	
	,AUX.CONSIGNEE_ZIP					AS [CONSIGNEE_ZIP]	
	,AUX.CONSIGNEE_CITY					AS [CONSIGNEE_CITY]	
	,AUX.CONSIGNEE_STATE				AS [CONSIGNEE_STATE]	
	,AUX.CONSIGNEE_STREET				AS [CONSIGNEE_STREET]	
	,ISNULL(AUX.CONSIGNEE_CTRY,'')		AS [CONSIGNEE_CTRY]	
	,''									AS [STOPOFF_1_NAME]	
	,''									AS [STOPOFF_1_ZIP]	
	,''									AS [STOPOFF_1_CITY]	
	,''									AS [STOPOFF_1_STATE]	
	,''									AS [STOPOFF_1_STREET]	
	,''									AS [STOPOFF_1_CTRY]	
	,''									AS [STOPOFF_1_LOC]	
	,''									AS [STOPOFF_2_NAME]	
	,''									AS [STOPOFF_2_ZIP]	
	,''									AS [STOPOFF_2_CITY]	
	,''									AS [STOPOFF_2_STATE]	
	,''									AS [STOPOFF_2_STREET]	
	,''									AS [STOPOFF_2_CTRY]	
	,''									AS [STOPOFF_2_LOC]	
	,''									AS [STOPOFF_3_NAME]	
	,''									AS [STOPOFF_3_ZIP]	
	,''									AS [STOPOFF_3_CITY]	
	,''									AS [STOPOFF_3_STATE]	
	,''									AS [STOPOFF_3_STREET]	
	,''									AS [STOPOFF_3_CTRY]	
	,''									AS [STOPOFF_3_LOC]	
	,''									AS [STOPOFF_4_NAME]	
	,''									AS [STOPOFF_4_ZIP]	
	,''									AS [STOPOFF_4_CITY]	
	,''									AS [STOPOFF_4_STATE]	
	,''									AS [STOPOFF_4_STREET]	
	,''									AS [STOPOFF_4_CTRY]	
	,''									AS [STOPOFF_4_LOC]	
	,''									AS [STOPOFF_5_NAME]	
	,''									AS [STOPOFF_5_ZIP]	
	,''									AS [STOPOFF_5_CITY]	
	,''									AS [STOPOFF_5_STATE]	
	,''									AS [STOPOFF_5_STREET]	
	,''									AS [STOPOFF_5_CTRY]	
	,''									AS [STOPOFF_5_LOC]	
	,''									AS [DISTANCE_KM]		
	,isnull(AUX.INCO_TERMS,'')			AS [INCO_TERMS]		
	,isnull(AUX.SHIP_DATE,'')			AS [SHIP_DATE]		
	,isnull(AUX.DEPART_DATE,'')			AS [DEPART_DATE]		
	,isnull(AUX.ARRIVAL_DATE,'')		AS [ARRIVAL_DATE]		
	,isnull(AUX.DELIVERY_DATE,'')		AS [DELIVERY_DATE]	
	,AUX.SERVICE						AS [SERVICE]		
	,AUX.SERVICE_DESC					AS [SERVICE_DESC]		
	,''									AS [EQUIPMENT]	-- PENDENTE			
	,''									AS [EQUIPMENT_REF]	-- PENDENTE		
	,AUX.SHIPPING_LINE					AS [SHIPPING_LINE]	
	,isnull(AUX.GROSS_WEIGHT,'')		AS [GROSS_WEIGHT]		
	,isnull(AUX.VOLUME,'')				AS [VOLUME]		
	,''									AS [DIM_WEIGHT]		
	,isnull(AUX.CHARGE_WEIGHT,'')		AS [CHARGE_WEIGHT]	
	,''									AS [LOADING_METERS]	
	,''									AS [UOM_CODE_1]		
	,''									AS [UOM_QTY_1]		
	,''									AS [UOM_CODE_2]		
	,''									AS [UOM_QTY_2]		
	,''									AS [UOM_CODE_3]		
	,''									AS [UOM_QTY_3]		
	
	,ISNULL(DET.[CHRG_CODE_1],'')		AS [CHRG_CODE_1]	
	,ISNULL(DET.[CHRG_DESC_1],'')		AS [CHRG_DESC_1]	
	,ISNULL(DET.[CHRG_CURR_1],'')		AS [CHRG_CURR_1]
	,ISNULL(DET.[CHRG_AMNT_1],'')		AS [CHRG_AMNT_1]
	,ISNULL(DET.[CHRG_CODE_2],'')		AS [CHRG_CODE_2] 		
	,ISNULL(DET.[CHRG_DESC_2],'')		AS [CHRG_DESC_2] 		
	,ISNULL(DET.[CHRG_CURR_2],'')		AS [CHRG_CURR_2]		
	,ISNULL(DET.[CHRG_AMNT_2],'')		AS [CHRG_AMNT_2] 		
	,ISNULL(DET.[CHRG_CODE_3],'')		AS [CHRG_CODE_3] 		
	,ISNULL(DET.[CHRG_DESC_3],'')		AS [CHRG_DESC_3] 		
	,ISNULL(DET.[CHRG_CURR_3],'')		AS [CHRG_CURR_3] 		
	,ISNULL(DET.[CHRG_AMNT_3],'')		AS [CHRG_AMNT_3]		
	,ISNULL(DET.[CHRG_CODE_4],'')		AS [CHRG_CODE_4]		
	,ISNULL(DET.[CHRG_DESC_4],'')		AS [CHRG_DESC_4]	
	,ISNULL(DET.[CHRG_CURR_4],'')		AS [CHRG_CURR_4]	
	,ISNULL(DET.[CHRG_AMNT_4],'')		AS [CHRG_AMNT_4]	
	,ISNULL(DET.[CHRG_CODE_5],'')		AS [CHRG_CODE_5]		
	,ISNULL(DET.[CHRG_DESC_5],'')		AS [CHRG_DESC_5]		
	,ISNULL(DET.[CHRG_CURR_5],'')		AS [CHRG_CURR_5]	
	,ISNULL(DET.[CHRG_AMNT_5],'')		AS [CHRG_AMNT_5]	
	,ISNULL(DET.[CHRG_CODE_6],'')		AS [CHRG_CODE_6]	
	,ISNULL(DET.[CHRG_DESC_6],'')		AS [CHRG_DESC_6]	
	,ISNULL(DET.[CHRG_CURR_6],'')		AS [CHRG_CURR_6]	
	,ISNULL(DET.[CHRG_AMNT_6],'')		AS [CHRG_AMNT_6]		
	,ISNULL(DET.[CHRG_CODE_7],'')		AS [CHRG_CODE_7]	
	,ISNULL(DET.[CHRG_DESC_7],'')		AS [CHRG_DESC_7]		
	,ISNULL(DET.[CHRG_CURR_7],'')		AS [CHRG_CURR_7]		
	,ISNULL(DET.[CHRG_AMNT_7],'')		AS [CHRG_AMNT_7]		
	,ISNULL(DET.[CHRG_CODE_8],'')		AS [CHRG_CODE_8]		
	,ISNULL(DET.[CHRG_DESC_8],'')		AS [CHRG_DESC_8]		
	,ISNULL(DET.[CHRG_CURR_8],'')		AS [CHRG_CURR_8] 		
	,ISNULL(DET.[CHRG_AMNT_8],'')		AS [CHRG_AMNT_8] 		
	,ISNULL(DET.[CHRG_CODE_9],'')		AS [CHRG_CODE_9]		
	,ISNULL(DET.[CHRG_DESC_9],'')		AS [CHRG_DESC_9] 		
	,ISNULL(DET.[CHRG_CURR_9],'')		AS [CHRG_CURR_9]		
	,ISNULL(DET.[CHRG_AMNT_9],'')		AS [CHRG_AMNT_9]		
	,ISNULL(DET.[CHRG_CODE_10],'')		AS [CHRG_CODE_10]		
	,ISNULL(DET.[CHRG_DESC_10],'')		AS [CHRG_DESC_10]		
	,ISNULL(DET.[CHRG_CURR_10],'')		AS [CHRG_CURR_10]		
	,ISNULL(DET.[CHRG_AMNT_10],'')		AS [CHRG_AMNT_10]		
	,ISNULL(DET.[CHRG_CODE_11],'')		AS [CHRG_CODE_11]		
	,ISNULL(DET.[CHRG_DESC_11],'')		AS [CHRG_DESC_11]		
	,ISNULL(DET.[CHRG_CURR_11],'')		AS [CHRG_CURR_11]		
	,ISNULL(DET.[CHRG_AMNT_11],'')		AS [CHRG_AMNT_11]		
	,ISNULL(DET.[CHRG_CODE_12],'')		AS [CHRG_CODE_12]		
	,ISNULL(DET.[CHRG_DESC_12],'')		AS [CHRG_DESC_12]		
	,ISNULL(DET.[CHRG_CURR_12],'')		AS [CHRG_CURR_12]		
	,ISNULL(DET.[CHRG_AMNT_12],'')		AS [CHRG_AMNT_12]		
	,ISNULL(DET.[CHRG_CODE_13],'')		AS [CHRG_CODE_13]		
	,ISNULL(DET.[CHRG_DESC_13],'')		AS [CHRG_DESC_13]		
	,ISNULL(DET.[CHRG_CURR_13],'')		AS [CHRG_CURR_13]		
	,ISNULL(DET.[CHRG_AMNT_13],'')		AS [CHRG_AMNT_13]		
	,ISNULL(DET.[CHRG_CODE_14],'')		AS [CHRG_CODE_14]		
	,ISNULL(DET.[CHRG_DESC_14],'')		AS [CHRG_DESC_14]		
	,ISNULL(DET.[CHRG_CURR_14],'')		AS [CHRG_CURR_14]		
	,ISNULL(DET.[CHRG_AMNT_14],'')		AS [CHRG_AMNT_14]		
	,ISNULL(DET.[CHRG_CODE_15],'')		AS [CHRG_CODE_15]		
	,ISNULL(DET.[CHRG_DESC_15],'')		AS [CHRG_DESC_15]		
	,ISNULL(DET.[CHRG_CURR_15],'')		AS [CHRG_CURR_15]		
	,ISNULL(DET.[CHRG_AMNT_15],'')		AS [CHRG_AMNT_15]	
	,''									AS [VAT_CODE]		
	,''									AS [VAT_CURR]		
	,''									AS [VAT_AMNT]		
	,ISNULL(INV.[CURR_CONVERT_1],'')	AS [CURR_CONVERT_1]	
	,ISNULL(INV.[CURR_EXCHANGE_1],'')	AS [CURR_EXCHANGE_1]
	,ISNULL(INV.[CURR_CONVERT_2],'')	AS [CURR_CONVERT_2]
	,ISNULL(INV.[CURR_EXCHANGE_2],'')	AS [CURR_EXCHANGE_2]
	,'BLR'								AS [CURR_PAYMENT]		
	,''									AS [TOTAL_EXCL_VAT]	
	,''									AS [TOTAL_INCL_VAT]
	from tmp_Rel_SCHCASS_JOB_AUX AUX (NOLOCK)
	INNER JOIN tmp_Rel_SCHCASS_INVOICE_TRATADO INV(NOLOCK)
		ON AUX.NUM_PROC = INV.NUM_PROC
		AND AUX.FATCOD = INV.FATCOD
	INNER JOIN tmp_Rel_SCHCASS_INVOICE_TRATADO_COLUNAS DET (NOLOCK)
		ON AUX.FATCOD = DET.BILLING_NUMBER

	SELECT * FROM tmp_Schneider_CASS



GO
